### ISSUE TITLE
BUG: Horizontal order of exogenous columns influences SARIMAX prediction

### ISSUE THREAD

**Issue by ComradeBronski** [statsmodels/statsmodels#7902] opened 2021-11-24 13:01 UTC
#### Describe the bug

I discovered that the order of the exogenous columns influences the SARIMAX prediction. 
If I train a model with the exog columns horizontally ordered alphabetically the prediction gives me one value. Retraining the model with everything exactly the same, with the exception that I randomly order the exogenous columns, the model prediction (and exogenous coefficients) is different.

My initial thought was that this is a bug, but I may be unaware of some underlying mechanism or configuration.

#### Code Sample, a copy-pastable example if possible

```python

order = (8,0,7)
sorder = (0,0,0,7)
trend = 'n'
method = 'powell'

SARIMAX(training.iloc[:,0], exog=training.iloc[:,1:], order=order, seasonal_order=sorder, trend=trend).fit(maxiter = 500, method=method)

```

**Comment by bashtage** [comment] 2021-11-24 23:21
Can you provide the data that will reproduce this issue.  If   I suspect that it is a numerical issue since the optimizer relies on a nonlinear optimizer. So you have the same issue when you choose a smaller order, e.g. ,order = (2,0,0)?  It is possible that your model is pooly identified which can happen if the residuals are near white noise and you have AR and MA terms, and so you are ending up at effectively random points in the unidentified region.  

Also, is the log-likelihood very different between the different estimates?

Ideally you could provide copy-pastable code and data that woudl reproduce.

**Comment by ComradeBronski** [comment] 2021-11-25 13:48
The log-likelihood is pretty similar 1718.770 versus 1717.790. The RMSE is ~3-4%

```
python
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.statespace.sarimax import SARIMAXResults

df = pd.DataFrame()
df = pd.read_csv('data.csv', header=0, parse_dates=True)
df = df.set_index('FullDate')
df.index = pd.to_datetime(df.index)
df = df.fillna(0)
df = df.asfreq('D')

order = (8,0,7)
sorder = (0,0,0,7)
method = 'powell'

model_exog = SARIMAX(df.iloc[:,0], exog=df.iloc[:,1:], order=order, seasonal_order=sorder).fit(maxiter = 500, method=method)
model_exog.summary()

# Reordered exog columns using sort_index(axis=1)

order = (8,0,7)
sorder = (0,0,0,7)
method = 'powell'

model_exog = SARIMAX(df.iloc[:,0], exog=df.iloc[:,1:].sort_index(axis=1), order=order, seasonal_order=sorder).fit(maxiter = 500, method=method)
model_exog.summary()
```

[data.csv](https://github.com/statsmodels/statsmodels/files/7603380/data.csv)

**Comment by ComradeBronski** [comment] 2021-11-29 13:40
I've carried out further testing and have found the following:

1.  If I change the order to (2,0,0) then move the columns around randomly, I still get different results. The accuracy drops ~9%, which is expected given the previous optimisation work already carried out.
2. I reduced the number of overall columns I was using by removing those that were not significant and with high error. The result was 
> a) a reduction in accuracy and 
> b) no improvement in the effect of moving around columns. I found that by simply moving a single column by a few places had the effect of reducing the prediction accuracy by 6%. 

3. I attempted to sort the columns using the p-value and t-values but all poorer results than the seemingly random sequence of columns I started with.

**Comment by ChadFulton** [comment] 2021-11-29 18:41
As @bashtage suggested, these differences are coming from the non-linear numerical optimizer.  In your example above, the optimizer is just finding different (local) maxima, and here this apparently depends on the parameter ordering (which is based on the ordering of the `exog` array).

One way to check that the models are defined identically in Statsmodels (except for the order of the `exog` columns) is to check that you get the same log-likelihood when you plug in the parameters from the model with the first ordering into the model with the second ordering:

```python
model_exog = SARIMAX(df.iloc[:,0], exog=df.iloc[:,1:], order=order, seasonal_order=sorder)
results_exog = model_exog.fit(maxiter = 500, method=method)
results_exog.summary()

# Reordered exog columns using sort_index(axis=1)
model_exog1 = SARIMAX(df.iloc[:,0], exog=df.iloc[:,1:].sort_index(axis=1), order=order, seasonal_order=sorder)

# Get the re-ordered version of the fitted parameters from the original ordering of exog
params = results_exog.params[model_exog1.param_names]
results_exog1 = model_exog1.smooth(params)

# Check that they are giving the same answer
print(results_exog.llf, results_exog1.llf)
```

```
1718.769927684969 1718.769927684969
```

**Comment by ChadFulton** [comment] 2021-11-29 18:42
Closing as an answered question, since this is not a bug, but feel free to continue to comment if you disagree or have questions

**Closed by ChadFulton** 2021-11-29 18:42 UTC
Labels: comp-tsa
