### ISSUE TITLE
Optimal number of features for VAR model

### ISSUE THREAD

**Issue by Chethan-Babu-stack** [statsmodels/statsmodels#7233] opened 2020-12-23 11:45 UTC
I have nearly 75,000 features in my time series data. I learnt how to find the maxlags for VAR(using AIC values), but maxlags of even 1 doesn't work(using 5000 features for test purpose).
Issue with maxlags = 1:
numpy.linalg.LinAlgError: 14-th leading minor of the array is not positive definite

I have an idea of selecting let's say 5(currently) features at a time and then using AIC values for different lags(1,2,3,4,5,6,7,8,9) and selecting the best maxlags for training my VAR model.

My question is, how do I know only 5 features to use at once? What is the optimal count of features to be used in this scenario?

Thanks in advance.

**Comment by bashtage** [comment] 2020-12-23 11:48
You cannot estimate a standard VAR with 5000 data points in practice. If you have a large number of variables you should probably use a feature reduction method such as PCA to extract the important components and then model these using a VAR or similar method.

**Comment by Chethan-Babu-stack** [comment] 2020-12-23 12:37
My features cannot be reduced. I have to retain all features in my dataset.

**Comment by bashtage** [comment] 2020-12-23 12:52
Then you will need to find a different way.  Standard VARs w/o restrictions are not suited for modelling high dimensional data.

**Comment by bashtage** [comment] 2020-12-23 12:52
You should probably ask on stats stackoverflow if you aren't sure what would be a reasonable approach.  I'm closing since there isn't anything that we can hope to fix here.

**Closed by bashtage** 2020-12-23 12:52 UTC

**Comment by josef-pkt** [comment] 2020-12-23 14:56
we had the discussion once, but statsmodels doesn't have any sparse var  #2933

There might be some newer R packages since that issue in 2016.

But I never heard trying to fit 75000 time series in one model.

Instead you could use lasso or scad penalization for each time series separately on lagged values, and use standard feature selection for linear regression.
