### ISSUE TITLE
error when building statsmodels from source

### ISSUE THREAD

**Issue by tsando** [statsmodels/statsmodels#4011] opened 2017-10-10 13:46 UTC
When I try to build statsmodels from source as per this instructions with Windows:

http://www.statsmodels.org/dev/install.html

using:

`python setup.py install`

I get the following error:

```
fatal error C1047: The object or library file 'C:\\Apps\\Anaconda3\\lib\\site-packages\\numpy\\core\\lib\npymath.lib' was created with an older
 compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed
```
any ideas how to solve this? I use Anaconda3 and numpy version 1.13.1. The full output from `python setup.py install` is below:

```
Cythonizing sources
statsmodels\nonparametric\linbin.pyx has not changed
statsmodels\nonparametric\_smoothers_lowess.pyx has not changed
statsmodels\tsa\kalmanf\kalman_loglike.pyx has not changed
statsmodels\tsa\regime_switching\_hamilton_filter.pyx.in has not changed
statsmodels\tsa\regime_switching\_kim_smoother.pyx.in has not changed
statsmodels\tsa\statespace\_kalman_filter.pyx.in has not changed
statsmodels\tsa\statespace\_kalman_smoother.pyx.in has not changed
statsmodels\tsa\statespace\_representation.pyx.in has not changed
statsmodels\tsa\statespace\_simulation_smoother.pyx.in has not changed
statsmodels\tsa\statespace\_statespace.pyx.in has not changed
statsmodels\tsa\statespace\_tools.pyx.in has not changed
statsmodels\tsa\statespace\_filters\_conventional.pyx.in has not changed
statsmodels\tsa\statespace\_filters\_inversions.pyx.in has not changed
statsmodels\tsa\statespace\_filters\_univariate.pyx.in has not changed
statsmodels\tsa\statespace\_smoothers\_alternative.pyx.in has not changed
statsmodels\tsa\statespace\_smoothers\_classical.pyx.in has not changed
statsmodels\tsa\statespace\_smoothers\_conventional.pyx.in has not changed
statsmodels\tsa\statespace\_smoothers\_univariate.pyx.in has not changed
running install
running bdist_egg
running egg_info
writing requirements to statsmodels.egg-info\requires.txt
writing statsmodels.egg-info\PKG-INFO
writing top-level names to statsmodels.egg-info\top_level.txt
writing dependency_links to statsmodels.egg-info\dependency_links.txt
package init file 'statsmodels\tsa\vector_ar\data\__init__.py' not found (or not a regular file)
reading manifest file 'statsmodels.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxi' anywhere in distribution
warning: no previously-included files matching '*' found under directory 'dist'
warning: no previously-included files found matching 'docs\source\generated\*'
warning: no previously-included files matching '*' found under directory 'docs\build'
warning: no previously-included files matching '*' found under directory 'docs\build\htmlhelp'
warning: no files found matching 'statsmodels\statsmodelsdoc.chm'
no previously-included directories found matching '*\__pycache__'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
writing manifest file 'statsmodels.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying statsmodels\version.py -> build\lib.win-amd64-3.5\statsmodels
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building 'statsmodels.tsa.statespace._statespace' extension
C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Istatsmode
ls/src -IC:\\Apps\\Anaconda3\\lib\\site-packages\\numpy\\core\\include -IC:\Apps\Anaconda3\lib\site-packages\numpy\core\include -IC:\Apps\Anaco
nda3\include -IC:\Apps\Anaconda3\include -I"C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\Include" -I"C:\Apps\Micros
oft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\Include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\share
d" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" -I"
C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" /Tcstatsmodels/tsa/statespace/_statespace.c /Fobuild\temp.win-amd64-3.5\Relea
se\statsmodels/tsa/statespace/_statespace.obj
C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:l
ibucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\\Apps\\Anaconda3\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:C:\Ap
ps\Anaconda3\libs /LIBPATH:C:\Apps\Anaconda3\PCbuild\amd64 /LIBPATH:"C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\L
ib\x64" /LIBPATH:"C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\Lib\x64" /LIBPATH:"C:\Program Files (x86)\Win
dows Kits\10\lib\10.0.15063.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 /LIBPATH:"C:\Program Files (x86)\Windows Kits\10
\lib\10.0.15063.0\ucrt\x64" npymath.lib /EXPORT:PyInit__statespace build\temp.win-amd64-3.5\Release\statsmodels/tsa/statespace/_statespace.obj
/OUT:build\lib.win-amd64-3.5\statsmodels\tsa\statespace\_statespace.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\statsmodels/tsa
/statespace\_statespace.cp35-win_amd64.lib
fatal error C1047: The object or library file 'C:\\Apps\\Anaconda3\\lib\\site-packages\\numpy\\core\\lib\npymath.lib' was created with an older
 compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed
error: Command "C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG
 /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\\Apps\\Anaconda3\\lib\\site-packages\\numpy\\core\\li
b /LIBPATH:C:\Apps\Anaconda3\libs /LIBPATH:C:\Apps\Anaconda3\PCbuild\amd64 /LIBPATH:"C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MS
VC\14.11.25503\Lib\x64" /LIBPATH:"C:\Apps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\Lib\x64" /LIBPATH:"C:\Program
 Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64" /LIBPATH:C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319 /LIBPATH:"C:\Program Files (x86)
\Windows Kits\10\lib\10.0.15063.0\ucrt\x64" npymath.lib /EXPORT:PyInit__statespace build\temp.win-amd64-3.5\Release\statsmodels/tsa/statespace/
_statespace.obj /OUT:build\lib.win-amd64-3.5\statsmodels\tsa\statespace\_statespace.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release
\statsmodels/tsa/statespace\_statespace.cp35-win_amd64.lib" failed with exit status 1257

```

**Comment by bashtage** [comment] 2017-10-10 14:27
You should try updating your numpy -- `conda update numpy`.  This is likely a conda issue.

**Comment by Kojoley** [comment] 2017-10-15 22:01
It is an distutils problem on Python 3.6.3 https://bugs.python.org/issue31340

**Comment by JimVaranelli** [comment] 2018-06-04 14:40
Has there been a resolution here? I cannot get past this build error. I tried the workaround below which did not solve the problem. I am using VS2017 with Anaconda 5.0.0 / python 3.6.2. I have tried both 8.1 and 10 SDKs with no luck.

vcvarsall.bat x86_amd64
set DISTUTILS_USE_SDK=1
python setup.py install

**Comment by bashtage** [comment] 2018-06-04 15:23
Why not install from conda, which has the latest statsmodels?

As for building, you don't need the SDK.  You can use https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017 .  Also, is your VS 2017 up to date?

Then you don't need to run any environmental variables since distutils will find the correct paths.

**Comment by JimVaranelli** [comment] 2018-06-04 16:13
Yes this is for enhancement testing (for both sm release and internal use) so being able to build is required. I updated my VS2017 install to the latest release. I already have the buildtools installed and in actuality the vsvarsall didn't do anything as I already had these set correctly in my own envars, I didn't see a good explanation as to what exactly the DISTUTILS_USE_SDK is operating on. My current thinking is to just do it on Linux but ultimately Windows needs to be supported as well so I will need to solve this sooner or later. Thanks.

**Comment by Kojoley** [comment] 2018-06-04 16:22
@JimVaranelli it seems that you did not understand the problem. You cannot link to static libraries built by VS2015 with the VS2017 linker. I suspect you were calling `vcvarsall.bat` from VS2017 but not from SDK 8.1.

**Comment by Kojoley** [comment] 2018-06-04 16:28
When you called `vcvarsall.bat` where it was locating and what version `cl.exe` was reporting?

**Comment by josef-pkt** [comment] 2018-06-04 16:28
I got the same error and haven't worked around it yet on my own computer

My interpretation is that building binary extensions with VS2017 is not compatible with numpy that is build with VS2015.
Gohlke mentioned the linker problems in the python bug report.
I didn't see any obvious way to change the setting for VS2017 to be compatible with VS2015 (given that I have very little experience in this.)

**Comment by Kojoley** [comment] 2018-06-04 16:34
> My interpretation is that building binary extensions with VS2017 is not compatible with numpy that is build with VS2015.

This is partly true. AFAIK ABI in VS2017 did not change, and you can safely mix VS2015 and VS2017 binaries (that's why distutils allowed to build with VS2017), but their static library format is something other and VS2017 linker rejects to link to static libraries of VS2015 version.

**Comment by josef-pkt** [comment] 2018-06-04 16:36
@Kojoley  So, is there an option to use VS2017 with numpy compiled with VS2015, or do we need to have VS2015 installed if we don't want to change the numpy build?

**Comment by JimVaranelli** [comment] 2018-06-04 16:36
The vcvarsall is from the VS2017 which I used for SDK 10. When I tried SDK 8.1 I manually updated my envars to the 8.1 includes/libs/dlls.

I've spent a couple days trying to get past this but I think I will need to go to Linux. 

Is numpy the only problem package? I can certainly build numpy with VS2017 but my working assumption is that this issue will require multiple package recompilations?

Thanks again for the input.

**Comment by josef-pkt** [comment] 2018-06-04 17:13
> Is numpy the only problem package?

From the statsmodels side most likely also scipy. We link to the underlying BLAS/LAPACK through scipy.

But the problem if a specific numpy static binary/linker version is required, is that most likely pandas and other packages like scikit-learn also will need to be compiled in a compatible way.

**Comment by Kojoley** [comment] 2018-06-04 17:16
> @Kojoley So, is there an option to use VS2017 with numpy compiled with VS2015, or do we need to have VS2015 installed if we don't want to change the numpy build?

If numpy is static library - only by linking with VS2015 linker. So it is easier for you to build numpy with VS2017.

> The vcvarsall is from the VS2017 which I used for SDK 10. When I tried SDK 8.1 I manually updated my envars to the 8.1 includes/libs/dlls.

Did you set both `DISTUTILS_USE_SDK` and `MSSdk`?

**Comment by JimVaranelli** [comment] 2018-06-04 17:23
I am downloading VS2015 now. If it works I will update the thread.

**Comment by bashtage** [comment] 2018-06-04 19:19
VS2015 isn't needed to build/compile statsmodels on the latest Anaconda/NumPy (conda update --all).  I just now successfully compiled it on a system that only has VS2017.  


Maybe if you have both 2015 and 2017 (or SDKs that are built with these) it is finding the wrong library when attempting to link. 

You should see lines like this:

```
:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Istatsmodels/src -Ic:\\Anaconda\\lib\\site-packages\\numpy\\core\\include -Ic:\Anaconda\lib\site-packages\numpy\core\include -Ic:\Anaconda\include -Ic:\Anaconda\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcstatsmodels/tsa/statespace/_smoothers/_univariate.c /Fobuild\temp.win-amd64-3.6\Release\statsmodels/tsa/statespace/_smoothers/_univariate.obj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\\Anaconda\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:c:\Anaconda\libs /LIBPATH:c:\Anaconda\PCbuild\amd64 /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\lib\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" npymath.lib /EXPORT:PyInit__univariate build\temp.win-amd64-3.6\Release\statsmodels/tsa/statespace/_smoothers/_univariate.obj /OUT:c:\git\statsmodels\statsmodels\tsa\statespace\_smoothers\_univariate.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\statsmodels/tsa/statespace/_smoothers\_univariate.cp36-win_amd64.lib
```

when compiling.  If you have other paths this might explain your issues.

**Comment by cgohlke** [comment] 2018-06-04 22:56
This is https://github.com/numpy/numpy/issues/9958 and it was fixed in numpy 1.14

**Comment by JimVaranelli** [comment] 2018-06-05 12:59
Thanks again for all the input. I eventually got a clean build after downloading VS2015. That was definitely not my preferred solution but I still couldn't get a clean build with VS2017 even after all of the above suggestions. I just saw cgohlke's comment regarding numpy 1.14 I am going to update the Anaconda numpy package and hopefully that will solve the VS2017 build issue.

**Comment by JimVaranelli** [comment] 2018-06-05 20:12
I can confirm that updating numpy to 1.14.3 has fixed the VS2017 build issue described in the original post. Thanks again.

**Closed** 2019-05-03 11:36 UTC
