### ISSUE TITLE
Some tests fail on aarch64 with 0.12.2

### ISSUE THREAD

**Issue by ggardet** [statsmodels/statsmodels#7866] opened 2021-11-08 14:07 UTC
#### Describe the bug
4 tests fail on aarch64:
```
[  718s] =========================== short test summary info ============================
[  718s] FAILED ../../usr/lib64/python3.9/site-packages/statsmodels/base/tests/test_penalized.py::TestPenalizedPoissonOraclePenalized2::test_params_table
[  718s] FAILED ../../usr/lib64/python3.9/site-packages/statsmodels/base/tests/test_penalized.py::TestPenalizedPoissonOraclePenalized2HC::test_params_table
[  718s] FAILED ../../usr/lib64/python3.9/site-packages/statsmodels/base/tests/test_penalized.py::TestPenalizedPoissonOraclePenalized2HC::test_cov_type
[  718s] FAILED ../../usr/lib64/python3.9/site-packages/statsmodels/discrete/tests/test_count_model.py::TestZeroInflatedModel_probit::test_fit_regularized
[  718s] = 4 failed, 14920 passed, 291 skipped, 139 xfailed, 947 warnings in 661.89s (0:11:01) =
```
Details:
```
[  718s] =================================== FAILURES ===================================
[  718s] ____________ TestPenalizedPoissonOraclePenalized2.test_params_table ____________
[  718s] [gw1] linux -- Python 3.9.7 /usr/bin/python3.9
[  718s] 
[  718s] self = <statsmodels.base.tests.test_penalized.TestPenalizedPoissonOraclePenalized2 object at 0xffff7e3abc70>
[  718s] 
[  718s]     def test_params_table(self):
[  718s]         res1 = self.res1
[  718s]         res2 = self.res2
[  718s] >       assert_equal((res1.params != 0).sum(), self.k_params)
[  718s] E       AssertionError: 
[  718s] E       Items are not equal:
[  718s] E        ACTUAL: 3
[  718s] E        DESIRED: 4
[  718s] 
[  718s] /usr/lib64/python3.9/site-packages/statsmodels/base/tests/test_penalized.py:79: AssertionError
[  718s] ___________ TestPenalizedPoissonOraclePenalized2HC.test_params_table ___________
[  718s] [gw3] linux -- Python 3.9.7 /usr/bin/python3.9
[  718s] 
[  718s] self = <statsmodels.base.tests.test_penalized.TestPenalizedPoissonOraclePenalized2HC object at 0xffff96ee5070>
[  718s] 
[  718s]     def test_params_table(self):
[  718s]         res1 = self.res1
[  718s]         res2 = self.res2
[  718s] >       assert_equal((res1.params != 0).sum(), self.k_params)
[  718s] E       AssertionError: 
[  718s] E       Items are not equal:
[  718s] E        ACTUAL: 3
[  718s] E        DESIRED: 4
[  718s] 
[  718s] /usr/lib64/python3.9/site-packages/statsmodels/base/tests/test_penalized.py:79: AssertionError
[  718s] _____________ TestPenalizedPoissonOraclePenalized2HC.test_cov_type _____________
[  718s] [gw3] linux -- Python 3.9.7 /usr/bin/python3.9
[  718s] 
[  718s] self = <statsmodels.base.tests.test_penalized.TestPenalizedPoissonOraclePenalized2HC object at 0xffff96dc57c0>
[  718s] 
[  718s]     def test_cov_type(self):
[  718s]         res1 = self.res1
[  718s]         res2 = self.res2
[  718s]     
[  718s]         assert_equal(self.res1.cov_type, 'HC0')
[  718s]         assert_equal(self.res1.results_constrained.cov_type, 'HC0')
[  718s]         cov_kwds = {'description': 'Standard Errors are heteroscedasticity '
[  718s]                                    'robust (HC0)',
[  718s]                     'adjust_df': False, 'use_t': False, 'scaling_factor': None}
[  718s]         assert_equal(self.res1.cov_kwds, cov_kwds)
[  718s]         assert_equal(self.res1.cov_kwds, self.res1.results_constrained.cov_kwds)
[  718s]     
[  718s]         # numbers are regression test using bfgs
[  718s]         params = np.array([0.96817787574701109, 0.43674374940137434,
[  718s]                            0.33096260487556745, 0.27415680046693747])
[  718s]         bse = np.array([0.028126650444581985, 0.033099984564283147,
[  718s]                         0.033184585514904545, 0.034282504130503301])
[  718s]         assert_allclose(res2.params[:self.k_nonzero], params, atol=1e-5)
[  718s]         assert_allclose(res2.bse[:self.k_nonzero], bse, rtol=5e-6)
[  718s] >       assert_allclose(res1.params[:self.k_nonzero], params, atol=1e-5)
[  718s] E       AssertionError: 
[  718s] E       Not equal to tolerance rtol=1e-07, atol=1e-05
[  718s] E       
[  718s] E       Mismatched elements: 4 / 4 (100%)
[  718s] E       Max absolute difference: 0.2741568
[  718s] E       Max relative difference: 1.
[  718s] E        x: array([0.975819, 0.492188, 0.387237, 0.      ])
[  718s] E        y: array([0.968178, 0.436744, 0.330963, 0.274157])
[  718s] 
[  718s] /usr/lib64/python3.9/site-packages/statsmodels/base/tests/test_penalized.py:384: AssertionError
[  718s] ______________ TestZeroInflatedModel_probit.test_fit_regularized _______________
[  718s] [gw0] linux -- Python 3.9.7 /usr/bin/python3.9
[  718s] 
[  718s] self = <statsmodels.discrete.tests.test_count_model.TestZeroInflatedModel_probit object at 0xffff90341130>
[  718s] 
[  718s]     @pytest.mark.skipif(PLATFORM_LINUX32, reason="Fails on 32-bit Linux")
[  718s]     def test_fit_regularized(self):
[  718s] >       super().test_fit_regularized()
[  718s] 
[  718s] /usr/lib64/python3.9/site-packages/statsmodels/discrete/tests/test_count_model.py:107: 
[  718s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  718s] 
[  718s] self = <statsmodels.discrete.tests.test_count_model.TestZeroInflatedModel_probit object at 0xffff90341130>
[  718s] 
[  718s]     def test_fit_regularized(self):
[  718s]         model = self.res1.model
[  718s]     
[  718s]         alpha = np.ones(len(self.res1.params))
[  718s]         alpha[-2:] = 0
[  718s]         res_reg = model.fit_regularized(alpha=alpha*0.01, disp=0, maxiter=500)
[  718s]     
[  718s] >       assert_allclose(res_reg.params[2:], self.res1.params[2:],
[  718s]             atol=5e-2, rtol=5e-2)
[  718s] E       AssertionError: 
[  718s] E       Not equal to tolerance rtol=0.05, atol=0.05
[  718s] E       
[  718s] E       Mismatched elements: 1 / 4 (25%)
[  718s] E       Max absolute difference: 0.08217881
[  718s] E       Max relative difference: 1.
[  718s] E        x: array([ 0.      ,  0.      , -0.026795,  1.482368])
[  718s] E        y: array([-0.082179,  0.008567, -0.026795,  1.482369])
[  718s] 
[  718s] /usr/lib64/python3.9/site-packages/statsmodels/discrete/tests/test_count_model.py:45: AssertionError
```

#### Code Sample, a copy-pastable example if possible
N/A

#### Expected Output

Tests should pass on aarch64.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

This is with statsmodels 0.12.2 on openSUSE Tumbleweed.

**Comment by josef-pkt** [comment] 2021-11-08 18:02
The zeroinflated test can be skipped, fit_regularized for ZI model is inherited, and I never checked how robust optimization is in those cases. Starting values for optimization are not very good yet. 

TestPenalizedPoissonOraclePenalized2 and HC test failures

When I run TestPenalizedPoissonOraclePenalized2 test locally, then I get an convergence warning. But it's in a preliminary estimate for `res1`, the final optimization converges.

Digging into this, optimization and convergence looks fragile and requires good start_params to make this robust.
My first try to change the PenalizedMixin.fit code with better start_params was not very successful. That requires more work to make the optimization more robust. SCAD is a non-convex penalty and AFAIR can have multiple local optima.

My current fix is to add explicit start_params to the unit test case. That tests that the algorithm is correct, but does not verify convergence problems and good defaults for start_params anymore.

The `trim=False` fit for this example also does not converge reliably. I need to use method="nm" to get start_params for "bfgs".

Related: I get other convergence warnings in base test_penalized that will need to be investigated (but I want to go back to other things for now.)
```
statsmodels/base/tests/test_penalized.py::TestPenalizedGLMBinomCountOracleHC::te
st_params_table
statsmodels/base/tests/test_penalized.py::TestPenalizedGLMBinomCountOracleHC2::t
est_params_table
  ...\statsmodels\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization faile
d to converge. Check mle_retvals
    warnings.warn("Maximum Likelihood optimization failed to "

```

---

for the record: my first draft
I looked a bit at it. I don't have a candidate for the cause of the problem.
Initially I thought convergence failures, but there are many similar unit tests that pass.
The only substantial difference in the failing unit tests is `trim=True`.
The coefficients shouldn't be close to the trim threshold, so I don't think it's a small numerical noise problem.
If trim is True, then the code computes a `_fit_zeros` estimate and result is computed. That's a difficult piece of code, that I don't want to get into now.
TODO: No start_params are given to fit_zeros. Providing those from the penalized estimate will improve convergence of the fit_zero estimate. 

This is pretty old code and, AFAIK, hasn't been changed in some time.
Some things for penalized were changed in 2019 for statsmodels version 0.10

**Comment by josef-pkt** [comment] 2021-11-08 19:11
fix for TestPenalizedPoissonOraclePenalized2 unit test is in #7868

**Comment by bashtage** [comment] 2021-11-09 10:05
What OpenBLAS does your NumPy use @ggardet ?  We often see a lot of failures in statespace too.

**Comment by ggardet** [comment] 2021-11-09 10:21
> What OpenBLAS does your NumPy use @ggardet ? We often see a lot of failures in statespace too.

NumPy 1.21.2 is built against blas 3.9.0 and statsmodels uses libopenblas_openmp0 0.3.17, pulled by scipy.

**Comment by bashtage** [comment] 2022-01-14 15:14
Can you test the wheels that are available, if you have time?  You can run the test suite using

```python
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
python -c "import statsmodels;statsmodels.test(['--skip-examples'])"
# can add '-n','auto' to the list if you install pytest-xdist and have many cores
```

**Comment by josef-pkt** [comment] 2022-09-26 17:30
looks old and most likely outdated.

closing, reopen if there are still problems

**Closed by josef-pkt** 2022-09-26 17:30 UTC
