### ISSUE TITLE
Result of exponential smoothing  is not consistence with R?

### ISSUE THREAD

**Issue by royqh1979** [statsmodels/statsmodels#6819] opened 2020-06-24 08:44 UTC
#### Describe the bug

The result of SimpleExponentialSmoothing() is not consistence with R's HoltWinters(beta=F,gamma=F).

It's this a bug? 

#### Code Sample, a copy-pastable example if possible

Statsmodel code:

```python
import pandas as pd
from statsmodels.tsa.holtwinters import SimpleExpSmoothing

Motor = pd.read_csv("data/motororg.dat")
comp = Motor["complaints"]
comp.index = pd.date_range(start="1996",periods=len(comp),freq="M")

model = SimpleExpSmoothing(comp)
model.fit()
print(model.params)
```

R code:
```R
Motor.dat <- read.table("e:\\tmp\\timeseries\\motororg.dat",header=T)
attach(Motor.dat)
Comp.ts <- ts(complaints, start = c(1996,1), freq=12)
Comp.hw1 <- HoltWinters(Comp.ts, beta = F, gamma = F)
Comp.hw1
```

The result of statsmodels is alpha(smoothing-level) = 0.08885990070014146
The result of R is alpha = 0.1429622

Contents of the motororg.dat is as below:
```
complaints
27
34
31
24
18
19
17
12
26
14
18
33
31
31
19
17
10
25
26
18
18
10
4
20
28
21
18
23
19
16
10
24
11
11
13
27
18
20
21
6
9
29
12
19
14
19
16
23
```

**Comment by ChadFulton** [comment] 2020-06-28 04:04
This is probably not a bug - parameters are selected by numerically minimizing the sum of squared errors, and the optimal parameters chosen depend on the starting parameters, the specific numerical optimizer being used, and also the space of allowable parameters.  These can differ between packages.

**Comment by ChadFulton** [comment] 2020-06-28 04:04
I'm going to close this since it doesn't seem like a bug to me.  Feel free to reopen if you have come across something else that makes you think it's a bug.

**Closed by ChadFulton** 2020-06-28 04:04 UTC
