### ISSUE TITLE
Bug In contingency_tables (2x2) Summary

### ISSUE THREAD

**Issue by kfeldman** [statsmodels/statsmodels#4117] opened 2017-11-09 19:31 UTC
The risk ratio CI is incorrectly displayed in the summary function. As you can see in the source below the CI from the Log Odds Ratio is used. 

http://www.statsmodels.org/dev/_modules/statsmodels/stats/contingency_tables.html#Table2x2.summary

[fmt(x) for x in [self.riskratio, "", lcb2, ucb2, self.riskratio_pvalue()]],

**Specifically,** 
lcb2, ucb2 = self.log_oddsratio_confint(alpha, method)
lcb3, ucb3 = self.riskratio_confint(alpha, method)
lcb2/ucb2 are used in both, when lcb3/ucb3 should be used for the risk ratio

**Comment by josef-pkt** [comment] 2017-11-09 19:36
I think this is duplicate of #3822 which should be fixed in master

(unfortunately the documentation hasn't been updated in a while)

**Comment by tqa236** [comment] 2020-06-11 12:01
@josef-pkt Is this issue fixed or is there anything left to do? The issue you mentioned is already closed.

**Comment by josef-pkt** [comment] 2020-06-11 12:59
Thanks for finding

Yes, it's all fixed AFAICS

**Closed by josef-pkt** 2020-06-11 12:59 UTC
