### ISSUE TITLE
Incorrect response to changes in Integration (d)  ARIMA parameter

### ISSUE THREAD

**Issue by renga17** [statsmodels/statsmodels#7393] opened 2021-03-30 08:25 UTC
statsmodels version 0.12.2.
api-statsmodels.tsa.arima.model.ARIMA
Environment:
1. Windows 10
2. OLE7

We have compared the output of ARIMA api with respect the integration parameter changes with the Deprecated since version 0.12 api statsmodels.tsa.arima_model.ARIMA and other R api as the response against changes in integration parameter seems to be incorrect.

The test case is based on timeseries characterized by order d=1. ARIMA model expect and prediction done for 10 periods in the future.
Here are the observations.
1. For order (0,1,0), the output is comparable to order (0,0,0).
2. For order (0,1,0), the output is the last value of the series continued.
3. For order (0,0,0), the output is average value projected in the future. (this is not an issue).

Example code with data
[https://github.com/renga17/misc](url)

**Comment by bashtage** [comment] 2021-03-30 08:54
What is `(0.1.0)`?  Orders are tuples.  

Can you provide a full example showing what you think is the problem?

These are all expected from what I can tell.  You need to set `trend="t"`  when using `(0,1,0)` to include something like a constant.

**Comment by bashtage** [comment] 2021-04-30 12:15
This is by design and working correctly from what can be seen here, so closing.

**Closed by bashtage** 2021-04-30 12:15 UTC
