### ISSUE TITLE
Please provide a full example about how to use `exog` .

### ISSUE THREAD

**Issue by eromoe** [statsmodels/statsmodels#4795] opened 2018-07-13 09:38 UTC
Hello, 

I want to predict a product sale count in a supermarket in future 3 days.
I collect the last 6 month sale data.  Including  product price, discount rate, weather, weekday_info, is_this_day_holiday, is_product_stockout_in_X_hour ....

After some researching, I know AMMA only need y (sale count) in every day.  And I found there is a parameter `exog` for addistion data.

## 1. But it is unclear what is the proper data format of exog.

Data source:
```
>>> y.hundred_count_sale.loc["2018-06":"2018-06"].shape
(30,)
>>> X.loc["2018-06":"2018-06"].shape
(30, 43)
```

Trainning code:
```
model = ARMA(y.hundred_count_sale.loc["2018-06":"2018-06"], order=(2, 2), exog=X.loc["2018-06":"2018-06"])
result_arma = model.fit()
```

got error :  
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-106-9cfc06e66bea> in <module>()
      1 model = ARMA(y.hundred_count_sale.loc["2018-06":"2018-06"], order=(2, 2), exog=X.loc["2018-06":"2018-06"])
----> 2 result_arma = model.fit()

C:\Anaconda3\lib\site-packages\statsmodels\tsa\arima_model.py in fit(self, start_params, trend, method, transparams, solver, maxiter, full_output, disp, callback, start_ar_lags, **kwargs)
    919 
    920         # check again now that we know the trend
--> 921         _check_estimable(len(endog), k_ar + k_ma + k_exog + k_trend)
    922 
    923         self.k_trend = k_trend

C:\Anaconda3\lib\site-packages\statsmodels\tsa\arima_model.py in _check_estimable(nobs, n_params)
    421 def _check_estimable(nobs, n_params):
    422     if nobs <= n_params:
--> 423         raise ValueError("Insufficient degrees of freedom to estimate")
    424 
    425 

ValueError: Insufficient degrees of freedom to estimate
```

------------------------------

## 2. Another problem is diff. 

If I do :

```
ts_diff = y.hundred_count_sale.loc["2018-06":"2018-06"].diff(7).dropna()
```

`.diff(7)` would remove the first 7 elements in y .  Do I need diff the exog `X` ? or simply pass `X[7:]` ?

**Comment by ChadFulton** [comment] 2018-07-13 23:45
> ValueError: Insufficient degrees of freedom to estimate

You correctly put the `exog` data into the model, but you have 43 predictors and only 30 datapoints, so there is not enough data to estimate all of the parameters in your model. If you don't have a longer time sample, then you will need to use fewer exogenous variables.

> 2. Another problem is diff.
> If I do :
> `ts_diff = y.hundred_count_sale.loc["2018-06":"2018-06"].diff(7).dropna()`
> `.diff(7)` would remove the first 7 elements in y . Do I need diff the exog `X` ? or simply pass `X[7:]`?

That depends on the model you're trying to fit. Are you hypothesizing that the differenced y variable is related to the values in `X`? Or are you hypothesizing that the differenced y variable is related to the differenced X variable?

For example, suppose that I was modeling inflation as the `y` variable and the unemployment rate as the `x` variable. Inflation is the change in prices. Then it might be that I think that inflation depends on the level of the unemployment rate (so I wouldn't diff `x`), or it might be that I think that inflation depends on the change in the unemployment rate (so I would diff `x`). It just depends the model you want.

**Comment by ChadFulton** [comment] 2018-07-14 00:33
I'm going to close this issue since I don't think it's a bug, but feel free to reply if something is still unclear.

**Closed by ChadFulton** 2018-07-14 00:33 UTC

**Comment by eromoe** [comment] 2018-07-16 01:57
Thank you for detail explanation.

But I still can't understand this
> you have 43 predictors and only 30 datapoints, so there is not enough data to estimate all of the parameters in your model

Because If I use linear model, it is fine to fit with 
```
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X.loc["2018-06":"2018-06"], y.order_count_sale.loc["2018-06":"2018-06"])
# without error
```

**Comment by ChadFulton** [comment] 2018-07-16 02:44
They are using `scipy.linalg.lstsq`, which does return an answer, however, there are still not enough data points to uniquely identify all of the parameters. `lstsq` imposes a particular normalization so that it can return some numbers to you, but that doesn't mean that the answer will be good or useful. In particular, you'll find that you are likely to dramatically overfit your training data.

To read more about this, you can search google for something like "regression with more variables than observations"

**Comment by eromoe** [comment] 2018-07-16 03:06
I understand now , it is very kind of you , thank you very much!
