### ISSUE TITLE
ExponentialSmoothing error: __init__() got multiple values for argument 'trend'

### ISSUE THREAD

**Issue by akpandya** [statsmodels/statsmodels#7114] opened 2020-10-23 12:25 UTC
Hello,

I am new to 

> Statsmodels (0.12.0)

trying to fit an Exponential Smoothing model to a ts data,  passing the below command in Jupyter NB:

```
hw = ExponentialSmoothing(data0,
                          trend='mul',
                          damped_trend=False,
                          seasonal='add',
                          seasonal_periods=12,
                          initialization_method="estimated",
                          use_boxcox=False).fit()

```
however, getting this error:
`TypeError: __init__() got multiple values for argument 'trend'`

Can anyone please help me resolve this? 
![image](https://user-images.githubusercontent.com/15137337/97002807-219a5580-1558-11eb-8184-6f36a7d84701.png)

**Comment by bashtage** [comment] 2020-10-23 13:15
Can you edit to include a copy-and-paste-able example the reproduces?

**Comment by ChadFulton** [comment] 2020-10-23 21:21
I can't replicate this problem, but it looks to me like it's probably an issue with a typo when you ran the cell.

Notice that in your screenshot, the command ends at line 9, but in the exception it ends at line 10. I'm guessing the command that produced the exception was something like

```python
hw = ExponentialSmoothing(data0,
                          typo_argument,  # <- this shouldn't be here
                          trend='mul',
                          damped_trend=False,
                          seasonal='add',
                          seasonal_periods=12,
                          initialization_method="estimated",
                          use_boxcox=False).fit()
```

**Comment by ChadFulton** [comment] 2020-10-24 03:37
Closing since it seems like there's no action required here, but do feel free to follow up.

**Closed by ChadFulton** 2020-10-24 03:37 UTC
Labels: comp-tsa, type-invalid
