### ISSUE TITLE
ImportError of module from 'statsmodels.compat.pandas' 

### ISSUE THREAD

**Issue by huytofu** [statsmodels/statsmodels#6484] opened 2020-01-31 03:54 UTC
#### Describe the bug

Failed to import due to compatibility issue with pandas

I am currently using the statsmodels version from the master branch @  git+https://github.com/statsmodels/statsmodels

For Pandas: any version starting from 0.21 to 1.0.0 produces this error
Please help!

#### Code Sample, a copy-pastable example if possible

```python
ImportError                               Traceback (most recent call last)
<ipython-input-220-23b3b387c9ee> in <module>
----> 1 import statsmodels.api as sm
      2 
      3 X = sm.add_constant(final_df_attributes_coded)
      4 estimator = sm.OLS(final_df_label_fact, X)
      5 estimator.fit()

~/anaconda3/lib/python3.7/site-packages/statsmodels/api.py in <module>
     18 from . import robust
     19 from .robust.robust_linear_model import RLM
---> 20 from .discrete.discrete_model import (Poisson, Logit, Probit,
     21                                       MNLogit, NegativeBinomial,
     22                                       GeneralizedPoisson,

~/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py in <module>
     26 from scipy.stats import nbinom
     27 
---> 28 from statsmodels.compat.pandas import Appender
     29 
     30 import statsmodels.tools.tools as tools

ImportError: cannot import name 'Appender' from 'statsmodels.compat.pandas' (/Users/tophunghuy/anaconda3/lib/python3.7/site-packages/statsmodels/compat/pandas.py)
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

Expected to sucessfully import statsmodels

#### Output of ``import statsmodels.api as sm;``

Failed to import due to compatibility issue with pandas

<details>

</details>

**Comment by bashtage** [comment] 2020-01-31 07:21
Your pandas is to old. Minimum pandas is 0.23.

**Comment by bashtage** [comment] 2020-01-31 08:06
Closing since nothing to do for us.

**Closed by bashtage** 2020-01-31 08:06 UTC

**Comment by huytofu** [comment] 2020-01-31 08:21
Hi I tried with pandas 0.24 and even 1.0.0
Still see the error

**Comment by huytofu** [comment] 2020-01-31 08:22
A temp fix I tried was to change all instances of
```
from statsmodels.compat.pandas import Appender
```
to
```
from pandas.util._decorators import Appender
```
inside statsmodels package

**Comment by bashtage** [comment] 2020-01-31 08:23
Why not pandas 0.25.3?

**Comment by huytofu** [comment] 2020-01-31 08:26
Haven't tried every single release of pandas yet. A bit cumbersome

**Comment by bashtage** [comment] 2020-01-31 11:07
0.24 works as well and is tested:

https://travis-ci.org/statsmodels/statsmodels/jobs/643700991

I think something must be wrong with your setup.

**Comment by dfive** [comment] 2020-03-08 20:04
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-42-eed08553c17f> in <module>
----> 1 import pmdarima as pm
      2 
      3 model1 = pm.auto_arima(onion_prices_data[['price']])
      4 
      5 print(model1.summary())

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/__init__.py in <module>
     27 
     28     # Stuff we want at top-level
---> 29     from .arima import auto_arima, ARIMA, AutoARIMA
     30     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf
     31 

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/arima/__init__.py in <module>
      4 
      5 from .approx import *
----> 6 from .arima import *
      7 from .auto import *
      8 from .utils import *

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/arima/arima.py in <module>
     15 from statsmodels.tsa.arima_model import ARIMA as _ARIMA
     16 from statsmodels.tsa.base.tsa_model import TimeSeriesModelResults
---> 17 from statsmodels import api as sm
     18 
     19 from scipy.stats import gaussian_kde, norm

/usr/local/anaconda3/lib/python3.7/site-packages/statsmodels/api.py in <module>
      9 from . import regression
     10 from .regression.linear_model import OLS, GLS, WLS, GLSAR
---> 11 from .regression.recursive_ls import RecursiveLS
     12 from .regression.quantile_regression import QuantReg
     13 from .regression.mixed_linear_model import MixedLM

/usr/local/anaconda3/lib/python3.7/site-packages/statsmodels/regression/recursive_ls.py in <module>
      9 import pandas as pd
     10 
---> 11 from statsmodels.compat.pandas import Appender
     12 
     13 from statsmodels.tools.data import _is_using_pandas

ImportError: cannot import name 'Appender' from 'statsmodels.compat.pandas' (/usr/local/anaconda3/lib/python3.7/site-packages/statsmodels/compat/pandas.py)

**Comment by mtchem** [comment] 2020-03-09 20:24
I am also having issues with statsmodels compatability with Pandas.  I have tried the suggested Pandas version 0.24, and all versions of Pandas from 0.23.0 - 1.01 and the most recent statsmodels verion 0.11.1

`~/anaconda3/envs/python3/lib/python3.6/site-packages/statsmodels/api.py in <module>
     18 from . import robust
     19 from .robust.robust_linear_model import RLM
---> 20 from .discrete.discrete_model import (Poisson, Logit, Probit,
     21                                       MNLogit, NegativeBinomial,
     22                                       GeneralizedPoisson,

~/anaconda3/envs/python3/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py in <module>
     26 from scipy.stats import nbinom
     27 
---> 28 from statsmodels.compat.pandas import Appender
     29 
     30 import statsmodels.tools.tools as tools

ImportError: cannot import name 'Appender' `

**Comment by bashtage** [comment] 2020-03-09 22:18
What happens if you look in statsmodels/compat/pandas.py?  Do you see Appender?  I suspect your statsmodel install is broken.  You could also try `pip uninstall statsmodels && pip install statsmodels --pgrade`

**Comment by justprophet** [comment] 2020-03-25 11:14
I have the same issue. I re installed the statsmodel. Still the same error. 
"Cannot import Appender"
Did you get a fix @dfive @mtchem

**Comment by bashtage** [comment] 2020-03-25 11:22
You likely have an unsupported (too new) version of pandas.

**Comment by bashtage** [comment] 2020-03-25 11:24
I have sm 0.11.0 and pandas 1.0.3 which work together.

**Comment by NiveshTayal** [comment] 2020-05-14 07:50
Getting below error while installing pmdarima

Python Code:- import pmdarima as pm

Issue:- ImportError: cannot import name 'assert_equal' from 'statsmodels.compat.pandas' (/databricks/python/lib/python3.7/site-packages/statsmodels/compat/pandas.py)

Having pandas == 1.0.3 and statsmodels==0.11.1

Please help!!!

**Comment by jingyuzheng** [comment] 2020-05-14 19:10
> Getting below error while installing pmdarima
> 
> Python Code:- import pmdarima as pm
> 
> Issue:- ImportError: cannot import name 'assert_equal' from 'statsmodels.compat.pandas' (/databricks/python/lib/python3.7/site-packages/statsmodels/compat/pandas.py)
> 
> Having pandas == 1.0.3 and statsmodels==0.11.1
> 
> Please help!!!

same issue here! anyone have solution?

**Comment by amirgamil** [comment] 2020-05-26 07:26
@NiveshTayal @jingyuzheng make sure to check that your editor/environment is using those updated versions - i.e. in your .ipynb check if pd.__version__ shows 1.0.3 and if it doesn't restart your environment. But with your versions of pandas and statsmodels, it should work

**Comment by shikhnu** [comment] 2020-05-29 16:54
Getting below error while installing pmdarima

Python Code:- import pmdarima as pm

Issue:- ImportError: cannot import name 'assert_equal' from 'statsmodels.compat.pandas' 

Having pandas == 1.0.3 and statsmodels==0.11.1

Please help!!!

**Comment by EvanHong99** [comment] 2022-04-05 04:34
> What happens if you look in statsmodels/compat/pandas.py? Do you see Appender? I suspect your statsmodel install is broken. You could also try `pip uninstall statsmodels && pip install statsmodels --pgrade`

It works

**Comment by firas-jolha** [comment] 2022-07-05 20:55
Any stable solution for this issue?

**Comment by bashtage** [comment] 2022-07-13 19:29
@firas-jolha do you know how you got this issue to  appear?
