### ISSUE TITLE
Wrong Forecasts for AR(p) model with exogenous variables

### ISSUE THREAD

**Issue by NajdorfB** [statsmodels/statsmodels#7099] opened 2020-10-14 20:03 UTC
**Describe the bug:**
statsmodels.tsa.arima_model.ARIMAResults.forecast() produces a wrong forecast if an AR(p) model with exogenous variables is used. Tested with AR(1) and AR(10), it produces the right forecast if exogenous variables are not used.

**Code Sample:**
```
import numpy as np
import statsmodels.api as sm
import pandas as pd

np.random.seed(12345)

# creating the error term and the exogenous variable
exogenous_variable = []
innovation = []
for _ in range(250):
    e = np.random.uniform(low=-10, high=10, size=1)
    exogenous_variable.append(e[0])
    i = np.random.standard_normal()
    innovation.append(i)

# calculate x, the end. variable
x = np.zeros(250)
for i in range(0, 250):
    if i == 0:
        x[i] = 0.05 * exogenous_variable[i] + innovation[i]
    else:
        x[i] = 0.5 * x[i-1] + 0.05 * exogenous_variable[i] + innovation[i]

# create dataframe with endo and exo var and split the data for forecasting
df = pd.DataFrame(data=[x, exogenous_variable])
df = df.transpose()
train = df.iloc[0:240]
test = df.iloc[240:]

# forecasting with exogenous variable
model = sm.tsa.arima.ARIMA(train.iloc[:, 0], exog=train.iloc[:, 1], order=(1, 0, 0), trend="n")
result = model.fit()
forecast = result.forecast(steps=1, exog=test.iloc[0, 1])
# Y(t) = AR(1) parameter * y(t-1) + beta * x(t)
mforecast = result.arparams * train.iloc[-1, 0] + result.params.iloc[0] * test.iloc[0, 1]

# forecasting without exogenous variables (this works)
model = sm.tsa.arima.ARIMA(train.iloc[:, 0], order=(1, 0, 0), trend="n")
result = model.fit()
forecast_we = result.forecast(steps=1)
# Y(t) = AR(1) parameter * y(t-1)
mforecast_we = (result.arparams * train.iloc[-1, 0])

```
**Expected Output**:
approx. 0.49167332 (calculated by hand, the python manual calculation gives the same)
received forecast 0.46541322479602343

**Comment by ChadFulton** [comment] 2020-10-15 00:57
Our model is of the form "regression with ARIMA errors", so `exog` is modeling the mean of the process, not the intercept.

- You are computing the forecast according to y_hat(t) = phi y(t-1) + beta * x(t)
- But the model is computing (y_hat(t) - beta * x(t)) = phi (y(t-1) - beta * x(t-1))

The following will work to manually compute the forecast:

```
mforecast = result.arparams * (train.iloc[-1, 0] - result.params.iloc[0] * train.iloc[-1, 1]) + result.params.iloc[0] * test.iloc[0, 1]
```

**Comment by ChadFulton** [comment] 2020-10-15 00:58
Closing since there is nothing to do here, but feel free to follow up.

**Closed by ChadFulton** 2020-10-15 00:58 UTC
Labels: comp-tsa-statespace, type-invalid

**Comment by NajdorfB** [comment] 2020-10-15 07:13
> 
> 
> Our model is of the form "regression with ARIMA errors", so `exog` is modeling the mean of the process, not the intercept.
> 
>     * You are computing the forecast according to y_hat(t) = phi y(t-1) + beta * x(t)
> 
>     * But the model is computing (y_hat(t) - beta * x(t)) = phi (y(t-1) - beta * x(t-1))
> 
> 
> The following will work to manually compute the forecast:
> 
> ```
> mforecast = result.arparams * (train.iloc[-1, 0] - result.params.iloc[0] * train.iloc[-1, 1]) + result.params.iloc[0] * test.iloc[0, 1]
> ```

Thanks for the reply, I feared that the error was on my part, but I was not able to figure out the formula statsmodels uses and my basic formula worked for ma(q) models.
Sorry for the wrong bug report and for the inconvenience,

**Comment by ChadFulton** [comment] 2020-10-15 15:12
No problem, glad we could clear everything up.
