### ISSUE TITLE
"sarimax_model_results.predict" memory consumption

### ISSUE THREAD

**Issue by fgilbert01** [statsmodels/statsmodels#3189] opened 2016-09-06 14:45 UTC
Hello,
I am running the sarimax model using only endogenous data with 8760 time steps. On my windows 10 computer, I see that the predict method consume 2 Gig of memory.
sarimax_model_results.predict (start= 0, end= iend_index, exog= None)

Can you explain why the model has such a big memory consumption and is there a way to decrease it.
Regards
Francois

**Comment by josef-pkt** [comment] 2016-09-06 14:51
Please provide more information:
specification of SARIMAX, i.e. number of lags, season length, ...
Is the large memory consumption only in predict or already in fit?

AFAIK, the statespace uses dense arrays and requires statespace and transition matrix in the dimension of the largest lag. However, that should be at fitting or even init stage. I don't see an inherent reason why predict should take a lot more memory.

(Chad will know better, with more information)

**Comment by fgilbert01** [comment] 2016-09-06 15:05
Hello Joseph,

 

Here are more details about the use of the fit and the predict functions.

 

The fit function takes 390 MB for a year of historical hourly load values.

 

mod = sm.tsa.SARIMAX(endog_hist_load, exog= None ,order=(1,0,0),seasonal_order=(0,1,1,24),trend='c', simple_differencing=False)

sarimax_model_results = mod.fit()

 

When the predict run, the memory consumption increase to 2 GigB. I was also thinking the fit part would be the one to consume the most memory.

 

Francois

**Comment by josef-pkt** [comment] 2016-09-06 15:15
That sounds strange. (however, I don't know the details well enough to guess for a reason).

What happens if you increase `start` in predict? 
e.g. does the memory consumption also increase if start is at least larger than the lags, or if you only predict out of sample (forecast)?

**Comment by josef-pkt** [comment] 2016-09-06 15:21
To check whether there are intermediate results stored for each prediction case:
can you look at the memory consumption as you increase the number of p(one step ahead) periods that are forecast, e.g. increase `end` - `start` by increments of 100?

**Comment by josef-pkt** [comment] 2016-09-06 15:28
about the usage: 
one-step insample predict should be redundant because it should be available already in the `filtered` series, `fittedvalues` (or something like that)

**Comment by fgilbert01** [comment] 2016-09-06 15:37
Joseph,
I am not sure I understand what you want me to test. Can you indicate the parameter change steps in the 2 following functions.
1. mod = sm.tsa.SARIMAX(endog_hist_load, exog= None ,order=(1,0,0),seasonal_order=(0,1,1,24),trend='c', simple_differencing=False)
2. sarimax_model_results.predict(start= 0, end= iend_index, exog= None)

The one thing I know is that memory increases when endog_hist_load array size increases.

**Comment by josef-pkt** [comment] 2016-09-06 15:45
My guess is that predict is designed for single prediction and saves auxiliary results at each step, in contrast to just using the kalman filter for `filtering`.

I'm not sure what your time index is. If it is just integers, then I would try the following

`sarimax_model_results.predict(start= 50, end= iend_index, exog= None)` to check whether there are problems with initialization of the state if start=0 

and 
`sarimax_model_results.predict(start= iend_index - i * 100, end= iend_index, exog= None)` 
for i in range(1, 10) 
to see whether memory increases approximately linearly in the length (how many periods).

**Comment by fgilbert01** [comment] 2016-09-06 15:55
Time index is not only integers.  It is a datetime index. 

Should I proceed with the test you have mentioned below.

**Comment by josef-pkt** [comment] 2016-09-06 15:57
> Should I proceed with the test you have mentioned below.

Yes, please try. Just adjust the predict `start` and `end` indices to whatever you need with your data.

**Comment by ChadFulton** [comment] 2016-09-06 16:59
I can't immediately replicate this memory usage. See the following code. If you like, give this code a try and let me know if you see different results.

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
x = pd.Series(np.random.normal(size=8760), index=pd.date_range('1970-01-01', freq='H', periods=8760))
# As of now, about 78 mb

mod = sm.tsa.SARIMAX(x, order=(1,0,0), seasonal_order=(1,0,0,24), trend='c')
# As of now, still about 78 mb

res = mod.fit()
# As of now, 577 mb

pred = res.predict(start=0, end=8800)
# Now down to about 533 mb (probably some garbage collection happened somewhere here)
```

**Comment by josef-pkt** [comment] 2016-09-06 17:23
@ChadFulton  your example also uses around 530 mb on my Windows 8, python 3.4, with MKL.

**Comment by fgilbert01** [comment] 2016-09-06 17:33
I have send my source code attached to this email:

 

I have a zip file that contains the main file with libraries and ini files. You need to execute load_sim.py that is in the folder LoadSim.

 

Francois

**Comment by fgilbert01** [comment] 2016-09-06 18:53
Hello,
I have used the github interface to send the 7z file that contain the source code. You will need to remove the .zip extension before extracting the results.

[memory_problem_sarimax.7z.zip](https://github.com/statsmodels/statsmodels/files/457537/memory_problem_sarimax.7z.zip)

**Comment by ChadFulton** [comment] 2016-09-06 21:59
Since we can't reproduce, please try the code snippet above and see what results you get.

**Comment by fgilbert01** [comment] 2016-09-07 14:05
I have tried your code snippet and it works well on my computer. I get around 500 Meg RAM consumption. I am using python 2.7 so that could be the difference between your set-up and mind.

Can you confirm you have run the code sample that I have sent and you got a 500 Meg RAM consumption.

**Comment by fgilbert01** [comment] 2016-09-07 14:19
I have tried your code snippet and it works well on my computer. I get around 500 Meg RAM consumption. I am using python 2.7 so that could be the difference between your set-up and mind.

 

Can you confirm you have run the code sample that I have sent and you got a 500 Meg RAM consumption.

**Comment by fgilbert01** [comment] 2016-09-07 14:21
I have tried your code snippet and it works well on my computer. I get around 500 Meg RAM consumption. I am using python 2.7 so that could be the difference between your set-up and mind.

Can you confirm you have run the code sample that I have sent and you got a 500 Meg RAM consumption.

**Comment by ChadFulton** [comment] 2016-09-07 17:32
It would be very helpful if you could construct a minimal example demonstrating the issue in a few lines. Otherwise, the problem is that I do not know when I will have time to go through your project files to see what might be causing an issue.

**Comment by fgilbert01** [comment] 2016-09-08 20:18
Hello,
I have been able to resolve the memory consumption issue and now have a 500 Meg RAM consumption during the SARIMAX fitting and it also run faster. Unfortunately, I do not know what changes made it work as I came back to the original code version. Strangely, it had a side effect where I cannot retrieved anymore the calibration parameters for a subsequent prediction. 
I have the following error message `Invalid dimensions for initial state vector. Requires shape (49,), got (25L,)`
when I execute:
mod = sm.tsa.SARIMAX(load_hist, exog= temperature_hist ,order=(1,0,0),seasonal_order=(0,1,1,24),trend='c', simple_differencing=False)
mod.initialize_known(saved_state, saved_cov)
The content of the saved_state and saved_cov are in the attached files.

[LastCovarianceParameter.dat.txt](https://github.com/statsmodels/statsmodels/files/462578/LastCovarianceParameter.dat.txt)
[LastStateParameter.dat.txt](https://github.com/statsmodels/statsmodels/files/462577/LastStateParameter.dat.txt)

On the original version that was taking 2 Gig of memory, I was not having this problem. The array parameters were good.

**Comment by ChadFulton** [comment] 2016-09-08 20:25
The error you're getting suggests that you are trying to use an initial state and covariance from a different model. Your model has a state vector of length 49, and you are trying to give it an initial state vector of length 25.

**Comment by fgilbert01** [comment] 2016-09-09 14:08
Chad,
Your comment just above gave me the help I need to find the problem. I was fitting a p,d,q 1,1,0 and trying to read the parameter with a 0,1,1 model. PROBLEM SOLVED.
THANKS VERY MUCH

**Comment by fgilbert01** [comment] 2016-09-09 14:21
Chad,
For the initial problem, I had submitted a problem with a seasonal_order=(0,1,1,24) and on your side you tested a seasonal_order=(1,0,0,24). That was the difference in term of memory usage. If you run a 0,1,1,24, you will see that the RAM goes to 1.9 MEG.
PROBLEM SOLVED ANYWAY

**Comment by ChadFulton** [comment] 2016-09-09 23:23
I see, my mistake. For the SARIMAX(1,0,0)x(0,1,1,24) series, I get about 1.7gb. This is not too surprising, since as Josef mentioned, there are a lot of data stored for a Kalman filter iteration and you have 49 state variables with that specification.

One simple thing you can do to reduce memory usage is to use `simple_differencing=True` which will cut down the state vector to 25. That reduces memory consumption to about 500mb in my test.

For more details on memory usage: the predicted_state_cov and filtered_state_cov arrays have dimension (k_states x k_states x nobs). Since you have 49 state variables, each of these arrays hold over 21 million datapoints each. Also, the default behavior is to return the smoothed result set, which includes a number of additional k_states x k_states x nobs arrays.

There are some options to reduce memory usage, but they may not be applicable in your case. There are memory conservation options (see e.g. `KalmanFilter.set_conserve_memory`) but using them eliminates the possibility of prediction or smoothing.

I think that there is probably a solution which would allow you to get what you want with minimal memory usage, but there is nothing built in. (e.g. you could perform model fitting using the more stringent memory conservation features on the entire dataset, and then you could perform filtering up to the date at which you wanted prediction to begin using stringent memory conservation features, and then save the resulting predicted_state and predicted_state_cov objects to use as the initial_state and initial_state_cov objects for a new Kalman filter run that would perform whatever prediction you wanted).  The interface for dealing with memory issues is not very well developed, and could certainly be improved.

It's not high on my personal priority list because ultimately if you want to perform smoothing you have to store all the intermediate data, and I almost always want to do smoothing. That's not to say that memory usage reduction isn't an important use case, but it's not usually my use case.

**Comment by josef-pkt** [comment] 2016-09-28 19:38
(I wrote this two weeks ago, and found it while closing tabs and programs)

@ChadFulton  A few questions based on my superficial knowledge of the model:

Is it possible to do this prediction with just filtering without keeping hold of come of the cov arrays, i.e. like minimal predict versus full get_prediction?

Is it possible to get rid of some of the stored arrays again? And where are those attached?
It used also around 1.7 GB when I tried the example, but deleting the `res` results instance still left the memory of the process above 1 GB. Only when I deleted the model, then memory was completely freed.
Would it make sense to add a delete_array method that removes large arrays that can be recreated by another call to `predict` (similar but more focused than what we have for pickling just the results)?
Is the predicted state in a relatively isolated object that could be kept or deleted separately?

The adjusted example looked much slower than the original example, but I didn't check whether it was in fit or predict.

**Comment by ChadFulton** [comment] 2016-09-29 00:12
More specific replies below, but mostly the answer is that it could be done relatively easily; the primary thing is the interface work since the underlying filter can already be configured to use less memory.

> Is it possible to do this prediction with just filtering without keeping hold of come of the cov arrays, i.e. like minimal predict versus full get_prediction?

This is not possible right now, but the backend part would be easy to implement. Again, most of the work would be setting up the interface.

> Is it possible to get rid of some of the stored arrays again? And where are those attached?
It used also around 1.7 GB when I tried the example, but deleting the res results instance still left the memory of the process above 1 GB. Only when I deleted the model, then memory was completely freed.

The arrays are held in the results object but also in the underlying Cython filtering / smoothing classes, and the references to those are held in the model. This is so they can be re-used each time `filter`, `smooth`, or `fit` is called so we don't constantly allocate and de-allocate memory.

> Would it make sense to add a delete_array method that removes large arrays that can be recreated by another call to predict (similar but more focused than what we have for pickling just the results)?

I think this would be the way to go about it. The only think to think through is that we'd probably also want to make this compatible with pickling, so we'd want to design it such that we could specify only the arrays we wanted to keep, and then have the option of re-creating the other arrays on demand.

> Is the predicted state in a relatively isolated object that could be kept or deleted separately?

It is used by other things (e.g. `fittedresults`, `resid`), so deleting it might result in exceptions if they are accessed.

**Comment by fgilbert01** [comment] 2016-10-04 20:20
Hello,
This is to let you know about some test that I did.
I fit Sarimax model with one year of hourly data and retain calibration parameters. With this set of calibration parameters, I got back in time and have made predictions to compare with observed values. I saw that using the saved calibration parameters was not working as well as re-fitting the model for each prediction. This mean that I might have to fit the Sarimax on each prediction and memory usage becomes very important in that case. 2 gig of data consumption is large for a year of hourly historical load. If you can reduce it, that would be great.

**Comment by mcptnl** [comment] 2017-04-05 19:34
Hi Chad/fgilbert
Thanks for posting this.
I'm currently struggling with a SARIMAX model. 
The data has 1900 rows of hourly data (starting from 1/1/17) until March 22nd. My idea is to forecast this with some exogenous variables (8) for holidays, etc, so I made two df with this information and created a model like this: 

_mod = sm.tsa.statespace.SARIMAX(endog= solitudes,  order=(3,0,2), exog=ex,
      seasonal_order=(1,0,0,168),enforce_invertibility=False,enforce_stationarity=False,simple_differencing=True)_

I need to use a 168 seasonality in order to have similar values between e.g. next Monday 8pm. with the previous Monday 8pm.
The problem is that it takes so long (and sometimes it was restarting my system using more than 4GB) and I can't even visualize the model when running _results=mod.fit()_

Note: the 3,0,2 order was obtained by using auto.arima in R. 1,0,0,168 seasonality has reduced a bit of the memory consumption but ideally it would be 0,1,2,168
Is there any configuration I have to change or a way to reduce memory consumption?

Thanks in advance,

**Comment by bashtage** [comment] 2020-07-08 17:09
@ChadFulton I'm pretty sure this has been addressed but I'll leave it to you to close.

**Comment by ChadFulton** [comment] 2020-07-09 19:30
Yes, I think so, at least there's nothing more planned for this right now.  I'll also note here for future reference that `ARIMA` model with the `innovations_mle` algorithm allows fitting models with long seasonal effects (although it has some downsides, like not allowing missing values), and this can used as follows:

```python
mod = sm.tsa.arima.ARIMA(endog, order=(1, 0, 2), seasonal_order=(1, 1, 1, 365))
res = mod.fit(method='innovations_mle', low_memory=True, cov_type='none')
```

In the future, it may be that implementing #6812 will allow us to add even more functionality while maintaining fast / low memory.

**Closed by ChadFulton** 2020-07-09 19:30 UTC
Labels: comp-tsa, comp-tsa-statespace, type-bug
