### ISSUE TITLE
model.get_prediction does not pay attention to row_labels

### ISSUE THREAD

**Issue by cdeline** [statsmodels/statsmodels#5561] opened 2019-04-09 18:20 UTC
I've spent some time tracking down aberrant behavior of statsmodels (v0.8.0) where my code works correctly with one virtual environment, but not another.  I've tracked it down to statsmodels throwing away information related to the labels of the exogenous variables in get_prediction (specifically \regression\_prediction.py get_prediction).  Although the function pulls row_labels from the input functions, this information is thrown away by np.dot(exog, params) in linear_model.predict().  An update to statsmodels v0.9.0 didn't improve this behavior.

This won't be an issue for numpy array-type inputs, but it is an issue when passing pandas series, which do not have a defined order.  Specifically, the order is different with different pandas and python versions.  

I'd request the following possible fixes:   
1. actually do something with the row_labels to make sure that self.params and exog have the same labels in the same order when calculating the predicted_mean. (row 163 in \regression\_prediction.py)

2. improve your user manual / example usage to make it unambiguous how to use the regression model and get_prediction functions.

3. specifically disallow pandas Series to be passed in as exogenous variables if you're not going to be matching by index name / row label

I'm attaching an example script which fails in python 2.7 pandas 0.23.4, but is successful in python 3.6 pandas 0.23.4.  The reason it fails is that there is an assumption that the exogenous values remain in a specific order, which is not guaranteed by Pandas.

def StatsModelsError():

    import statsmodels.api as sm  
    import numpy as np
    import pandas as pd
    # do a ax^2+bx linear fit to the data'''
    a = 2; b = 5
    x = np.linspace(0,5)
    df = pd.DataFrame({'x^2':x**2,'x':x, 'y':a*x**2+b*x})
    exog =    df[['x^2','x']]
    endog = df['y']
    model = sm.OLS(endog, exog).fit()
    print(model.params)
    xtarget = 3
    temp1 = pd.Series({'x^2':xtarget**2,'x':xtarget})
    temp2 = np.array([xtarget**2,xtarget])
    predict1 = model.get_prediction(temp1).predicted_mean[0]
    predict2 = model.get_prediction(temp2).predicted_mean[0]
    assert(predict1==predict2)
    # for python 2.7, pandas 0.23.4, numpy 1.15.2, predict1 = 51, predict2 = 33.
    # for python 3.6, pandas 0.23.4, numpy 1.15.2, predict1 = 33, predict2 = 33

Thank you!!!

**Comment by jcdang** [comment] 2019-04-16 21:41
I think the proper solution would be for you to write the series like this:
`
temp1 = pd.Series({'x^2':xtarget**2,'x':xtarget}, index=exog.keys())
`
or
`
from collections import OrderedDict 
temp1 = pd.Series(OrderedDict({'x^2':xtarget**2,'x':xtarget}))
`

**Comment by ChadFulton** [comment] 2019-08-27 08:34
Since there has been no follow-up here, and since the original issue is for v0.8, I will close this. Please feel free to re-open if the issue is unresolved.

**Closed by ChadFulton** 2019-08-27 08:34 UTC
Labels: comp-regression
