### ISSUE TITLE
BUG: diffuse period (nobs_diffuse) is overestimated in diagnostic tests when mle_regression=False

### ISSUE THREAD

**Issue by tatamiya** [statsmodels/statsmodels#7342] opened 2021-02-21 08:59 UTC
#### Describe the bug

The results of diagnostic test methods below are different from what I expected
because the diffuse period (`nobs_diffuse`)  is overestimated
when I use regression in UnobservedComponents with `mle_regression=False`.

- [test_normality](https://github.com/statsmodels/statsmodels/blob/ad4b474b712517515400b0447998c6771897e02d/statsmodels/tsa/statespace/mlemodel.py#L2941)
- [test_heteroskedasticity](https://github.com/statsmodels/statsmodels/blob/ad4b474b712517515400b0447998c6771897e02d/statsmodels/tsa/statespace/mlemodel.py#L2989)
- [test_serial_correlation](https://github.com/statsmodels/statsmodels/blob/ad4b474b712517515400b0447998c6771897e02d/statsmodels/tsa/statespace/mlemodel.py#L3151)

In my understanding, `nobs_diffuse` is the number of diffuse initialization parameters 
and it is used for calculating effective observed data length (`nobs_effective`):
  (number of observed data) - (number of parameters estimated via diffuse initialization).

In the current implementation, this is represented as below:
https://github.com/statsmodels/statsmodels/blob/ad4b474b712517515400b0447998c6771897e02d/statsmodels/tsa/statespace/mlemodel.py#L3081-L3085

However, in my case below `nobs_diffuse` is much larger (expected 2 but actually 41).

As far as I saw, this problem takes place only when `mle_regression=False`.

If my understanding is correct, `nobs_diffuse` should be replaced by `k_diffuse_states`
because this property seems to always coincide with the number of diffuse initialization parameters.

#### Code Sample, a copy-pastable example if possible

```python
import statsmodels.api as sm

nile = sm.datasets.get_rdataset("Nile")

data = nile.data

data['dummy'] = (data['time']>1910).astype(int)

# local level model + regression
## number of diffuse initialization parameters is 2
llevel_model = sm.tsa.UnobservedComponents(data['value'], 
                                           level='local level',
                                           exog=data['dummy'],
                                           mle_regression=False, 
                                           use_exact_diffuse=True)

llevel_results = llevel_model.fit(method='lbfgs')

# Normality
## expected: 0.257115163206816
sm.stats.jarque_bera(llevel_results.standardized_forecasts_error[0][2:])[0]

## actual: 4.71655997736207
llevel_results.test_normality(method='jarquebera')[0][0]

# Serial correlation
## expected: 
## array([ 0.57831186,  0.64406109,  0.67693703,  2.25719498,  2.49950921,
##        2.71819373,  3.97947804,  5.34892425,  7.27403016, 12.42056881,
##       12.51833789, 12.53168576, 12.89328375, 12.91490691, 13.4522997 ,
##       13.67213356, 13.82392425, 14.4418782 , 14.54499544, 14.56818073,
##       14.59294545, 14.59648418, 15.59836306, 15.85790664, 16.37608682,
##       17.15810358, 17.1584262 , 17.77446619, 18.33865445, 19.7279967 ,
##       20.21790648, 20.23019406, 22.1891111 , 24.05375159, 25.2803473 ,
##       25.36948658, 26.29389837, 32.29775702, 32.33409201, 32.5354304 ])
sm.stats.acorr_ljungbox(llevel_results.standardized_forecasts_error[0][2:])[0]

## actual: 
## array([0.31573534, 0.69990287, 0.90046421, 4.40234864, 5.44223924,
##       5.48836724, 5.89268844, 6.32210186, 6.32528248, 6.34458572])
llevel_results.test_serial_correlation(method='ljungbox')[0][0]

llevel_results.df_model
## 4

llevel_results.nobs_diffuse
## 41, expected 2

llevel_results.k_diffuse_states
## 2



```

#### Expected Output

Noted in sample code above

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.8.5.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: ja_JP.UTF-8

statsmodels
===========

Installed: 0.12.1 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.4 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/numpy)
scipy: 1.5.4 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/scipy)
pandas: 1.2.0 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.1 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.3 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 7.19.0 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/IPython)
    jinja2: 2.11.2 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.7.3 (/Users/tatamiya/Library/Caches/pypoetry/virtualenvs/state-space-0JTrBQuf-py3.8/lib/python3.8/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment] 2021-02-22 07:46
Probably need @ChadFulton to comment.

**Comment by ChadFulton** [comment] 2021-02-22 16:15
> In my understanding, nobs_diffuse is the number of diffuse initialization parameters

`nobs_diffuse` is the number of periods for which there is a diffuse component in the conditional distribution of the state vector. In many cases this happens to be equal to the dimension of diffuse components in the distribution of the *initial* state vector, but it is not always the case. It basically depends on how much information the observed variables provide about the unobserved states - the less information is provided, the more periods it takes to produce an estimate of the state vector (i.e. move to a non-diffuse distribution).

> However, in my case below nobs_diffuse is much larger (expected 2 but actually 41).

When you include the regression coefficient in the state vector, it is initialized as diffuse. Typically, if there are `k` regressors, then it requires `k` periods to move out of the diffuse filter (this is just the same as saying that in OLS, you need at least `k + 1` periods to produce a unique estimate of `k` parameters).

Now, because you have a dummy variable that is equal to zero during the first 40 periods in question, the data does not provide any information to help estimate that coefficient, and the corresponding state distribution remains diffuse during that period. Then after one additional period (it is one period because `k=1` here), this diffuse element of the state vector finally falls away.

Notice, however, that this situation would not be helped if you switched the definition of the dummy variable to have ones for the pre-1910 period. That's because in that case, for the first 40 periods the dummy variable is acting like a constant term, and it is not identified separately from the initial state in the `level` term. So again, you can't eliminate the diffuse component of the state vector for the first 41 periods, until the variation in your data provides enough information to begin estimating the coefficient dummy variable.

> The results of diagnostic test methods below are different from what I expected

I see why there is an argument for using a different set of periods to compute the diagnostic statistics in this particular case than is implied by `nobs_diffuse`. However, based on the usual references (Harvey, 1989, and Durbin and Koopman, 2010), we are following the appropriate procedure and I don't see any changes that we could put in place in general. The best I can imagine is allowing users to override `nobs_diffuse`.

Alternatively, do you have a reference (a paper or documentation from some other software) that describes a different approach?

**Comment by tatamiya** [comment] 2021-02-23 09:22
Thank you for your reply!

I understand where the 'magic number' 41 comes from and why this is an appropriate procedure.

The reason why I considered the results strange is that I could not reproduce the results of Commandeur & Koopman 2007.
In section 7.2 of the book, the authors say the number of diffuse initialization parameters is 14
in a model with local level + seasonality + regression + intervention variable.
In order to compute them in a same way, I used `mle_regression=False` and found the difference I reported here.
In this type of model, however, I found MLE might be better for computing regression coefficients
although the number of diffuse initialization parameters is 12 and different from 14 in C&K book.
(Here is [my notebook](https://github.com/tatamiya/state_space_model_notebooks/blob/main/statsmodels/Comparison%20of%20Diffuse%20Initialization%20Period%20in%20Dummy%20Variable%20Regression%20(CommandeurKoopman2007%20Section7.2).ipynb))

Now I don't think we should change the three diagnostic test methods to override `nobs_diffuse`.
Instead of that, it would be more useful to move the core logic of `test_heteroskedasticity` method to `stats.stattools` or `stats.diagnostic`.
It is difficult to compute the heteroskedasticity test with different `nobs_diffuse`
because computation of `nobs_diffuse` and hypothesis test are both in the `test_heteroskedasticity` method.
On the other hand, it is easier in the serial correlation test and normality test because we can just use `stats.diagnostic.acorr_ljungbox` and `stats.stattools.jarque_bera`.
If we have a similar independent function like `stats.diagnostic.het_timeseries_residual_breakvar`,
we can reproduce the C&K book results and we can also apply the test to other types of time series models.
I will submit another issue.

**Comment by ChadFulton** [comment] 2021-02-26 00:38
> If we have a similar independent function like stats.diagnostic.het_timeseries_residual_breakvar,
we can reproduce the C&K book results and we can also apply the test to other types of time series models.
I will submit another issue.

I think that this is a good idea, and I look forward to seeing the new issue. Thanks!

**Comment by ChadFulton** [comment] 2021-02-26 00:53
Closing this since the new issue (#7348) has been posted.

**Closed by ChadFulton** 2021-02-26 00:53 UTC
Labels: comp-tsa-statespace, question
