### ISSUE TITLE
arma_process bugs, tests missing

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#218] opened 2012-04-03 19:30 UTC
bugs:

nobs is required for `__repr__`
impulse_response method has wrong call to function

no/insufficient tests for the class and methods

```
>>> tap.ArmaProcess.from_coeffs(res.arparams, res.maparams)
Traceback (most recent call last):
  File "<pyshell#64>", line 1, in <module>
    tap.ArmaProcess.from_coeffs(res.arparams, res.maparams)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new\statsmodels\statsmodels\tsa\arima_process.py", line 732, in __repr__
    self.nobs)
TypeError: %d format: a number is required, not NoneType
>>> tap.ArmaProcess.from_coeffs(res.arparams, res.maparams, nobs=100)
ArmaProcess([1.0, -1.5938842256919354, 0.82486374092452552], [1.0, -1.4271644149908818, 0.53181715373168881, 0.27500531483296076], nobs=100)

>>> ap.arma2ma(20)
array([ 1.        ,  0.16671981, -0.02731451,  0.09394802,  0.17227302,
        0.19708893,  0.17203517,  0.11163263,  0.03602392, -0.03466376,
       -0.08496484, -0.10683124, -0.10019221, -0.07157357, -0.03143506,
        0.00893459,  0.04017035,  0.05665707,  0.05716974,  0.04438758])

>>> ap.impulse_response(20)
Traceback (most recent call last):
  File "<pyshell#72>", line 1, in <module>
    ap.impulse_response(20)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new\statsmodels\statsmodels\tsa\arima_process.py", line 763, in impulse_response
    return arma_impulse_response(self.ar, self.ma, worN=nobs)
TypeError: arma_impulse_response() got an unexpected keyword argument 'worN'

```

**Comment by josef-pkt** [comment] 2015-08-17 22:06
just ran into this again, trying out an example

also impulse_response method seems to reverse `ma` and `ar`

**Comment by josef-pkt** [comment] 2015-08-18 02:21
several of the arima_process tests are for consistency and not externally validated

R for example has http://artax.karlin.mff.cuni.cz/r-help/library/stats/html/ARMAacf.html and http://artax.karlin.mff.cuni.cz/r-help/library/stats/html/ARMAtoMA.html

Stata seems to have only a few as postestimation function that require an estimated time series model, but covers several models. (some of the models are in the statespace PRs)

**Comment by bashtage** [comment] 2020-08-10 10:47
Appears to have been fixed in master.  Cannot reproduce.

**Closed by bashtage** 2020-08-10 10:47 UTC
Labels: comp-tsa, type-bug
