### ISSUE TITLE
Replicating SARIMAX prediction by Hand

### ISSUE THREAD

**Issue by hiqbal2** [statsmodels/statsmodels#7156] opened 2020-11-16 23:50 UTC
Hi, I am trying to replicate the SARIMAX prediction output manually but seem to keep getting errors. Following various threads, I get that the predictions are done using Kalman filter but I don't quite know exactly how?

I posted my question in https://stats.stackexchange.com/questions/496723/manual-hand-calculating-statsmodels-time-series-sarima-forecast but am hoping that someone here could help me out.

Specifically, I seem to be able to replicated on AR models. All other additions to the SARIMAX model makes my calculations not match.

**Comment by ChadFulton** [comment] 2020-11-17 12:24
> Specifically, I seem to be able to replicated on AR models. All other additions to the SARIMAX model makes my calculations not match.

The moving-average term in SARIMAX models must be estimated, and so it is not identical to the `resid` attribute near the beginning of the sample. See my answer to https://stats.stackexchange.com/questions/430186/how-statsmodels-predict-ma-process/430274#430274.

> I get that the predictions are done using Kalman filter but I don't quite know exactly how?

The Kalman filter is an iterative method for performing Bayesian updating for a class of linear Gaussian models. To apply it here, you have to write down the state space form of the ARIMA model and initialize the model with a prior (typically the unconditional distribution is used for stationary ARIMA models). Then you can apply the Kalman filter recursions to compute the predictions. See for example for example https://www.stat.purdue.edu/~chong/stat520/ps/statespace.pdf.

Closing this issue since this is not a bug, but feel free to follow up.

**Closed by ChadFulton** 2020-11-17 12:24 UTC
Labels: comp-tsa-statespace, question
