### ISSUE TITLE
order of exog variables producing different results?

### ISSUE THREAD

**Issue by jlin83** [statsmodels/statsmodels#4587] opened 2018-05-03 18:39 UTC
I'm not sure if this has been asked or is expected behavior, but I'm providing a list of covariates to an OLS in a slightly different order and getting different values for the coefficient for our "varOfInterest"

```
In [11]: X = df[['varOfInterest', 'var1', 'var2', 'var3']]
    ...: X = sm.add_constant(X)
    ...: Y = df['exp_ops']
    ...: model = sm.OLS(Y,X, missing='drop').fit(cov_type='HC1')
    ...: print(model.summary())
    ...: 
    ...: X = df[['var1', 'var2', 'var3', 'varOfInterest']]
    ...: X = sm.add_constant(X)
    ...: Y = df['exp_ops']
    ...: model = sm.OLS(Y,X, missing='drop').fit(cov_type='HC1')
    ...: print(model.summary())
    ...: 
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                exp_ops   R-squared:                      -0.230
Model:                            OLS   Adj. R-squared:                 -0.230
Method:                 Least Squares   F-statistic:                     37.76
Date:                Thu, 03 May 2018   Prob (F-statistic):           1.23e-31
Time:                        17:07:48   Log-Likelihood:            -3.0283e+08
No. Observations:            47860003   AIC:                         6.057e+08
Df Residuals:                47859998   BIC:                         6.057e+08
Df Model:                           4                                         
Covariance Type:                  HC1                                         
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const             -12.1226     25.011     -0.485      0.628     -61.143      36.898
varOfInterest      -0.0310      0.037     -0.841      0.400      -0.103       0.041
var1                0.0717      0.035      2.031      0.042       0.003       0.141
var2                1.5859      1.036      1.530      0.126      -0.445       3.617
var3                0.4401      0.416      1.058      0.290      -0.376       1.256
====================================================================================
Omnibus:                344834768.864   Durbin-Watson:                         1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   17793384208904003584.000
Skew:                        -881.091   Prob(JB):                               0.00
Kurtosis:                 2987094.065   Cond. No.                           2.05e+03
====================================================================================

Warnings:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.05e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                exp_ops   R-squared:                      -0.230
Model:                            OLS   Adj. R-squared:                 -0.230
Method:                 Least Squares   F-statistic:                     37.76
Date:                Thu, 03 May 2018   Prob (F-statistic):           1.22e-31
Time:                        17:08:18   Log-Likelihood:            -3.0283e+08
No. Observations:            47860003   AIC:                         6.057e+08
Df Residuals:                47859998   BIC:                         6.057e+08
Df Model:                           4                                         
Covariance Type:                  HC1                                         
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const             -12.2287     25.079     -0.488      0.626     -61.382      36.925
var1                0.0717      0.035      2.031      0.042       0.003       0.141
var2                1.5858      1.036      1.531      0.126      -0.445       3.617
var3                0.4401      0.416      1.058      0.290      -0.375       1.256
varOfInterest       0.1825      0.157      1.166      0.244      -0.124       0.489
====================================================================================
Omnibus:                344832443.476   Durbin-Watson:                         1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   17792147882442668032.000
Skew:                        -881.066   Prob(JB):                               0.00
Kurtosis:                 2986990.288   Cond. No.                           2.05e+03
====================================================================================

Warnings:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.05e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
```

Am I missing something in how the model is instantiated and fit?

**Comment by josef-pkt** [comment] 2018-05-03 19:03
No, this shouldn't happen.
There are some numerical problems with your dataset. I never tried 47 million observations.
Rsquared is negative, which shouldn't be possible.

check the scaling of your variables, especially of endog in this case.

Kurtosis is "gigantic" so you must have some very large observations in there. If observations differ widely in scale, then reduce operations like sum or the dot products in OLS will become numerically inaccurate and noisy, e.g. large quantities swamp small quantities.

e.g. if Y = df['exp_ops'] uses the exponential, then values can very quickly become very large or even overflow.

Condition number is not large enough to run into numerical problems because of multicollinearity, so I guess it's more the scaling of the response variable Y.

**Comment by josef-pkt** [comment] 2018-05-03 19:07
Just another sanity check, because we don't check this internally.
Is your data float64. With single precision float32 the numerical accuracy will be much lower, and could also cause this.
But given your kurtosis the problem is more severe than a single versus double precision issue

**Comment by nchehras** [comment] 2018-05-03 20:12
Thanks for the quick response. I tried a few things to better understand the source of the issue. 

- First, I manually calculated the coefficients (no changes in the underlying data), and the order of the covariates were irrelevant: 

`X1 = df[['x1', 'x2', 'x3', 'varOfInterest']]` 
`X1 = sm.add_constant(X1)`
`X1 = np.array(X1).astype('float')` 

`X2 = df[['varOfInterest', 'x1', 'x2', 'x3']]`
`X2 = sm.add_constant(X2)`
`X2 = np.array(X2).astype('float')`

`Y = np.array(df['exp_ops'])`

`b1 = np.dot(np.linalg.inv(np.dot(X1.T,X1)),np.dot(X1.T,Y))`
`print(b1)`
`#[ 9.87107701 -0.0122895   0.07457152  0.08244257 -0.02987899]`

`b2 = np.dot(np.linalg.inv(np.dot(X2.T,X2)),np.dot(X2.T,Y))`
`print(b2)`
`#[ 9.87107701 -0.02987899 -0.0122895   0.07457152  0.08244257]`


- I tried running the same data through the same regressions in Stata and didn't find this ordering issue:

`      Source |       SS           df       MS      Number of obs   =  47860003`
`-------------+----------------------------------   F(4, 47859998)  >  99999.00`
`       Model |  2.0961e+11         4  5.2402e+10   Prob > F        =    0.0000`
`    Residual |  5.0425e+11  47859998  10536.0065   R-squared       =    0.2936`
`-------------+----------------------------------   Adj R-squared   =    0.2936`
`       Total |  7.1386e+11  47860002  14915.6034   Root MSE        =    102.65`

`------------------------------------------------------------------------------------`
`             exp_ops |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]`
`-------------------+----------------------------------------------------------------`
`     varOfInterest |   -.029879   .0296744    -1.01   0.314    -.0880397    .0282817`
`		       x1 |  -.0122895   .0002174   -56.54   0.000    -.0127155   -.0118635`
`     		       x2 |   .0745715   .0000357  2085.96   0.000     .0745015    .0746416`
`		       x3 |   .0824426   .0008356    98.66   0.000     .0808049    .0840803`
`                 _cons |   9.871077   .0213724   461.86   0.000     9.829188    9.912966`
`------------------------------------------------------------------------------------`

- Stata output, different X order:

`      Source |       SS           df       MS      Number of obs   =  47860003`
`-------------+----------------------------------   F(4, 47859998)  >  99999.00`
`       Model |  2.0961e+11         4  5.2402e+10   Prob > F        =    0.0000`
`    Residual |  5.0425e+11  47859998  10536.0065   R-squared       =    0.2936`
`-------------+----------------------------------   Adj R-squared   =    0.2936`
`       Total |  7.1386e+11  47860002  14915.6034   Root MSE        =    102.65`

`------------------------------------------------------------------------------------`
`           exp_ops |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]`
`-------------------+----------------------------------------------------------------`
`		x1 |  -.0122895   .0002174   -56.54   0.000    -.0127155   -.0118635`
`   		x2 |   .0745715   .0000357  2085.96   0.000     .0745015    .0746416`
`		x3 |   .0824426   .0008356    98.66   0.000     .0808049    .0840803`
`     varOfInterest |   -.029879   .0296744    -1.01   0.314    -.0880397    .0282817`
`             _cons |   9.871077   .0213724   461.86   0.000     9.829188    9.912966`
`------------------------------------------------------------------------------------`
 
- When I removed (trimmed) outliers from the outcome variable, the discrepancy between the coefficients from regressions with different covariate ordering reduced. The more I trimmed, the more similar the coefficients were. I'm not suggesting that the right answer is to trim, but I thought that might help with troubleshooting. 
- Data is float64, but given that the manual formula works fine, I suspect there's something else going on.

**Comment by josef-pkt** [comment] 2018-05-03 21:00
not good, Stata has positive rsquared

can you try two more ways?

- use method QR instead of pinv in fit:  OLS(...).fit(method='qr')
- use pinv manually, i.e. `beta = np.linalg.pinv(X).dot(Y)`   with X1 and X2. This is our default method.

background info:

What's the scale of `varOfInterest`? i.e. min, max, std
All other coefficients are unchanged with the reordering, 

Do you know what your linear algebra in numpy is based on? i.e. MKL, OpenBlas, ...
(I don't remember how to check this.)

We don't have currently an option to use the moment conditions directly to compute the OLS params.
SVD, which we use through np.linalg.pinv, should be the most stable numerical algorithm, so the result here is surprising.

**Comment by nchehras** [comment] 2018-05-03 21:57
I agree, this is surprising. Info is below, let me know if there's anything else to try. 
- method = 'qr' doesn't seem to help: 
```
In [138]: Y = df['y']
     ...:
     ...: X = df[['varOfInterest', 'x1', 'x2', 'x3']]
     ...: X = sm.add_constant(X)
     ...:
     ...: model = sm.OLS(Y, X, missing ='drop').fit(method='qr')
     ...: print(model.summary())
     ...:
     ...: X = df[['x1', 'x2', 'x3', 'varOfInterest']]
     ...: X = sm.add_constant(X)
     ...:
     ...: model = sm.OLS(Y, X, missing ='drop').fit(method='qr')
     ...: print(model.summary())
     ...:
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                      -0.240
Model:                            OLS   Adj. R-squared:                 -0.240
Method:                 Least Squares   F-statistic:                -2.319e+06
Date:                Thu, 03 May 2018   Prob (F-statistic):               1.00
Time:                        21:22:19   Log-Likelihood:            -3.0304e+08
No. Observations:            47860003   AIC:                         6.061e+08
Df Residuals:                47859998   BIC:                         6.061e+08
Df Model:                           4
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           -12.3586      0.029   -427.415      0.000     -12.415     -12.302
varOfInterest    -0.0313      0.039     -0.797      0.425      -0.108       0.046
x1                1.5502      0.001   2666.278      0.000       1.549       1.551
x2                0.0744   2.35e-05   3161.802      0.000       0.074       0.074
x3                0.4397      0.000   2246.012      0.000       0.439       0.440
====================================================================================
Omnibus:                345634896.729   Durbin-Watson:                         1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   18206677654391498752.000
Skew:                        -889.742   Prob(JB):                               0.00
Kurtosis:                 3021586.056   Cond. No.                           1.98e+03
====================================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.98e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                      -0.240
Model:                            OLS   Adj. R-squared:                 -0.240
Method:                 Least Squares   F-statistic:                -2.319e+06
Date:                Thu, 03 May 2018   Prob (F-statistic):               1.00
Time:                        21:22:46   Log-Likelihood:            -3.0304e+08
No. Observations:            47860003   AIC:                         6.061e+08
Df Residuals:                47859998   BIC:                         6.061e+08
Df Model:                           4
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           -12.4654      0.029   -431.078      0.000     -12.522     -12.409
x1                1.5502      0.001   2666.327      0.000       1.549       1.551
x2                0.0744   2.35e-05   3161.836      0.000       0.074       0.074
x3                0.4397      0.000   2246.074      0.000       0.439       0.440
varOfInterest     0.1839      0.039      4.676      0.000       0.107       0.261
====================================================================================
Omnibus:                345631821.353   Durbin-Watson:                         1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   18205018061662484480.000
Skew:                        -889.709   Prob(JB):                               0.00
Kurtosis:                 3021448.339   Cond. No.                           1.98e+03
====================================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.98e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
```
- pinv results below: 
```
In [151]: X1 = df[['x1', 'x2', 'x3', 'varOfInterest']]
     ...: X2 = df[['varOfInterest', 'x1', 'x2', 'x3']]
     ...:
     ...: beta = np.linalg.pinv(X1).dot(Y)
     ...: print(beta)
     ...:
     ...: beta = np.linalg.pinv(X2).dot(Y)
     ...: print(beta)
     ...:
[  1.58720159   0.07951963   0.448666   -38.88012564]
[-11.6266993    1.50116927   0.07357854   0.43270227]

```

- varOfInterest is just an (exog) indicator variable, 50/50 1's and 0's

- using `np.__config__.show()` it looks like numpy is based on OpenBlas

**Comment by josef-pkt** [comment] 2018-05-04 01:14
Do you have access to a version with an MKL based numpy?

There were some bugs with SVD with large arrays in OpenBLAS in the past, but I don't know if any of them are related to this.

Another possibility to try is to turn of multithreading in OpenBLAS, in case that's a source of problems. #2914

**Comment by josef-pkt** [comment] 2018-05-04 01:29
In some cases Stata has a numerically more robust implementation than statsmodels, but I never seen an example for OLS. In discrete Poisson Stata can converge without problems where statsmodels runs into exp overflow problems during the optimization if some exog have larger values.

However, here it is just basic linear algebra. One reparameterization that some packages use for the linear model is to take out the mean, i.e. estimate the model with demeaned variables, endog and exog, and estimate OLS without intercept, and then recover the constant from the residuals. This can help in cases where the mean is large compared to fluctuations around the mean.

This demeaning might help, but my guess is now on an OpenBlass bug.

**Comment by bashtage** [comment] 2019-07-19 15:18
Closing as answered.

**Closed by bashtage** 2019-07-19 15:18 UTC
