### ISSUE TITLE
Unable to reproduce results with saved STLForecast model

### ISSUE THREAD

**Issue by gsamaras** [statsmodels/statsmodels#8201] opened 2022-03-30 11:23 UTC
#### Describe the issue

When I save the result of the model of STLForecast() and then forecast, I get poor accuracy. If I use the result right away, the forecast works fine. I am not saying this is a bug, but I am missing something? I don't save the right thing?

#### Code Sample, a copy-pastable example if possible

```python
import matplotlib.pyplot as plt
from statsmodels.datasets import elec_equip as ds
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.forecasting.stl import STLForecast

elec_equip = ds.load().data
elec_equip.index.freq = 'MS'
stlf = STLForecast(elec_equip, ARIMA, model_kwargs=dict(order=(1, 1, 0), trend="t"))
stlf_res = stlf.fit()

forecast = stlf_res.forecast(24)
plt.plot(elec_equip)
plt.plot(forecast)
plt.show()
```
which gives good accuracy:

![Screen Shot 2022-03-30 at 2 16 52 PM](https://user-images.githubusercontent.com/12050610/160822612-d4b74fad-0a97-4fbd-a548-e28846219a5f.png)
However when I do:
```python
import statsmodels.api as sm

stlf_res.model_result.save("STLF_model.pickle") # am I saving the right thing?
STFL_model = sm.load("STLF_model.pickle")

forecast = STFL_model.forecast(24)
plt.plot(elec_equip)
plt.plot(forecast)
plt.show()
```
I get bad performance:
![Screen Shot 2022-03-30 at 2 20 26 PM](https://user-images.githubusercontent.com/12050610/160823140-6d56a6c5-03be-4c70-9a57-99352c02bcf0.png)

I also tried:
```
stlf_res.model.save("STLF_model.pickle")
```
but I got that ARIMA model has no save method.

Maybe I am not saving the right thing. How should I save the model please?

#### Useful links
[STLForecastResults](https://www.statsmodels.org/devel/generated/statsmodels.tsa.forecasting.stl.STLForecastResults.html#statsmodels.tsa.forecasting.stl.STLForecastResults)
[ARIMAResults](https://www.statsmodels.org/devel/generated/statsmodels.tsa.arima.model.ARIMAResults.html#statsmodels.tsa.arima.model.ARIMAResults)
[ARIMAResults.save](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima.model.ARIMAResults.save.html)

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.12.final.0
OS: Linux 5.10.90+ #1 SMP Wed Mar 23 09:10:07 UTC 2022 x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8

statsmodels
===========

Installed: 0.13.1 (/opt/conda/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.28 (/opt/conda/lib/python3.7/site-packages/Cython)
numpy: 1.20.3 (/opt/conda/lib/python3.7/site-packages/numpy)
scipy: 1.7.3 (/opt/conda/lib/python3.7/site-packages/scipy)
pandas: 1.3.5 (/opt/conda/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.2 (/opt/conda/lib/python3.7/site-packages/dateutil)
patsy: 0.5.2 (/opt/conda/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.5.1 (/opt/conda/lib/python3.7/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.1.0 (/opt/conda/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.30.1 (/opt/conda/lib/python3.7/site-packages/IPython)
    jinja2: 3.0.3 (/opt/conda/lib/python3.7/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.10.0 (/opt/conda/lib/python3.7/site-packages/pygments)
pytest: 7.1.0 (/opt/conda/lib/python3.7/site-packages/pytest)
virtualenv: 20.10.0 (/opt/conda/lib/python3.7/site-packages/virtualenv)
</details>

**Comment by bashtage** [comment] 2022-03-30 15:04
Closing since not a bug.

**Closed by bashtage** 2022-03-30 15:04 UTC
