### ISSUE TITLE
Interface for tsa.acf and tsa.graphics.plot_acf differs

### ISSUE THREAD

**Issue by ispmarin** [statsmodels/statsmodels#4154] opened 2017-12-07 18:02 UTC
The interface for the function `tsa.acf` uses the parameter `nlags` while the function `tsa.graphics.tsa.plot_acf` uses the parameter `lags`.

**Comment by josef-pkt** [comment] 2017-12-07 18:25
I don't remember the details or reason.
Based on the docstring and implementation of the `lags` option in `plot_acf`, those two are different, lags is more general than nlags, and allows for an arbitrary array of lags, while acf nlags specifies a fixed number of consecutive lags.

**Comment by bashtage** [comment] 2019-07-23 13:37
Closing as by design.

**Closed by bashtage** 2019-07-23 13:37 UTC
Labels: comp-graphics, comp-tsa
