### ISSUE TITLE
MissingDataError: exog contains inf or nans

### ISSUE THREAD

**Issue by slamer59** [statsmodels/statsmodels#5187] opened 2018-09-12 11:32 UTC
Hello,
I have a problem with my data. 
I am using adfuller test on them and get this error.
_MissingDataError: exog contains inf or nans_

What does it means and how exactly ? What is exog ? Is it possible to clean my data upfront ? How ?

Regards,
Thomas PEDOT

**Comment by gisunzl** [comment] 2018-09-20 01:15
i have the same problem, would you resolve it?

**Comment by josef-pkt** [comment] 2018-09-20 01:41
adfuller and most other tsa functions cannot handle missing values.
If you have missing values only in front and end, then it is possible to remove those from the data, e.g. using pandas dropna.
If there are missing data in between valid data, then the problem is more serious. We cannot just drop observations because time series have ordering on a fixed time grid and lags need to refer to the observation at a previous time point. After dropping a missing observations the lag would refer to an additional period in the past.

If there are only a few missing observations, then imputing them (e.g. with pandas) would not distort the results by much.

Another case is if observations correspond to events and not to time period, i.e. irregularity in time periods is irrelevant. In those cases it might still make sense to drop observations even in the middle.
(e.g. event is when a person goes running, the time series has a lag structure in terms of previous runs. If we miss one run, then the previous event is still the latest previous run and calender time wouldn't matter.)

(asides: I thought I remember an issue for this but the only one I find is #1345
My guess is that in the auxiliary regression we could drop cases/observations with missing endog or any of the exog/lagged values. In this case, we would drop observations that are "infected" by a neighboring missing value and keep only the complete subsets of periods that form a valid observation in the auxiliary regression. Added complication: selecting the lag would have to use the smallest common subset of observations.
Theoretical problem: the underlying process would have jumps across the excluded intervals, while the asymptotic distribution assumes a continuous path, random walk.
)

**Comment by bashtage** [comment] 2019-07-19 14:44
Closed as answered.

**Closed by bashtage** 2019-07-19 14:44 UTC

**Comment by hendshe** [comment] 2021-05-12 12:46
How could you know which variable is causing the error when this error is shown? (MissingDataError: exog contains inf or nans)

**Comment by bashtage** [comment] 2021-05-12 13:29
`np.any(~np.infinite(exog),axis=0)`

**Comment by hendshe** [comment] 2021-05-12 13:48
> `np.any(~np.infinite(exog),axis=0)`

Thanks a lot! But this has given the following error without showing the variables

> AttributeError: module 'numpy' has no attribute 'infinite'

**Comment by bashtage** [comment] 2021-05-12 13:51
Sorry `isfinite`

**Comment by hendshe** [comment] 2021-05-12 14:27
Thank you! Although it has shown me earlier this above-error related to exog, now when I type this command, I get that (name 'exog' is not defined). So, I have no clue how to identify the cause of the error (exog. contain inf or nans) or to correct it.

>  np.any(~np.isfinite(exog),axis=0) 

NameError: name 'exog' is not defined
![image](https://user-images.githubusercontent.com/77800456/117991796-ab680f80-b33e-11eb-951d-5015ca20aa96.png)

**Comment by bashtage** [comment] 2021-05-12 15:10
`exog` is the name of the variable you are using in the exog position in the model construction.

**Comment by hendshe** [comment] 2021-09-06 14:22
> same problem with me while printing arima model in notebook
> 
> MissingDataError: exog contains inf or nans
> 
> how to resolve this issue any body knows idea?

What has worked for me is recoding the missings as zeros to bypass this

**Comment by VARMASANGARAJU** [comment] 2021-10-14 08:14
`main_df.isnull().sum()`

> check if having any null values 
if any use 

`main_df.dropna(axis=0)`
