### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by chkewat** [statsmodels/statsmodels#4160] opened 2017-12-11 16:45 UTC
Getting below error while trying to install "statsmodels" even I already have "Microsoft Visual C++ 14.10" installed on my machine.

OS : Windows 7
Python Version : 3.6
command used : pip install statsmodel

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Please could you help.

**Comment by bashtage** [comment] 2017-12-11 22:43
You should run setup from the VS2015 x64 native tools command promot (assuming Windows 64).

**Comment by chkewat** [comment] 2017-12-12 13:42
Hi ,
Thanks a lot for your response!!
But still same error.  Just to confirm , what i understand by "VS2015 x64 native tools command promot" is "MS Build Command prompt" and "Developers Command prompt 2015"  under VS2015 Tools in start menu. 
Please find attached screenshot of error. 
Kindly let me know if I can try anything else?

![statsmodelserror](https://user-images.githubusercontent.com/28755047/33887530-effaf42a-df41-11e7-8e71-06ad82ac7db2.JPG)

**Comment by bashtage** [comment] 2017-12-12 13:48
It should be this:

![image](https://user-images.githubusercontent.com/5585221/33887793-e7faaad0-df42-11e7-9eae-9c4a25eca1cc.png)

It looks like your numpy is broken.  

What do you get when you try

python -c "import numpy;print(numpy.__version__)"

from the same command prompt?

**Comment by chkewat** [comment] 2017-12-12 14:06
Thanks again!!, 
I can see only following command prompts .
![commandprompt](https://user-images.githubusercontent.com/28755047/33888630-8ab2189c-df45-11e7-8d80-aa12d59ad784.JPG)


And Numpy is..
![numpyversion](https://user-images.githubusercontent.com/28755047/33888647-986a081e-df45-11e7-8fdd-293ed8e7c878.JPG)

**Comment by bashtage** [comment] 2017-12-13 08:04
Hard to say what the problem is.  As an alternative, I would suggest using miniconda.  You could do the following after install miniconda and adding it to the system path.

```bash
conda install statsmodels matplotlib ipython -y
conda remove statsmodels
cd statsmodels  # cd to the git repo
pip install -e .
```

which will install statsmodels dependencies and 0.8.0 statsmodels, and then remove 0.8.0 statsmodels.  Finally you can install from the git repo.

**Comment by maryam1ou** [comment] 2018-01-04 10:19
i followed your solutions , it seams that i have the same issue, with the visual 2015 installed i get the error 
![capture](https://user-images.githubusercontent.com/29778599/34559082-77634888-f138-11e7-8a82-5cff92f56560.PNG)
 And when i used the commande line you suggested  whith numpy
python -c "import numpy;print(numpy.version)"
i get 
![capture](https://user-images.githubusercontent.com/29778599/34559145-afa79ac8-f138-11e7-9c10-01685384fe44.PNG)
can you please help me

**Comment by bashtage** [comment] 2018-01-04 10:30
Have you actually installed the C/C++ components?  If you have you should have a commend prompt called  "VS2015 x64 Native Tools Command Prompt". If you want to check, open the VS command prompt and enter

```
cl /?
```
Post the top 5 lines of running this command

**Comment by maryam1ou** [comment] 2018-01-04 10:37
i don't have the "VS2015 x64 NAtive Tools command prompt" 
i tried the link my cmd suggested in the error : 
 http://landinghub.visualstudio.com/visual-cpp-build-tools 
it is running right now 
![capture](https://user-images.githubusercontent.com/29778599/34559806-36483e96-f13b-11e7-9eb8-68d4e2e0e63b.PNG)

**Comment by bashtage** [comment] 2018-01-04 10:45
Yes, the C compiler is required.  Once this is installed setup should run.

**Comment by maryam1ou** [comment] 2018-01-04 10:46
Yes it works thank you .

**Comment by meleeboy** [comment] 2018-06-05 05:43
the link to visual c++ build tools is broken. Hope this one helps to people who face same issue:
http://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe

**Comment by SushenL** [comment] 2018-06-08 01:53
hi meleeboy
I uninstalled "microsoft visual c++ 2017" and install the Link of 2015 , but it not work ....
![image](https://user-images.githubusercontent.com/34903459/41134967-bd44e0a8-6b01-11e8-835a-a02d8609b7f8.png)

**Comment by requeijaum** [comment] 2018-06-18 15:41
Links here:

http://web.archive.org/web/20170519122327/http://landinghub.visualstudio.com:80/visual-cpp-build-tools

http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe

**Comment by sowindy** [comment] 2018-06-20 03:29
@requeijaum u r right

**Comment by requeijaum** [comment] 2018-06-26 16:16
I updated some stuff. The link is working, though.

**Comment by ShubhamHalyal** [comment] 2018-07-06 06:53
@chkewat  link http://landinghub.visualstudio.com/visual-cpp-build-tools doesn't work. I tried all the suggestions on this page, but nothing works for python 3.7.
But works for python 2.7.

**Comment by rabinlc** [comment] 2018-08-20 09:30
I have installed visual c++ but it is not working

**Comment by Halkaramov2019** [comment] 2018-12-10 00:45
> Use the link to http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe. That will install Visual C++ 14.0 without installing Visual Studio.

Thank you very much, it worked for me

**Comment by macik1423** [comment] 2019-02-05 13:17
> 
> 
> Use the link to http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe. That will install Visual C++ 14.0 without installing Visual Studio.

Thanks! Finally I installed scrapy without problems and conda.

**Comment by bashtage** [comment] 2019-06-08 13:48
This has been very quiet, so I am closing as solved. Please reopen if it continues.

**Closed** 2019-06-08 14:01 UTC

**Comment by mujdeayik** [comment] 2019-07-12 15:58
I have a work desktop which cannot be connected to internet due to security. I have therefore installed statsmodels package to a directory in another laptop and moved it to a folder the work desktop (python 3.7-32 bit). Installing the statsmodels package from that directory via command prompt, ı had the same issue. I installed the full package visual c++ 14 without installing visual studio, but that did not resolve the issue. I cannot upgrade pip as the pc not internet connected. Although python just installed from a software center perhaps pip with it is not up to date but not sure. How can ı update pip on an internet connected laptop and replace it with the pip in work laptop? Would that resolve the issue? Many thanks

**Comment by bashtage** [comment] 2019-07-12 16:04
You can download the appropriate whl file and then do a local install assuming NAME-OF_FILE.whl is in the same directory, `pip install NAME-OF_FILE.whl`.  This said, there is no 32-bit Wheel for Python 3.7 since pandas didn't have one when the 0.10.0 wheels were built.  This should be fixed by 0.10.1.

**Comment by mujdeayik** [comment] 2019-07-12 17:24
Thanks a lot Kevin. Does that mean I need to uninstall 32 bit Python and install 62 bit instead?

**Comment by bashtage** [comment] 2019-07-12 17:44
64-bit is always my recommendation unless you are forced to run 32-bit
windows or have other constraints.

**Comment by KARTHIK-RAJU-G** [comment] 2019-07-14 14:17
![IMG-20190714-WA0003](https://user-images.githubusercontent.com/52886689/61184813-88e80b00-a66f-11e9-91c8-0d29aedb2950.jpg)
can you help me out i have installed opencv correctly and code is also correct 
import cv2
image = cv2.imread("clouds.jpg")
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Over the Clouds", image)
cv2.imshow("Over the Clouds - gray", gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Comment by mujdeayik** [comment] 2019-07-16 08:12
Just installed 3.7 64 bit. Now visual c++ error resolved while installing statsmodels package. However i have got another error now which is: could not find a version that satisfies the requirement statsmodels. I have downloaded statsmodels version a zip file from github

**Comment by tecdee** [comment] 2019-08-01 15:10
> Links here:
> 
> http://web.archive.org/web/20170519122327/http://landinghub.visualstudio.com:80/visual-cpp-build-tools
> 
> ## http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe
> shasum output:
> 
> ```
> 3e0de8af516c15547602977db939d8c2e44fcc0b  visualcppbuildtools_full.exe
> ```
> 
> md5sum output:
> 
> ```
> MD5 (visualcppbuildtools_full.exe) = 8d4afd3b226babecaa4effb10d69eb2e
> ```
> 
> rghost mirror:
> http://rgho.st/8bZNpMNH4

Your solution worked for me. Thanks a lot.

**Comment by JasmeetSinghO7** [comment] 2020-02-24 07:40
I'm getting same error in my pycharm while installing packages...... anybody have any idea how to fix it?

**Comment by bashtage** [comment] 2020-02-24 08:11
Install Build Tools for Visual Studio 2019 which then lets you install the Visual Studio 2015 C compiler, which is the correct C++.

**Comment by JasmeetSinghO7** [comment] 2020-02-24 09:26
Thank you for responding to may query.... actually I have started pycharm
with anaconda and now packages are working fine.
Thanks & Regards

**Comment by asbaghel** [comment] 2020-07-03 07:04
> You should run setup from the VS2015 x64 native tools command promot (assuming Windows 64).

It works from that cmd but not from any other terminal

**Comment by bashtage** [comment] 2020-07-03 07:07
> It works from that cmd but not from any other terminal

This suggests there is a path issue.  It can be difficult to debug these when Python won't automatically pick it up. It should work from any termin (cmd or PowerShell) when properly configured.

**Comment by bashtage** [comment] 2020-07-03 07:11
When you click on modify on

![image](https://user-images.githubusercontent.com/5585221/86441828-ba386b80-bd04-11ea-80dc-bd3db778343a.png)

You should see (at a minimum):

![image](https://user-images.githubusercontent.com/5585221/86441868-c7edf100-bd04-11ea-92bf-8597fe86f80a.png)

**Comment by SajalSinghal** [comment] 2020-10-18 07:37
You can install misaka package by conda install -c conda-forge/label/cf202003 misaka

**Comment by rishik-00** [comment] 2021-06-02 16:47
hey @bashtage i am getting the same error while installing cvxpy, i have also installed the visual tools , please help me
![Capture](https://user-images.githubusercontent.com/43490153/120519419-398c5e80-c3f0-11eb-94f1-d6987e76fcd2.JPG)
I have installed these files from the visual tools, please tell me if i need to check anymore

**Comment by bashtage** [comment] 2021-06-18 14:25
cvxpy is hard to build. If you need this you should stick with platforms that have wheels available.

**Comment by bashtage** [comment] 2021-06-18 14:26
You can also get it from conda using conda-forge.
