### ISSUE TITLE
Running from Windows cmd.exe, plots freeze the console

### ISSUE THREAD

**Issue by Beliavsky** [statsmodels/statsmodels#7513] opened 2021-06-18 23:10 UTC
In the cmd.exe console of Windows 10, if I type

`python ex_kernel_regression.py`

the script runs and a plot appears in my web browser and a message

`Press Cntrl+C to stop WebAgg server`

appears in the console. However, closing the tab with the plot and following that instruction in the console does not work -- it stays frozen. I need to close the console and open a new one every time I run a script, which is inconvenient.

**Comment by bashtage** [comment] 2021-07-05 10:15
I can't reproduce locally.  Running the example creates a window, and then when I close the window it finishes.  Perhaps you have a bad backend setup?  Try a standard backen (e.g., Qt5) More of a matplotlib issue.  Closing since nothing for us to do.

**Closed by bashtage** 2021-07-05 10:15 UTC
