### ISSUE TITLE
Handle missing values with state space model (Local Linear Trend)

### ISSUE THREAD

**Issue by adoherty21** [statsmodels/statsmodels#7684] opened 2021-09-03 14:50 UTC
#### Describe the bug

I am using statsmodels to fit a Local Linear Trend state space model which inherits from the sm.tsa.statespace.MLEModel class using the code from the example in the documentation:

https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_local_linear_trend.html

The state space model and Kalman filter should handle missing values naturally but when I add some null values the state space model outputs nulls. In another example in the docs, implementing SARIMAX it appears that missing data appears to be handled automatically:

https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_internet.html

Is there a way to handle missing values in the same way for a Local Linear Trend model?

I posted this in Stackoverflow - https://stackoverflow.com/questions/69042614/handle-missing-values-with-stats-models-local-linear-trend-model

Running version '0.12.2'

I am happy to support the development of this feature if it is required.

#### Code Sample

```python

%matplotlib inline

import numpy as np
import pandas as pd
from scipy.stats import norm
import statsmodels.api as sm
import matplotlib.pyplot as plt



"""
Univariate Local Linear Trend Model
"""
class LocalLinearTrend(sm.tsa.statespace.MLEModel):
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 2
        # Initialize the statespace
        super(LocalLinearTrend, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['design'] = np.array([1, 0])
        self.ssm['transition'] = np.array([[1, 1],
                                       [0, 1]])
        self.ssm['selection'] = np.eye(k_states)

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['sigma2.measurement', 'sigma2.level', 'sigma2.trend']

    @property
    def start_params(self):
        return [np.std(self.endog)]*3

    def transform_params(self, unconstrained):
        return unconstrained**2

    def untransform_params(self, constrained):
        return constrained**0.5

    def update(self, params, *args, **kwargs):
        params = super(LocalLinearTrend, self).update(params, *args, **kwargs)

        # Observation covariance
        self.ssm['obs_cov',0,0] = params[0]

        # State covariance
        self.ssm[self._state_cov_idx] = params[1:]
        
        

import requests
from io import BytesIO
from zipfile import ZipFile

# Download the dataset
ck = requests.get('http://staff.feweb.vu.nl/koopman/projects/ckbook/OxCodeAll.zip').content
zipped = ZipFile(BytesIO(ck))
df = pd.read_table(
    BytesIO(zipped.read('OxCodeIntroStateSpaceBook/Chapter_2/NorwayFinland.txt')),
    skiprows=1, header=None, sep='\s+', engine='python',
    names=['date','nf', 'ff']
)


# Load Dataset
df.index = pd.date_range(start='%d-01-01' % df.date[0], end='%d-01-01' % df.iloc[-1, 0], freq='AS')

# Log transform
df['lff'] = np.log(df['ff'])


# The only change I have made from the online tutorial is to include this null
df['lff'][5] = np.nan

# Setup the model
mod = LocalLinearTrend(df['lff'])

# Fit it using MLE (recall that we are fitting the three variance parameters)
res = mod.fit(disp=False)
print(res.summary())

```

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

I would expect that the output of the model with null values present is not impacted fully as the Kalman filter should handle nulls.

#### Output

<details>

The output is a model summary contains all null values other than Jarque-Bera, Prob, Skew and Kurtosis.

</details>

**Comment by ChadFulton** [comment] 2021-09-04 02:30
The statespace models can indeed handle `NaN` values in the `endog` variable. I think the issue is that in this example code, the starting parameters are computed as:

```python
    @property
    def start_params(self):
        return [np.std(self.endog)]*3
```

To handle `NaN` values in the data, you'd want to replace this with:

```python
    @property
    def start_params(self):
        return [np.nanstd(self.endog)]*3
```

**Comment by ChadFulton** [comment] 2021-09-04 02:31
I'm closing this as answered, but feel free to re-open if it still doesn't work. Unfortunately I'll be pretty unresponsive for the next few weeks though, but I'd be happy to help after that.

**Closed by ChadFulton** 2021-09-04 02:31 UTC
Labels: comp-tsa-statespace, question

**Comment by adoherty21** [comment] 2021-09-06 09:12
Thanks a lot Chad I can confirm this solution worked.  The implementation it is very comprehensive.  Cheers

**Comment by ChadFulton** [comment] 2021-09-13 06:46
Thanks for letting us know!
