### ISSUE TITLE
Logit dtype - bool variables causes AttributeError: 'float' object has no attribute 'exp'

### ISSUE THREAD

**Issue by mpekalski** [statsmodels/statsmodels#2850] opened 2016-03-10 11:25 UTC
I have quite big dataset that I am trying to run Logit on. It fails on fit method. As far as I understand the cause are boolean columns in the dataset. 

I have a pandas dataframe **df**
```
set(df.dtypes)
{dtype('bool'), dtype('int64'), dtype('float64')}
```
when I run 
```
from statsmodels.discrete.discrete_model import Logit
from statsmodels.tools import add_constant 
Y =  add_constant(df, prepend=True)

lg = Logit(target, Y)
lg_model = lg.fit()
print lg.model.summary()
```

I get an error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-5f97b1d0eb1f> in <module>()
      4 
      5 lg = Logit(target, Y)
----> 6 lg_model = lg.fit()
      7 print lg.model.summary()

/usr/lib/python2.7/dist-packages/statsmodels/discrete/discrete_model.pyc in fit(self, start_params, method, maxiter, full_output, disp, callback, **kwargs)
   1184         bnryfit = super(Logit, self).fit(start_params=start_params,
   1185                 method=method, maxiter=maxiter, full_output=full_output,
-> 1186                 disp=disp, callback=callback, **kwargs)
   1187         discretefit = LogitResults(self, bnryfit)
   1188         return BinaryResultsWrapper(discretefit)

/usr/lib/python2.7/dist-packages/statsmodels/discrete/discrete_model.pyc in fit(self, start_params, method, maxiter, full_output, disp, callback, **kwargs)
    162         mlefit = super(DiscreteModel, self).fit(start_params=start_params,
    163                 method=method, maxiter=maxiter, full_output=full_output,
--> 164                 disp=disp, callback=callback, **kwargs)
    165         return mlefit # up to subclasses to wrap results
    166 

/usr/lib/python2.7/dist-packages/statsmodels/base/model.pyc in fit(self, start_params, method, maxiter, full_output, disp, fargs, callback, retall, **kwargs)
    355                              disp=disp, maxiter=maxiter, callback=callback,
    356                              retall=retall, full_output=full_output,
--> 357                              hess=hess)
    358 
    359         if not full_output: # xopt should be None and retvals is argmin

/usr/lib/python2.7/dist-packages/statsmodels/base/model.pyc in _fit_mle_newton(f, score, start_params, fargs, kwargs, disp, maxiter, callback, retall, full_output, hess)
    401     while (iterations < maxiter and np.any(np.abs(newparams -
    402             oldparams) > tol)):
--> 403         H = hess(newparams)
    404         oldparams = newparams
    405         newparams = oldparams - np.dot(np.linalg.inv(H),

/usr/lib/python2.7/dist-packages/statsmodels/base/model.pyc in <lambda>(params)
    348         if method == 'newton':
    349             score = lambda params: self.score(params) / nobs
--> 350             hess = lambda params: self.hessian(params) / nobs
    351             #TODO: why are score and hess positive?
    352 

/usr/lib/python2.7/dist-packages/statsmodels/discrete/discrete_model.pyc in hessian(self, params)
   1177         """
   1178         X = self.exog
-> 1179         L = self.cdf(np.dot(X,params))
   1180         return -np.dot(L*(1-L)*X.T,X)
   1181 

/usr/lib/python2.7/dist-packages/statsmodels/discrete/discrete_model.pyc in cdf(self, X)
   1024         """
   1025         X = np.asarray(X)
-> 1026         return 1/(1+np.exp(-X))
   1027 
   1028     def pdf(self, X):

AttributeError: 'float' object has no attribute 'exp'
```

Changing all boolean columns to folat64
```
for x in df.columns:
    if (df[x].dtype == numpy.bool):
        df[x] = df[x].astype(numpy.float64)
```

changes the error
```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-8-5f97b1d0eb1f> in <module>()
      4 
      5 lg = Logit(target, Y)
----> 6 lg_model = lg.fit()
      7 print lg.model.summary()

/usr/lib/python2.7/dist-packages/statsmodels/discrete/discrete_model.pyc in fit(self, start_params, method, maxiter, full_output, disp, callback, **kwargs)
   1184         bnryfit = super(Logit, self).fit(start_params=start_params,
   1185                 method=method, maxiter=maxiter, full_output=full_output,
-> 1186                 disp=disp, callback=callback, **kwargs)
   1187         discretefit = LogitResults(self, bnryfit)
   1188         return BinaryResultsWrapper(discretefit)

/usr/lib/python2.7/dist-packages/statsmodels/discrete/discrete_model.pyc in fit(self, start_params, method, maxiter, full_output, disp, callback, **kwargs)
    162         mlefit = super(DiscreteModel, self).fit(start_params=start_params,
    163                 method=method, maxiter=maxiter, full_output=full_output,
--> 164                 disp=disp, callback=callback, **kwargs)
    165         return mlefit # up to subclasses to wrap results
    166 

/usr/lib/python2.7/dist-packages/statsmodels/base/model.pyc in fit(self, start_params, method, maxiter, full_output, disp, fargs, callback, retall, **kwargs)
    355                              disp=disp, maxiter=maxiter, callback=callback,
    356                              retall=retall, full_output=full_output,
--> 357                              hess=hess)
    358 
    359         if not full_output: # xopt should be None and retvals is argmin

/usr/lib/python2.7/dist-packages/statsmodels/base/model.pyc in _fit_mle_newton(f, score, start_params, fargs, kwargs, disp, maxiter, callback, retall, full_output, hess)
    403         H = hess(newparams)
    404         oldparams = newparams
--> 405         newparams = oldparams - np.dot(np.linalg.inv(H),
    406                 score(oldparams))
    407         if retall:

/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.pyc in inv(a)
    524     signature = 'D->D' if isComplexType(t) else 'd->d'
    525     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 526     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
    527     return wrap(ainv.astype(result_t, copy=False))
    528 

/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.pyc in _raise_linalgerror_singular(err, flag)
     88 
     89 def _raise_linalgerror_singular(err, flag):
---> 90     raise LinAlgError("Singular matrix")
     91 
     92 def _raise_linalgerror_nonposdef(err, flag):

LinAlgError: Singular matrix
```

I know the matrix is ill conditioned, so the second error is not that of a surprise, but the algorithm hot being able to deal with boolean variables is kind of a surprise.
```
numpy.linalg.cond(Y) 
3.4030346042451334e+73
```

**Comment by josef-pkt** [comment] 2016-03-10 13:52
The only possible explanation that I can come up with is that your `target` endog variable is an object array, which would be used by pandas instead of a bool if there are missing values.

What's the detype in
`np.asarray(target).dtype`?

If that's not it, then we need a reproducable example, e.g. with part of the failing data or some made up similar data.

What version of statsmodels are you using? I thought we check now for object arrays, but that might not be for all cases.

**Comment by mpekalski** [comment] 2016-03-10 14:02
I think target is ok. 
```
print(type(target))
print(target.dtype)
<class 'pandas.core.series.Series'>
int64
```
I get this error on v0.5 and after upgrade also on  v0.61.

I will try to make up some example, as I cannot share the original data.

**Comment by josef-pkt** [comment] 2016-03-10 14:12
I was reading too fast, the exception is with exog. Y is your array of explanatory variables exog.

What's `np.asarray(Y).dtype`?
Use asarray because that's the relevant conversion and dtype for the actual calculations

**Comment by mpekalski** [comment] 2016-03-10 14:23
I must have not reload kernel in jupyter notebook after upgrading from 0.5 to 0.61 as now the error is as you wrote

```
ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
```
and answering your question
```
np.asarray(Y).dtype
dtype('O')
```

**Comment by josef-pkt** [comment] 2016-03-10 14:44
Good, that causes the problem.

Currently, we don't and statsmodels doesn't know what to do with object arrays, so we raise an exception. This might or might not change for some objects that could possibly be converted to numeric in a relatively unambiguous way.

As background information: 
What was the column that is of object type? 
Would pandas `to_numeric` (version at least 0.17, AFAICS) do the right thing for your use case?
(It looks like older versions of pandas had `convert_objects` which is deprecated according to http://stackoverflow.com/questions/18434208/pandas-converting-to-numeric-creating-nans-when-necessary )   I never tried either.

**Comment by mpekalski** [comment] 2016-03-10 15:38
I think you should try to check if the types are in int, float and bool. 
If yes then convert bool to int. That solved the problem for me.
After running
```
for x in df.columns:
    if (df[x].dtype == numpy.bool):
        df[x] = df[x].astype(numpy.float64)
```

I did not have any column of type object. 
Before conversion it was
```
set(df.dtypes)
{dtype('bool'), dtype('int64'), dtype('float64')}
```

**Comment by josef-pkt** [comment] 2016-03-29 15:36
closing as not a bug.
We have some open issues to see whether we can convert object arrays to something useable (numeric) that does not require any ambiguous second guessing of the user's intention.

**Closed by josef-pkt** 2016-03-29 15:36 UTC
Labels: comp-base
