### ISSUE TITLE
ARIMAX forecast not equal to linear combination of coefficients/values

### ISSUE THREAD

**Issue by dkori** [statsmodels/statsmodels#7628] opened 2021-08-08 16:14 UTC
#### Describe the bug

My understanding is that when running an ARIMAX model, the prediction generated should be a linear combination of the following after differencing:

- exogenous variable coefficients multiplied by exogenous variable values
- AR coefficients multiplied by appropriate lagged endog values
- MA coefficients multiplied by lagged residuals

Constructing the forecast using the above works when both AR and MA are turned off (order of [0, 1, 0]), but doesn't seem to work when AR or MA are turned on. 

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
import statsmodels.api as sm
# initialize random df
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=['y','x1','x2','x3'])
# set aside last row as prediction set, everything else as train
df_train = df.iloc[0:-1]
df_pred = df.iloc[-1]
# train arima 2,1,2 on df_train
model = sm.tsa.statespace.SARIMAX(df_train['y'],
                                  df_train[['x1','x2','x3']],
                                  #order=[2,1,2],
                                  enforce_stationarity=False,
                                  enforce_invertibility=False)
# generate prediction using exog values for prediction row
predicted_y = model.fit().get_forecast(1, exog = df_pred[['x1','x2','x3']]).predicted_mean.to_list()[0]
# use model parameters to decompose linear contributors to prediction
# find the model coefficients
coef_frame = model.fit().params.reset_index().set_axis(['parameter','coefficient'],axis=1)
# first difference the df to account for ARIMA 1 parameter
df_1st_diff = df - df.shift(1)
# reshape exog vars from last row of 1st diff - these are values prediction should be based on
pred_1st_diff_exog = df_1st_diff.iloc[-1][['x1','x2','x3']].transpose().reset_index().set_axis(['parameter','value'],axis=1)
# merge coefficients with exog variable values used to generate prediction
param_frame = coef_frame.merge(pred_1st_diff_exog,how='left')
# extract residuals for passing to MA
resids = model.fit().resid.to_list()
# extract the ar and ma orders for the given model
ar_order = model.fit().model_orders['ar']
ma_order = model.fit().model_orders['ma']
# gather appropriate values for ar (lagged 1st diff ys) and ma (lagged residuals), plug into param frame values
# iterate through numbers up to ar model order and extract values
for i in range(1,ar_order+1):
    # the ar1 lag should be the the second to last row of first diff frame, cos last row corresponds to
    # to the prediction row
    arlag = df_1st_diff.iloc[0-(i+1)]['y']
    # lag again to get the previous weeks lag value 
    ar_string = 'ar.L'+str(i)
    param_frame.loc[param_frame['parameter']==ar_string,'value'] = arlag
for i in range(1,ma_order+1):
    malag = resids[0-i]
    ma_string = 'ma.L'+str(i)
    param_frame.loc[param_frame['parameter']==ma_string,'value'] = malag
# multiply coefficient by value to get impact of each parameter on prediction
param_frame['impact'] = param_frame['coefficient']*param_frame['value']
# take the sum of all of the impacts used to generate prediction
impact_sum = param_frame['impact'].sum()
# store the last y and the last first differenced y
last_y = df_train['y'].iloc[-1]
last_y_1st_diff = df_1st_diff['y'].iloc[-2]
print('Predicted Y: {0}\nSum of impacts: {1}\nLast Y: {2}\n1st diff of last y: {3}'.format(
predicted_y,impact_sum,last_y,last_y_1st_diff))
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

From the sample above, predicted_y should be equal to last_y + impact_sum. This is only works when running on order [0, 1, 0]. 
#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.8.2.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.12.2 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.4 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/numpy)
scipy: 1.6.3 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/scipy)
pandas: 1.1.4 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/pandas)
    dateutil: 2.8.1 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/dateutil)
patsy: 0.5.1 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.4.2 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 7.19.0 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/IPython)
    jinja2: 2.11.2 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.7.2 (/Users/devrakor/Library/Python/3.8/lib/python/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by ChadFulton** [comment] 2021-08-09 02:42
It looks like you are thinking of a model that looks like:

Δy(t) = b Δx(t) + phi Δy(t-1) + e(t) + theta e(t-1)

But Statsmodels fits regression with ARIMA errors, so that the model is:

y(t) = b x(t) + u(t)
Δu(t) = phi Δu(t-1) + z(t) + theta z(t-1)

These models can be reparameterized into each other, see e.g. [Hyndman's blog](https://robjhyndman.com/hyndsight/arimax/).

A secondary issue is that near the beginning of the sample, `resid` is not the best estimate for the MA error terms z(t), as described [here](https://stats.stackexchange.com/questions/430186/how-statsmodels-predict-ma-process/430274#430274), and so if you use `resid` you will not exactly replicate the forecasts. However, you're forecasting after 100 periods, and this effect is likely to be negligible for your forecasts.

Finally, you should not call `model.fit()` repeatedly, because this call actually performs the model fitting. Instead, you should save the results, e.g. `results = model.fit()`, and then use the results object.

**Comment by ChadFulton** [comment] 2021-08-09 02:42
Closing this question as answered, but feel free to follow up.

**Closed by ChadFulton** 2021-08-09 02:42 UTC
Labels: comp-tsa, question
