### ISSUE TITLE
start_params calculation algo in SARIMAX and ARIMA

### ISSUE THREAD

**Issue by holder-fo** [statsmodels/statsmodels#8554] opened 2022-12-03 03:11 UTC
@ChadFulton sorry, i can't get how start_params is calculated in SARIMAX. could you guide me with the link to source code?
besides, is it same method (hannan_rissanen algo ?) used to calculate the start values in both SARIMAX and ARIMA? 
BTW, is a simple way to get start_params only with any orders?

**Comment by ChadFulton** [comment] 2023-01-13 04:47
Starting parameters for both models are computed using https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/statespace/sarimax.py#L910 (because `ARIMA` is a subclass of `SARIMAX`).

It is approximately the Hannan-Rissanen method.  The thing about starting parameters is that we need to be able to compute them for "any" dataset, even ones that e.g. do not have enough observations for the Hannan-Rissanen method.  As a result, there are a number of special cases, etc.  But it basically uses a conditional-sum-of-squares approach for the exog, trend, AR, and MA components. Starting parameters are not required to e.g. be provably consistent, etc.. We just need them to be generally "close enough" to the optimum that the maximum likelihood estimator can succeed.

> BTW, is a simple way to get start_params only with any orders?

The only way is to create multiple models and check the `start_params` attribute.

Finally, note that you can compute starting parameters in any way that you like, and pass those values to the `fit` method.  For example, if you really want exactly the `hannan_rissanen` estimates as starting parameters, then you can call `fit` with `method='hannan_rissanen'` first to compute them, or you can compute them manually, by loading the estimator function via `from statsmodels.tsa.arima.estimators.hannan_rissanen import hannan_rissanen`.

**Comment by ChadFulton** [comment] 2023-01-13 04:47
Closing as an answered question, but feel free to follow up with additional posts.

**Closed by ChadFulton** 2023-01-13 04:47 UTC
Labels: comp-tsa-statespace, question

**Comment by holder-fo** [comment] 2023-01-13 05:48
@ChadFulton thanks for detailed response!
would you be kind to guide me how to manually compute `start_params` via function `hannan_rissanen` when i need difference or seasonal part?

**Comment by ChadFulton** [comment] 2023-01-14 00:33
If you have a difference, then you would manually difference the data prior to running the Hannan-Rissanen procedure. If you have seasonal lags, one option is to include those lags in the Hannan-Rissanen regressions. Note that `from statsmodels.tsa.arima.estimators.hannan_rissanen` does not support seasonal terms.
