### ISSUE TITLE
Something wrong with coint_johansen or am i doing it wrong?

### ISSUE THREAD

**Issue by favetelinguis** [statsmodels/statsmodels#3855] opened 2017-08-04 06:50 UTC
The question is explanined at:
https://stackoverflow.com/questions/45495471/statsmodels-coint-johansen-wich-cointegration-relations-are-the-strongest

**Comment by josef-pkt** [comment] 2017-08-04 12:59
You should describe a bit the results and what you expect. A runnable example is good, but takes more time (which I don't have this morning)
My guess is that this is a statistics or interpretation question and not a bug or programming question

I don't remember all the details.
You only have one unit root, so you should see only one cointegrating relationship (which is not unique and only identified by some normalizations). 
You could run VECM and check the beta and alpha arrays, which are the cointegrating equations and the adjustment coefficients.

(#3775 I don't know or remember how the pca/cca components d1, d2, d3 or similar should be interpreted.)

**Comment by josef-pkt** [comment] 2017-10-03 23:58
not enough information, closing

**Closed** 2019-07-23 14:09 UTC
Labels: comp-tsa
