### ISSUE TITLE
The regression type is always 'c' for mackinnon p and mackinnon crit regardless of coint regression type.

### ISSUE THREAD

**Issue by jrfc223** [statsmodels/statsmodels#3086] opened 2016-06-28 20:20 UTC
I added print statements to display value of the regression type before mackinnon p, inside mackinnon p, after mackinnon p, inside mackinnon crit, and after mackinnon crit. You can see that changes to regression type in the call to coint are not carried to the mackinnon p and crit functions. 

```
import statsmodels.tsa.stattools as st
>>> st.coint(x, y)
coint 1: c
mackinnon p: c
coint 2: c
mackinnon crit: c
coint 3: c
(-1.7614239700657568, 0.64826351648110636, array([-3.43295071, -2.86268898, -2.56738165]))

>>> st.coint(x, y, regression='nc')
coint 1: nc
mackinnon p: c
coint 2: nc
mackinnon crit: c
coint 3: nc
(-1.7891458878893765, 0.63497921804452351, array([-3.43295071, -2.86268898, -2.56738165]))

>>> st.coint(x, y, regression='ct')
coint 1: ct
mackinnon p: c
coint 2: ct
mackinnon crit: c
coint 3: ct
(-1.7891458878893765, 0.63497921804452351, array([-3.43295071, -2.86268898, -2.56738165]))

import statsmodels
>>> statsmodels.version.full_version
'0.8.0rc1'
```

**Comment by josef-pkt** [comment] 2016-06-28 21:32
(I reformatted description.)

I was hoping we can hide it a bit longer, it's not in the official api and documentation. but I guess it's out of the bag
see #1451

The problem is that I didn't know what the p-values are supposed to be. I was recently looking at the MacKinnon et al paper to figure out what the options are.

R and official Stata only have phillips-ouliaris. And AFAIC or IIRC, the Stata user contributed package uses different tables.
AFAICS, the mackinnon critical values and p-values that are already in statsmodels apply to the `coint` case and depend on the number of variables in the cointegrating vector. I never checked the dependence on constant and trend.

johansen's cointegration test #453 also has confusing options, 5 or 7 options for constant and trend, with and without implied restrictions. (MacKinnon et al for johansen is "no commercial use" license incompatible. #3024 reproduces at some precision the critical-values for the simplest case.)

**Comment by josef-pkt** [comment] 2016-06-28 21:37
see also https://groups.google.com/d/msg/pystatsmodels/YHZoX-vIsLo/eLaHy-2DtKoJ

**Comment by josef-pkt** [comment] 2017-05-27 13:22
I'm closing this #3146 refactoring should make this obsolete

**Closed by josef-pkt** 2017-05-27 13:22 UTC
Labels: comp-tsa, type-bug
