### ISSUE TITLE
predicting new data without using exogenous input of it in SARIMAX

### ISSUE THREAD

**Issue by ncabay** [statsmodels/statsmodels#5467] opened 2019-01-15 06:23 UTC
Hello,

I am trying to train my SARIMAX function with endogenous and exogenous data. My endogenous data is **price** column presented as Y and exogenous data is **totaltx** column presented as X.  Here, to predict Y(t+horizon), I would like to use Y(t-window),...,Y(t) and X(t-window),...X(t). However, I do not want to use X(t+horizon). I am trying to use exogenous regressor for X(t+horizon) instead of using real one.

I have a code snippet but it contains the exogenous values of the predicted values so it is not usable for my intention.

```
while (train_end_index < inputNumber - 1):
        train_end_index = train_start_index + trainLength
        test_start_index = train_end_index
        test_end_index= test_start_index + horizon
        if (filteredData[test_start_index:test_end_index]["day"].values[-1] > 300) and (filteredData[test_start_index:test_end_index]["year"].values[-1] == 2017):
            return predictions, prices
        trainFeatures = filteredData[train_start_index:train_end_index]["totaltx"]
        trainOutput = filteredData[train_start_index:train_end_index]["price"]

        training_arima = sm.tsa.statespace.SARIMAX(endog=trainOutput, exog=trainFeatures, order=(window, 1, 1), trend="ct", initialization='approximate_diffuse')
        training_arima_fit = training_arima.fit(disp=0)

        testFeatures = filteredData[train_start_index:test_end_index]["totaltx"]
        testOutput = filteredData[train_start_index:test_end_index]["price"]

        test_arima = sm.tsa.statespace.SARIMAX(endog=testOutput, exog=testFeatures, order=(window, 1, 1), trend="ct", initialization='approximate_diffuse')
        #res = test_arima.filter(training_arima_fit.params)
        res=test_arima.smooth(training_arima_fit.params)

        predicted = res.predict()[-1:]
        price = filteredData[test_start_index:test_end_index]["price"].values[-1:]

        predictions = np.append(predictions, predicted.values)
        prices = np.append(prices, price)
        train_start_index = train_start_index + 1
    
```
Can you please help me to activate exogenous regressor for arima so I do not need to use X(t+horizon) for the prediction of Y(t+horizon).

Thank you.

**Comment by ChadFulton** [comment] 2019-01-15 23:08
Since you are defining a model with explanatory variables (`exog`), then by definition, the predictions will depend on values of those explanatory variables. In a simplified example, an AR(1) with an exogenous regressor is written:

y(t) = a y(t-1) + b x(t) + e(t)

where y(t) is the output, x(t) is the explanatory variable, and e(t) is a random error term.

So if you want to forecast y(t+1), there's no way to get around the fact that it depends on x(t+1). The easiest thing to do (but not necessarily the best thing to do as far as making a forecast) is use some simple univariate forecasting model for x(t+1). The simplest case would be forecasting x(t+1) using its mean value over the sample (but again, that might be a terrible forecast, depending on what x(t+1) looks like).

**Comment by ChadFulton** [comment] 2019-01-15 23:12
(Note: the formulation I showed there is an ARX model. In Statsmodels, we use a slightly different formulation, "regression with AR errors":

y(t) = b x(t) + eps(t)
eps(t) = a eps(t-1) + e(t)

the reason we use the second formulation is that the parameters are often easier to interpret).

**Comment by josef-pkt** [comment] 2019-01-16 16:40
inheritance is nice
The inherited `from_formula` for exog with spline components in keyword works without changes.
The results are the same as without formula, but we don't get the correct exog_names.

(I thought I had changed the code to create nicer names for the spline components, but I don't find any related committed code.)

```
gam_ccf = GLMGam.from_formula('city_mpg ~ fuel + drive', data=df_autos2, smoother=cc, alpha=(1 / s_scale * sp))
print(gam_ccf.exog_names)
['const', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12']
```

**Comment by josef-pkt** [comment] 2019-01-16 16:46
using pandas DataFrame for splines still does not work

```
x_spline = df_autos2[['weight', 'hp']]
cc = CyclicCubicSplines(x_spline, df=[6, 5], constraints='center')
```
this raises an exception in indexing.
using numpy array `x_spline.values` works and was used in my initial examples.

**Comment by josef-pkt** [comment] 2019-01-16 16:52
last two comments are in the wrong issue/PR (too many open tabs)
I will delete after copying the comments to the right place.

**Comment by NicolaDonelli** [comment] 2019-04-05 10:43
Are the predictions obtained with ARX and "Regressions with AR errors" (which I think is implemented in the statsmodels.regression.linear_model.GLSAR class) the same?
To me they seem different since with ARX you should have y_hat(t+1) = a y(t) + b x(t+1) while with GLSAR you actually have y_hat(t+1) = b x(t+1).

Am I missing something?

**Comment by ChadFulton** [comment] 2019-04-08 00:22
@NicolaDonelli I'm not sure if your question is about those models in general, or about Statsmodels?

If about Statsmodels, then you are correct that `SARIMAX` will not produce the same forecasts as `GLSAR`, because `SARIMAX` will include forecasts of the ARIMA errors component when building the forecast of `y`, while `GLSAR` will only use b x(t+1), as you say.

**Comment by bashtage** [comment] 2019-07-23 12:40
Closing as answered.

**Closed by bashtage** 2019-07-23 12:40 UTC
Labels: comp-tsa
