### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by PLAYER69** [statsmodels/statsmodels#2193] opened 2015-01-19 10:40 UTC
Tried installing statsmodels in pyzo. Getting the following error:

>>> conda install statsmodels
Error: Unsatisfiable package specifications
Hint: the following combinations of packages create a conflict with the
remaining packages:
  - numpy 1.7*
  - statsmodels

Anyone know how I can resolve this?

My version of pyzo is :+1: 
Version info
IEP version: 3.3 (source)
Platform: win32
Python version: 3.3.2
Qt version: 4.8.4
PySide version: 1.2.1

**Comment by PLAYER69** [comment] 2015-01-19 14:38
Tried running statsmodels in anaconda:

import statsmodels.api as sm

getting the following error msg:

>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\krisan\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)
  File "C:/Users/krisan/.spyder2/temp.py", line 12, in <module>
    import statsmodels.api as sm
  File "C:\Users\krisan\Anaconda\lib\site-packages\statsmodels\api.py", line 15, in <module>
    from .tsa import api as tsa
  File "C:\Users\krisan\Anaconda\lib\site-packages\statsmodels\tsa\api.py", line 5, in <module>
    from .vector_ar.var_model import VAR
  File "C:\Users\krisan\Anaconda\lib\site-packages\statsmodels\tsa\vector_ar\var_model.py", line 23, in <module>
    from statsmodels.tools.linalg import logdet_symm
  File "C:\Users\krisan\Anaconda\lib\site-packages\statsmodels\tools\linalg.py", line 23, in <module>
    from scipy.linalg import calc_lwork
ImportError: cannot import name calc_lwork

**Comment by josef-pkt** [comment] 2015-01-19 14:50
This is now another duplicate of #2184

#2191 has a temporary workaround, but scipy 0.15.1 should be on the way.

sorry about this.

**Closed** 2015-01-19 15:26 UTC
