### ISSUE TITLE
PERF: Increase in training size makes prediction slower.

### ISSUE THREAD

**Issue by franchesoni** [statsmodels/statsmodels#5287] opened 2018-10-01 20:00 UTC
I've been working with VARMAX module. 

Trying to use this suggestion [#2788](https://github.com/statsmodels/statsmodels/issues/2788#issuecomment-175209448) I realized that making larger the training set (the set of samples from which I get the params) increases the prediction time when forecasting in a model defined over the series formed by training-test sets.

I've made a notebook reproducing this issue and as a example of what I intend to do. Is this the expected behavior?

The notebook has many questions, all of them I'm interested in. But the important ones are:
I am really doing what I intend? (Is this the correct method?)
How could I make it more efficient? 

the notebook at 
https://github.com/franchesoni/proyectoEPST/blob/master/statsmodels%20issue.ipynb

#2788 @ChadFulton

**Comment by ChadFulton** [comment] 2018-10-01 23:40
Thanks for the report and the replication notebook! For your main question: you are right, a larger dataset does increase prediction / forecasting time.

Technically this is because we perform the Kalman filtering iterations starting at the beginning of the dataset regardless of where prediction starts. You bring up a good point, that we can improve this by using the stored state to only run the filtering iterations for the observations associated with dynamic prediction or forecasting.

For your questions specifically:

> I am really doing what I intend? (Is this the correct method?)

It looks right to me, but I'm not sure what you intend.

> How could I make it more efficient?

For now, the same method that I describe here https://github.com/statsmodels/statsmodels/issues/5226#issuecomment-423020649 would work for you (just don't wait until "later" for the second part :)).

At some point, ideally we'll make an improvement in the `KalmanFilter.predict` library.

(Next questions from your notebook):

> The time that takes 'filter' function is larger than before. Which operations over the data causes this? Isn't it just a kalman filter with given params?

This is not surprising - if you have more data, then filtering (which is a `for` loop over the data) takes longer.

**Comment by franchesoni** [comment] 2018-10-04 20:43
Thanks for the response!

What I intend to do is evaluate the performance of the predictor. That means computing forecasts over different lead times in the test set. With the predictions I can easily get the errors for each lead time (in my actual problem from 1 sample ahead to 24 samples ahead) and calculate the forecasting skill of a VARMAX model. Hope I was clear (if not, let me know).

Now let me see if I got your suggestion right

I  use this variables to control the size of the training set and of the predictions to be made
`n = 4000; samples = 3000` where n is number of samples used of the training set, and samples is the number of moments in which I do some forecasting.

Then I write
```
training_model = sm.tsa.VARMAX(train_set[-n::, :], order=order)
training_fitted = training_model.fit()
```
to "train"

Of the training I need to get
```
params = training_fitted.params
save_state = training_fitted.filter_results.predicted_state[..., -1]
save_state_cov = training_fitted.filter_results.predicted_state_cov[..., -1] 
```
where -1 refers to the last state.

Then use above variables on the predictor over the test set in this way
```
full_model = sm.tsa.VARMAX(test_set[0:samples+lt], order=order)
full_model.inistialize_known(save_state, save_state_cov)
result = full_model.filter(training_fitted.params)
```

And finally
```
predictions = np.empty((lt, samples, 3))
for index in range(samples):
    predictions[:, index, :] = result.predict(start=index, end=index+lt-1, dynamic=True)
```

The reproducible example is in this notebook (old notebook modified):
https://github.com/franchesoni/proyectoEPST/blob/master/statsmodels%20issue2.ipynb

Questions
1 - Is that code above what you were suggesting?
2 - If it is, in the notebook is shown that the results are not exactly the same than when using the whole series, did I make a mistake, is this the expected behavior or something else?
3 - The index -1 implies last state and indexation is ok?
4 - If what I intend to do is clearer now, is this the best way to achieve this?

**Comment by ChadFulton** [comment] 2018-10-05 01:16
> What I intend to do is evaluate the performance of the predictor. That means computing forecasts over different lead times in the test set. With the predictions I can easily get the errors for each lead time (in my actual problem from 1 sample ahead to 24 samples ahead) and calculate the forecasting skill of a VARMAX model. Hope I was clear (if not, let me know).

I'm not sure I understand. Which of the following are you thinking about:

**Case 1**: You're estimating the parameters once on a training set, and then you want to do expanding window, 24-period-ahead forecasts?

e.g. suppose you have you have 1048 observations, and you want to use the first 1000 periods for training.

So first you estimate the parameters using the first 1000 periods, and then:

1. Form forecasts of periods 1001 - 1024 based on the first 1000 periods
2. Form forecasts of periods 1002 - 1025 based on the first 1001 periods

etc?

**Case 2**
You estimating the parameters on an expanding window training set, and then you want to 24-period-ahead forecasts each time?

e.g. suppose you have you have 1048 observations, and you want to use at least 1000 periods for training.

So you would do:

1. Estimate parameters using the first 1000 observations and form forecasts of periods 1001 - 1024
2. Estimate parameters again, now using the first 1001 observations and form forecasts of periods 1002 - 1025

etc?

**Case 3** Or did I misunderstand and you are actually doing something else?

**Comment by franchesoni** [comment] 2018-10-05 13:19
It's case 1 what I intend now.
Case 2 is almost the same, maybe more theoretically consistent, but there's no doubt the computation cost will increase considerably. Is for this reason that I focused on case 1.

Nevertheless, it would be useful, if possible, to compare performances of both methods. But it's not the main objective, it's only something I could try later.

**Comment by franchesoni** [comment] 2018-10-09 16:31
@ChadFulton , Is that code above what you were suggesting if I am in case 1?

Sorry to bother you

**Comment by ChadFulton** [comment] 2018-10-10 04:10
Since you're not re-estimating the parameters, you can just use `dynamic` prediction to cut off the information set you're using to make each prediction. Something like the following should work (I haven't had time to double check it, so you might want to make sure that it's doing what you want it to):

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.signal import lfilter

rs = np.random.RandomState(seed=12345)

endog = pd.Series(
    lfilter([1], [1, -0.95], rs.normal(size=1048)),
    index=pd.PeriodIndex(start='1930', periods=1048, freq='M'))
training = endog.iloc[:1000]
test = endog.iloc[1000:]

mod_train = sm.tsa.SARIMAX(training)
res_train = mod_train.fit()

mod_test = sm.tsa.SARIMAX(test)
mod_test.initialize_known(res_train.predicted_state[..., -1],
                          res_train.predicted_state_cov[..., -1],)
res_test = mod_test.filter(res_train.params)


test_predict = np.zeros((len(test), len(test))) * np.nan
for i in range(len(test)):
    test_predict[i:, i] = res_test.predict(start=i, dynamic=True).values
test_predict = pd.DataFrame(test_predict, index=test.index)
```

**Comment by franchesoni** [comment] 2018-10-10 19:00
Thanks! That solves my problems. I'm pretty sure it's the same than what I wrote [above](https://github.com/statsmodels/statsmodels/issues/5287#issuecomment-427162402). I will write my code like that.

Maybe it's interesting to note that the results are not exactly the same than when using the whole series, as I show in the notebook. Hope this is not a bug. 

Again, thanks for helping (and for the library) :)

**Comment by ChadFulton** [comment] 2018-10-11 00:04
> Thanks! That solves my problems. I'm pretty sure it's the same than what I wrote above. I will write my code like that.

Yes, I didn't get a chance to look back at your code before I posted that, but I think you're right.

> Maybe it's interesting to note that the results are not exactly the same than when using the whole series, as I show in the notebook. Hope this is not a bug.

When I ran your notebook and inspected the differences, the maximum absolute difference in prediction was 5e-10.

The difference here is because once the Kalman filter has converged, we can stop performing certain parts of the recursion to save computational time. However, to check for convergence, we need to run the full recursion at least once.

So in your `full_model2` model, by the time the filter gets to the iteration that corresponds to `test_set[0]`, it has long since converged and is no longer performing the full recursions, whereas in your `full_model`, since `test_set[0]` is the first observation, it has to perform the full recursion for that observation. Only then can it discover that the filter has already converged.

> Again, thanks for helping (and for the library) :)

No problem!

**Comment by mysterious-ben** [comment] 2019-07-18 11:28
Hi, I was working with `statsmodels.tsa.UnobservedComponents` and I had a similar performance issue when I tried to cross-validate the model.

One can cross-validate the model without retraining using `predict` with the option `dynamic=True` but it's still painfully slow for long time series. Basically, Kalman Filter is recreated at every call of `predict` and it iterates through all previous observations. In my case where the data had more than 300'000 observations, each call of `predict` took more then 10 seconds - even though I only needed 10 forecasted values and all intermediate matrices were stored. The current system is very inefficient.

It would be great to have a more efficient way to cross-validate a model!

**Comment by ChadFulton** [comment] 2019-07-18 13:08
This feature is now available for state space models in the development version of Statsmodels via the `extend` method in results objects. See https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_forecasting.html for an example.

This feature will be released in v0.11, but we do not yet have a timeline for that release. In the meantime, if you need this feature you can install the development version of Statsmodels from Github.

**Comment by mysterious-ben** [comment] 2019-07-19 07:33
@ChadFulton Thanks a lot for a quick reply!

I've tried `extend` method in v0.11. Unforgunately, it doesn't solve the issue. To make a forecast, `predict` method calls Kalman filter for every observation in the training set. E.g., to make a one-step ahead forecast with 300'000 training set, Kalman filter is called 300'000 times and then the result is trimmed to the last value. So if I'm cross-validating on the last 100'000 samples, the performance is very poor.

I did not make an explicit benchmark of 'extend' + 'predict' vs. `predict` with `dynamic=True` but I suspect that the former is even slower.

One solution would be to call Kalman filter only for the test samples (for which forecast is needed). I think this is the way Kalman filter is supposed to work; it can be done, although I'm not sure how much effort is required within the current implementation.

**Comment by ChadFulton** [comment] 2019-07-19 11:52
I'm not sure I understand you, but I think the combination of `extend`, `predict`, and `forecast` should allow you to avoid refiltering any observations unnecessarily. Please feel free to post a new issue with code showing what you're doing, and I can take a look.

**Comment by mysterious-ben** [comment] 2019-07-19 14:04
@ChadFulton Please check the code below. I haven't opened the new issue (yet) as I think the current title describes it well. Also, I might be doing something wrong. I actually hope that's the case: then I'll be able to run my cross-validation smoothly after you correct me =)

In short, the time to generate one-step ahead forecast is linearly increasing with the number of observations. I don't believe it should happen. If I'm correct, there is no way to reduce time for cross-validation using `dynamic` or `extend` options.

**Code:**
```python
    from datetime import datetime
    import numpy as np
    import statsmodels.api as sm

    for lib in [np, statsmodels]:
        print(f'{lib.__name__} v{lib.__version__}')

    np.random.seed(42)
    np.set_printoptions(precision=2)

    for complexity_factor in [1, 10, 100]:
        seasonal_1 = np.repeat(np.random.choice(100, 10), 100 * complexity_factor)
        seasonal_2 = np.repeat(np.random.choice(100, 100), 10 * complexity_factor)
        seasonal_3 = np.repeat(np.random.choice(100, 1000), 1 * complexity_factor)
        level = np.array([1] * len(seasonal_1))
        irregular = np.random.normal(0, 5, len(seasonal_1))
        y = level + seasonal_2 + seasonal_2 + seasonal_2 + irregular

        m = sm.tsa.UnobservedComponents(
            endog=y, level=True,
            freq_seasonal=[
                {'period': 10, 'harmonics': 15},  # daily
                {'period': 100, 'harmonics': 3},  # weekly
                {'period': 1000, 'harmonics': 15},  # annualy
            ],
            filter_method=0x10,
            inversion_method=0x01,
            stability_method=0X01,
        )

        print()
        print(f'number of observations = {len(seasonal_1)}')

        timer = datetime.now()
        res: sm.tsa.statespace.MLEResults = m.filter(params=[25]*5)
        print(f'filter time: {datetime.now() - timer}')

        timer = datetime.now()
        x = res.get_forecast(1).predicted_mean
        print(f'one-step ahead forecast time: {datetime.now() - timer} (value = {x})')

        timer = datetime.now()
        x = res.get_prediction(len(y), len(y)).predicted_mean
        print(f'one-step ahead predict time: {datetime.now() - timer} (value = {x})')
```

**Output:**
```
numpy v1.16.4
statsmodels v0.11.0dev0+168.g876dd47f7

number of observations = 1000
filter time: 0:00:01.030759
one-step ahead forecast time: 0:00:00.204412 (value = [171.56])
one-step ahead predict time: 0:00:00.160637 (value = [171.56])

number of observations = 10000
filter time: 0:00:09.608855
one-step ahead forecast time: 0:00:01.723938 (value = [11.8])
one-step ahead predict time: 0:00:01.609647 (value = [11.8])

number of observations = 100000
filter time: 0:01:38.280281
one-step ahead forecast time: 0:00:16.053005 (value = [105.93])
one-step ahead predict time: 0:00:15.839936 (value = [105.93])
```

**Comment by ChadFulton** [comment] 2019-07-20 00:59
Thanks for posting that. Yes you're right, we could and should improve that.

However, if you use `extend`, this slow forecast will only occur for the very first out-of-sample forecast made, and the following ones will be fast.

**Comment by mysterious-ben** [comment] 2019-07-21 13:15
@ChadFulton Thanks for replaying so quickly!

Hmmm, that's not what I see: in the example below prediction time does not change. Am I doing something wrong?

**Code:**
```python
from datetime import datetime
import numpy as np
import statsmodels.api as sm

for lib in [np, statsmodels]:
    print(f'{lib.__name__} v{lib.__version__}')

np.random.seed(42)
np.set_printoptions(precision=2)
n_cv = 3

for complexity_factor in [1, 100]:
    seasonal_1 = np.repeat(np.random.choice(100, 10), 100 * complexity_factor)
    seasonal_2 = np.repeat(np.random.choice(100, 100), 10 * complexity_factor)
    seasonal_3 = np.repeat(np.random.choice(100, 1000), 1 * complexity_factor)
    level = np.array([1] * len(seasonal_1))
    irregular = np.random.normal(0, 5, len(seasonal_1))
    y = level + seasonal_2 + seasonal_2 + seasonal_2 + irregular

    m = sm.tsa.UnobservedComponents(
        endog=y[:-n_cv], level=True,
        freq_seasonal=[
            {'period': 10, 'harmonics': 15},
            {'period': 100, 'harmonics': 3},
            {'period': 1000, 'harmonics': 15},
        ],
        filter_method=0x10,
        inversion_method=0x01,
        stability_method=0X01,
    )

    print()
    print(f'number of observations = {len(y)}')

    timer = datetime.now()
    res: sm.tsa.statespace.MLEResults = m.filter(params=[25]*5)
    print(f'filter time: {datetime.now() - timer}')

    for i in range(len(y)-n_cv, len(y)):
        timer = datetime.now()
        # x = res.get_forecast(1).predicted_mean
        x = res.get_prediction(i, i).predicted_mean
        print(f'<{i}> one-step ahead predict time: {datetime.now() - timer} (value = {x})')

        timer = datetime.now()
        res.extend(y[[i]])
        print(f'<{i}> extend time: {datetime.now() - timer} (value = {x})')
```

**Output:**
```
numpy v1.16.4
statsmodels v0.11.0dev0+168.g876dd47f7

number of observations = 1000
filter time: 0:00:00.776752
<997> one-step ahead predict time: 0:00:00.157607 (value = [202.31])
<997> extend time: 0:00:00.007581 (value = [202.31])
<998> one-step ahead predict time: 0:00:00.147576 (value = [197.37])
<998> extend time: 0:00:00.007202 (value = [197.37])
<999> one-step ahead predict time: 0:00:00.147370 (value = [204.73])
<999> extend time: 0:00:00.007154 (value = [204.73])

number of observations = 100000
filter time: 0:01:13.822639
<99997> one-step ahead predict time: 0:00:14.287605 (value = [6.52])
<99997> extend time: 0:00:00.013507 (value = [6.52])
<99998> one-step ahead predict time: 0:00:13.681755 (value = [14.79])
<99998> extend time: 0:00:00.006416 (value = [14.79])
<99999> one-step ahead predict time: 0:00:13.722140 (value = [13.88])
<99999> extend time: 0:00:00.005852 (value = [13.88])
```

**Comment by ChadFulton** [comment] 2019-07-21 14:42
The problem is that `extend` returns a new results object, it does not mutate the current results object. One option would be to modify your loop this way:

```python
    # Cross-validate the model
    forecast_res = res
    for i in range(len(y)-n_cv, len(y)):
        timer = datetime.now()
        # x = forecast_res.get_forecast(1).predicted_mean
        x = forecast_res.get_prediction(i, i).predicted_mean
        print(f'<{i}> one-step ahead predict time: {datetime.now() - timer} (value = {x})')

        timer = datetime.now()
        forecast_res = forecast_res.extend(y[[i]])
        print(f'<{i}> extend time: {datetime.now() - timer} (value = {x})')
```

**Comment by mysterious-ben** [comment] 2019-07-22 07:41
@ChadFulton Of course, my bad! You are correct, I forgot to assign
```python
res = res.extend(y[[i]])
```

Eventually, a combination of `extend` and `get_forecast` worked for my cross-validation purpuses. Which is great, big thanks for helping to sort it out!

Altough it works as it is, in my opinion, a couple of things could be improved:

1. `get_forecast` and `get_prediction` methods are increadibly slow for long time series. The cause is a loop that iterates through all the samples - no matter what forecasts are requested by the user. You can search for `next(kfilter)` in `_predict` function to understand what I'm talking about. `extend` helps to sidestep this issue but... (see point 3 below)

2. `append` method is slow. I did not check why exactly but it certainly is. It's fine if one needs to make a one-off extension of an existing time series. However, for cross-validation this method just won't work. `extend` is much faster but... (see point 3 below)

3. `extend` method will return an object that only has results for the new points. Basically, it sidesteps performance issues for long time series by only saving the new points. Which is okay but it makes some things less consistent. For example, `self.nobs` of the returned object equals to the number of the new points. Thus, the code below won't return a 1-step ahead prediction as one could expect: 

```python
m = sm.tsa.UnobservedComponents(np.arange(1000))
res = m.fit()
res = res.extend(y[[i]])
x = res.get_prediction(1000, 1000).predicted_mean
print(x)
```

One possible solution would be to increase performance of `get_prediction` and `append` methods but cutting redundant iterations and (possbily?) an overhead of object re-creation.

In any case, I think that this is a great package for state space models. I'm really glad that you keep working on it!

**Comment by ChadFulton** [comment] 2019-07-22 22:53
> get_forecast and get_prediction methods are increadibly slow for long time series. The cause is a loop that iterates through all the samples - no matter what forecasts are requested by the user. You can search for next(kfilter) in _predict function to understand what I'm talking about. extend helps to sidestep this issue but... (see point 3 below)

Yes, this is the part that we talked about before that can and should be fixed.

> append method is slow. I did not check why exactly but it certainly is. It's fine if one needs to make a one-off extension of an existing time series. However, for cross-validation this method just won't work. extend is much faster but... (see point 3 below)

Yes, this is true, right now `append` is simply a convenience method and is not designed to improve performance.  Ideally we would rewrite this so that it is almost as fast as `extend`, but that will be somewhat time consuming to do.

> extend method will return an object that only has results for the new points. Basically, it sidesteps performance issues for long time series by only saving the new points. Which is okay but it makes some things less consistent. For example, self.nobs of the returned object equals to the number of the new points.

Yes, you're totally correct, that is the current tradeoff that is being made.

> One possible solution would be to increase performance of get_prediction and append methods but cutting redundant iterations and (possbily?) an overhead of object re-creation.

Improving `get_prediction` should be straightforward, while improving `append` will unfortunately not be (this is because we have to support more use cases than simply forecasting / cross-validation, e.g. smoothing).

**Comment by mysterious-ben** [comment] 2019-07-23 08:09
Yes, that makes sense. Also, I think that if performance of `get_prediction` is improved, one will be able to efficiently cross-validate using `get_prediction` with `dynamic=True` option. In my opinion, it would be more convient than using `extend` because all attributes and indexing of the original model are preserved.

**Comment by ChadFulton** [comment] 2019-08-02 21:58
Relevant to this issue: #6064 will improve `get_prediction` performance in the case of long time series.

**Comment by ChadFulton** [comment] 2019-08-05 01:25
I am going to close this as the original issue has been resolved (increase in training size makes out of sample forecasting slower). Still there is clearly a ways to go on improving performance; e.g. in `append` case.

**Closed by ChadFulton** 2019-08-05 01:25 UTC
Labels: Performance, comp-tsa, comp-tsa-statespace
