### ISSUE TITLE
Unable to fit ARIMA?

### ISSUE THREAD

**Issue by amueller** [statsmodels/statsmodels#3620] opened 2017-04-23 21:48 UTC
I've been trying to fit an ARIMA model to the Mauna loa dataset.
There is a write-up here:
http://marcharper.codes/2016-07-26/Mauna+Loa.html

However, trying to reproduce this I get
> ValueError: The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.

I'm no ARIMA expert but I would expect this to work.
Also, as this data has a periodicity of 12, I would expect it to require a lag of 12. I tried to fit a model with lag 12, but that never finished. Is that expected?

**Comment by amueller** [comment] 2017-04-23 21:52
Oh, steps to reproduce:
```python
import pandas as pd
columns = ["year", "month", "decimal date", "average", "interpolated", "trend", "?"]
co2 = pd.read_csv("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt",
                  delim_whitespace=True, skiprows=72, names=columns, parse_dates=[[0, 1]])
co2.set_index("year_month", inplace=True)
ppm = co2.interpolated
from statsmodels import tsa
arima_model = tsa.arima_model.ARIMA(ppm, order=(2, 1, 2))
res = arima_model.fit()
```

Setting the last entry of "order" to 0 doesn't yield the error, but yields a stationary model (it's not clear to me why that is)

**Comment by josef-pkt** [comment] 2017-04-23 21:59
general recommendation: try SARIMAX, it can handle seasonal ARMA models and is currently better maintained.

Does the old notebook reproduce, or does this mean that it doesn't work with the current statsmodels version?

> Setting the last entry of "order" to 0 doesn't yield the error, but yields a stationary model (it's not clear to me why that is)

If there is differencing, then the model will be integrated (not stationary in levels), but predict or forecast has a `typ='level'` keyword options to get the prediction in terms of level instead of differences.

**Comment by amueller** [comment] 2017-04-23 22:06
Thanks!

The old notebook doesn't reproduce anymore, it doesn't say which version of statsmodels it ran with, I think. I'm using 0.8.

**Comment by amueller** [comment] 2017-04-23 22:08
I tried again with order=(12, 1, 0) and I get
> /home/andy/anaconda3/lib/python3.5/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals

I haven't found documentation of that.

**Comment by amueller** [comment] 2017-04-23 22:09
I wanted to discuss ARIMA in class, SARIMAX is much more complex, I don't think I can do that. plain AR works fairly well on the problem, though.

**Comment by josef-pkt** [comment] 2017-04-23 23:47
I just ran the unchanged notebook from https://github.com/marcharper/marcharper.codes/tree/master/2016-07-26 with current statsmodels master and I get the same results without exception (but different warning, usage warning but no deprecation warning)

I haven't tried anything else yet, nor looked at the details.

**Comment by amueller** [comment] 2017-04-24 01:00
Thanks. Well I might give it a go with master again then.

**Comment by josef-pkt** [comment] 2017-04-24 01:13
statsmodels 0.8 has a new option because start_params computation is still fragile.

You could try to set in ARIMA fit `start_ar_lags` to 13 or something 2 * max(ar_order, ma_order), and see if that works for you. http://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.fit.html

**Comment by stellarkey** [comment] 2019-05-03 23:20
> 
> 
> statsmodels 0.8 has a new option because start_params computation is still fragile.
> 
> You could try to set in ARIMA fit `start_ar_lags` to 13 or something 2 * max(ar_order, ma_order), and see if that works for you. http://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.fit.html

That amazingly worked.

**Comment by KarthikMgk** [comment] 2019-05-11 19:26
> statsmodels 0.8 has a new option because start_params computation is still fragile.
> 
> You could try to set in ARIMA fit `start_ar_lags` to 13 or something 2 * max(ar_order, ma_order), and see if that works for you.

Even though this did not solve the problem, but it improved my AIC Score. Thanks

**Comment by bashtage** [comment] 2019-07-22 22:52
Closing as answered.

**Closed by bashtage** 2019-07-22 22:52 UTC

**Comment by thesofakillers** [comment] 2020-11-07 09:44
Hi, the [statsmodels.tsa.arima_model.ARIMA](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA) model, whose `fit` function implements the `start_ar_lags` parameter discussed above as a solution is deprecated. The [current ARIMA model](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima.model.ARIMA.html)'s `fit` function does not provide this parameter, yet I'm still getting `ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals` errors for many of my ARIMA models. Any idea how to fix this issue?

**Comment by bashtage** [comment] 2020-11-11 09:03
You are probably fitting a model that is poorly identified.  This `start_ar_lags` has been removed since the starting value generation code has been substantially improved and uses more sophisticated methods.

**Comment by thesofakillers** [comment] 2020-11-11 13:10
@bashtage, thank you for the response. I should note that this was happening the vast majority of the time. I ran a grid search on 56 different models with maximum p and q parameters of around 12, and less than 10 of these models converged. Perhaps as you say it has something to do with my data being hard to identify. 

I should note that passing the argument `method='innovations_mle'` diminished the issue, for anyone who is running into something similar
