### ISSUE TITLE
Documentation outages

### ISSUE THREAD

**Issue by surchs** [statsmodels/statsmodels#2544] opened 2015-07-16 15:52 UTC
Hi,

just want to make sure you guys are aware that the docs are frequently unavailable. Aside from the #2450 Ublock issues there seems to be a more general downtime issue of the [statsmodels.sourceforge.net](http://statsmodels.sourceforge.net/) domain.

Are there any plans to migrate to something more reliable?

**Comment by ChadFulton** [comment] 2015-07-16 17:51
Down for me right now too.

**Comment by josef-pkt** [comment] 2015-07-16 18:06
https://mobile.twitter.com/sfnet_ops?lang=en
Looks like it happens once every few days

**Comment by josef-pkt** [comment] 2015-07-17 08:59
looks like 18 hours of outage so far. I guess we have to look sooner for an alternative than I thought.

**Comment by sieben** [comment] 2015-07-17 12:54
Maybe moving to https://readthedocs.org/ would be a nice idea. Sourceforge seems to be on its way to the graveyard.

**Comment by kiyoto** [comment] 2015-07-17 22:07
I'd be happy to help w/ the migration to readthedocs. :+1:

**Comment by josef-pkt** [comment] 2015-07-17 22:19
I tried to read a bit about readthedocs, but didn't get very far.
Most likely the easier alternative is github and github pages. 
readthedocs might require more adjustments to the doc build process before it rtd will be able to build it.

(I'm travelling tomorrow but I would like to spend some time on this next week.)
It would be helpful if you, or someone, can figure out what the requirements for readthedocs are. Based on a search there seems to have been an attempt to add statsmodels but the build failed. Our build script includes several custom extras, and building the documentation with rtd requires to install all our dependencies, AFAIU.

**Comment by njsmith** [comment] 2015-07-19 06:43
Possibly useful reference -- matplotlib's .travis.yml has code to automatically build and push the development version of the docs to github pages on every commit: https://github.com/matplotlib/matplotlib/blob/master/.travis.yml

They go to a dedicated "devdocs" repository, which ends up available here:
http://matplotlib.org/devdocs/

**Comment by josef-pkt** [comment] 2015-07-19 07:10
@njsmith Thanks for the information 

It looks like matplotlib found a way to limit when the documentation is build, so it doesn't rebuild with each pull request push:

https://github.com/matplotlib/matplotlib/blob/master/.travis.yml#L135
`if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'matplotlib/matplotlib' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then`

**Comment by josef-pkt** [comment] 2015-07-19 07:25
Given the sourceforge outage we need a quick solution. Any permanent solution that requires evaluating and trying out different options can or should wait.

It would be very helpful If someone can take the lead on this or provide detailed proposals and instructions.

(i have one more week with relatively good internet time before I go mostly offline for a week. And I will need most of my time to keep up or catch up with GSOC and code maintenance.)

My guess is that just copying all the hml docs to a github pages repo will be the fastest way for the "quickfix".

**Comment by sieben** [comment] 2015-07-19 12:50
I've tried to build up the documentation but there is no readme about the
dependencies for doing so.
For instance I get this kind of errors:

$ make html
# generate the examples rst files
Generating reST from examples folder
#../tools/examples_rst.py
Generating notebooks from examples/notebooks folder
../tools/nbgenerate.py
Traceback (most recent call last):
  File "../tools/nbgenerate.py", line 25, in <module>
    from IPython.zmq.blockingkernelmanager import (BlockingKernelManager as
ImportError: No module named zmq.blockingkernelmanager

Before finding solution it would be a good idea to know what are the
dependencies for building documentation.

Le dim. 19 juil. 2015 à 09:26, Josef Perktold <notifications@github.com> a
écrit :

**Comment by josef-pkt** [comment] 2015-07-19 13:05
I think it's only ipython and it's dependencies  (that includes zmq and mathjax or ???) for building notebooks (nbconvert) that is specifically required for building the documentation.

matplotlib is required for the doc build and optional for the plot and graphics functions in statsmodels itself.
I guess that the math rendering still requires a latex program to be on the system path.

see optional dependencies at the bottom here
https://github.com/statsmodels/statsmodels/blob/4b55fa4871cf3f1dbd2e30bfe00d80df87d4b340/docs/source/install.rst


Related: because I often have problems with building notebook examples, I often have it disabled (or is disabled by default in Windows make.bat ?), so I can build just the sphinx docs without extra notebook examples.

Another problem is that some generated documentation files only differ in capitalization, and I have a few warnings and missing files on Windows which doesn't have a case sensitive file system.

**Comment by sieben** [comment] 2015-07-19 17:33
I don't think so I use ipython last version with python zmq and it still
doesn't work.

AttributeError: 'ZMQSocketChannel' object has no attribute 'execute'
Exception AttributeError: "NotebookRunner instance has no attribute 'kc'"
in <bound method NotebookRunner.__del__ of <__main__.NotebookRunner
instance at 0x2b827c349a28>> ignored

Do you have hints on what could be wrong ? I've install both ipython and
zmq with :
pip install --user --upgrade "ipython[all]" pyzmq

A good start would be to include in the .travis.yml a task to build the
documentation no matter what is the solution coming after (readthedocs, or
github pages) the docs needs to be reproductible with the build.

Le dim. 19 juil. 2015 à 15:05, Josef Perktold <notifications@github.com> a
écrit :

**Comment by sieben** [comment] 2015-07-20 13:21
https://github.com/scikit-learn/scikit-learn/issues/4993

**Comment by TomAugspurger** [comment] 2015-07-20 13:45
Should be able to copy https://github.com/scikit-learn/scikit-learn.github.io pretty much.

@josef-pkt I've built the HTML docs, notebooks are trickier. Had to install IPython 0.13.2, but that relies on an old version of libzmq, which is trickier. It may be easier to update the nbgenerate code to work with recent versions of IPython.

What else do you need to make the switch? We should be able to upload the HTML files right now, I think. If you or @jseabold makes a `statsmodels.github.io` repository, I can submit a PR with the HTML docs, and we'll worry about the notebooks later.

**Comment by jseabold** [comment] 2015-07-20 15:09
You're going to need an older version of IPython ~(1.x) to build the docs.
I got them building with newer IPython last week, but haven't done a PR.
Path of least resistance is just to take the existing docs on SF and throw
them into the website github repo, assuming we can at least rsync from
sourceforge.

I'm moving across the country this weekend and won't be available to help
for at least a few weeks.

https://github.com/jseabold/statsmodels/tree/update-nbgen

**Comment by josef-pkt** [comment] 2015-07-20 16:59
This morning (France time) I tried to ftp into sourceforge but it didn't work. (but I haven't tried in a while and I'm also not sure the saved password is still correct.)

**Comment by sieben** [comment] 2015-07-20 17:30
If somebody can give me a built doc I can offer to host them on my server.

Le lun. 20 juil. 2015 18:59, Josef Perktold <notifications@github.com> a
écrit :

**Comment by TomAugspurger** [comment] 2015-07-20 17:36
@jseabold thanks skipper, I pulled your branch, building now (hopefully I have my LaTex issues sorted out).

**Comment by jseabold** [comment] 2015-07-20 17:45
Also, https://github.com/statsmodels/statsmodels-website

**Comment by jseabold** [comment] 2015-07-20 17:46
That's just our landing page for now, but the docs could live there too.

**Comment by TomAugspurger** [comment] 2015-07-20 18:37
Ok http://statsmodels.github.io/dev/ has the development documentation.

I'll try to get the stable updated sometime tonight. I think I can point statsmodels.github.io to the dev docs for now, and then point them to stable once I get those uploaded.

**Comment by josef-pkt** [comment] 2015-07-20 18:39
Very good, thanks Tom

**Comment by TomAugspurger** [comment] 2015-07-20 19:08
Not all the notebooks came out correctly. e.g. http://statsmodels.github.io/dev/examples/notebooks/generated/wls.html The input and output may be off by one? No time to look right now though.

**Comment by ChadFulton** [comment] 2015-07-20 19:33
Also I notice the plots aren't showing up yet.

Good to see the docs again (and especially for the dev version, which I
don't think were ever available), thanks!

**Comment by TomAugspurger** [comment] 2015-07-21 00:13
http://statsmodels.github.io/  now points to stable.

- The repo for the site is here http://github.com/statsmodels/statsmodels.github.io
- I built the stable docs from this branch: https://github.com/TomAugspurger/statsmodels/tree/nbgen-0.6.1. It's just the 0.6.1 release with Skipper's changes to the doc generation rebased on top.
- The dev docs were built with https://github.com/TomAugspurger/statsmodels/tree/nbgen

Should we change the links in the README to point to the github.io site, at least for now?

**Comment by p3trus** [comment] 2015-07-22 15:39
Is there a way to get the latest nightly builds for windows?

**Comment by sieben** [comment] 2015-07-22 15:42
It would probably be a good idea to update the link that is given on https://github.com/statsmodels/statsmodels to the new website

**Comment by TomAugspurger** [comment] 2015-07-22 15:45
@sieben agreed. I'd favor a permanent move away from sourceforge.  Whether to github pages or elsewhere doesn't really matter. But I think that's up to @josef-pkt . The documentation itself also contains links to source forge that would need to be scrubbed.

**Comment by TomAugspurger** [comment] 2015-07-22 15:47
@p3trus, http://statsmodels.github.io/dev/ has the version I built a few days ago. I'm not sure what statsmodels' nightly build process is like. pandas builds our docs and uploads them as part of our Travis build.

**Comment by jseabold** [comment] 2015-07-22 15:53
Our nightly builds so far are boxes in my house, which I've been away from
for a while and don't have reliable remote access. The nightly build box
for the docs has been down for a while. The link for nightly builds for
windows binaries for the package is also down with sourceforge (and this
box is out of commission temporarily, anyway).

I'm going to switch all of this infrastructure stuff to another solution in
the coming weeks, unless someone beats me to it.

**Comment by TomAugspurger** [comment] 2015-07-22 15:55
@jseabold Are you ok with changing the link in the README to point to http://statsmodels.github.io?

**Comment by josef-pkt** [comment] 2015-07-22 16:11
@TomAugspurger   I just prepared the change for the Readme.test, but I have to bet busy with family again. I need to run, If you want to prepare a PR, the following is what I started to put on top of the readme so it's very visible.

```
Change in Location of Documentation
===================================

Due to the current outage of our online documentation, we recreated the
documentation on github.

The documentation for the latest release is at

   http://statsmodels.github.io/stable/index.html

The documentation for the development version is at

   http://statsmodels.github.io/dev/index.html


This is currently a temporary solution that will be transformed into the new permanent location.
```

**Comment by josef-pkt** [comment] 2015-07-22 18:11
Before we announce a permanent solution, with reliable permanent links, I have one more question and issue.

We could use as the main domain for the documentation the `statsmodels.org` domain. I have been paying for it and parking it for several years.
This would be a good opportunity to activate `statsmodels.org` similar to other packages, but we would need a solution that doesn't cost **me** anything or much and without having to give away the domain.

Does anyone know what the options are?
I only paid minimal attention when scikit-learn opened `http://scikit-learn.org/` with redirecting to the documentation server.

**Comment by jseabold** [comment] 2015-07-22 20:26
I pay hover.com a $12/year for my personal domain. scikit-learn registered
on gandi.net and uses rackspace cloud for management.

**Comment by kiyoto** [comment] 2015-07-22 20:40
@josef-pkt I might be able to convince my employer to pay for hosting if we can add a little blurb like "hosting provided by Treasure Data" or something. Up for it?

**Comment by josef-pkt** [comment] 2015-07-22 21:12
@kiyoto Thanks for the offer, but not yet.
My guess is that we can keep the github hosting but just need the statsmodels.org name server or redirection or whatever.  I just have problems to understand what the relevant instructions imply, and what the DNS, CNAME, ... lingo is all about. I might even have it for free with my registrar (https://www.gkg.net/dnszone/buy) but I don't understand the ;arge print (small print which is printed in regular sized letters).

(Reading about nonparametric confidence intervals is more fun.)

**Comment by jseabold** [comment] 2015-07-22 21:36
It looks like they provide hosting for free. We'll need to add a CNAME to
the repo and you'll need to configure things on your end.

https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/

**Comment by sieben** [comment] 2015-08-14 11:58
What about a definitive move ? statsmodels.org is not easily found by google right now. I think linking to it from the github.com page would help rise it to the top of the search page.

**Comment by josef-pkt** [comment] 2017-10-04 13:53
I think this is all resolved. We have www.statsmodels.org and sourceforge redirects. Google search provides the correct links

**Closed by josef-pkt** 2017-10-04 13:53 UTC
