### ISSUE TITLE
BUG: add_constant considers column of zeros a legitimate constants column.

### ISSUE THREAD

**Issue by komarkdev** [statsmodels/statsmodels#2702] opened 2015-11-09 22:00 UTC
tools.tools.add_constant   checks whether a column of constants already exists in which case it returns the data as is.  However, this check is done through var function, and data will be returned as is even if the const column is the column of zeros. Column of zeros is not a good const column for the purposes of regression.  Code snippet with the problem is below. 

P.S. It could be convenient to also add a flag to skip the check above at all. Otherwise  the shape of the returned array may be different from run to run and this may need handling. (this is how this bug was found though...)

code:

if not data.dtype.names:
        var0 = data.var(0) == 0
        if np.any(var0):
            return data

**Comment by josef-pkt** [comment] 2015-11-09 22:30
duplicate of #2659   proposed fix in #2665

closing as duplicate @komarkdev  Please add any comments to the above issue or PR, Thanks

**Closed** 2015-11-09 22:30 UTC
