### ISSUE TITLE
Confusion regarding the smf module

### ISSUE THREAD

**Issue by dsaxton** [statsmodels/statsmodels#4947] opened 2018-08-21 01:49 UTC
This code works fine as expected:

```python
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

n = 100
data = pd.DataFrame({"y": np.random.poisson(lam=1, size=n), 
                     "x": np.random.randn(n)})

result = smf.poisson("y ~ x", data).fit()
result.summary()
```

The problem happens when the user mistakenly tries to use the `Poisson` class (which doesn't use the formula syntax, yet it is imported within the module nonetheless and will even autocomplete if the user makes the mistake of capitalizing the P) within the `smf` class as below,

```python
result = smf.Poisson("y ~ x", data).fit()
result.summary()
```

It is very easy to make this mistake and the resulting error message is quite cryptic, so I am wondering if there is a way to fix this.  It seems that the `smf` module should not directly expose those classes that don't follow the formula syntax.

**Comment by josef-pkt** [comment] 2018-08-21 01:53
this got lost #833
we just need `del xxx` to remove the original classes from the namespace

**Comment by dsaxton** [comment] 2018-08-21 02:13
@josef-pkt I created a pull request for this.  I think it went through, although I'm seeing some git weirdness locally.

**Comment by bashtage** [comment] 2018-08-21 07:07
No need for del.  Just use `__all__` which is the standard method to limit namespace.

**Comment by josef-pkt** [comment] 2018-08-21 12:17
`__all__` still leaves the classes in the name space and is not enough.
`__all__` works for `from xxx import *` and a few other things.

**Comment by josef-pkt** [comment] 2018-08-21 21:05
I'm closing this as duplicate of #833

**Closed by josef-pkt** 2018-08-21 21:05 UTC
