### ISSUE TITLE
check for the lag order with model.select_order()

### ISSUE THREAD

**Issue by 3chrzaszcze** [statsmodels/statsmodels#2655] opened 2015-10-13 16:20 UTC
Hi,

I want check for the lag order to determine the maximum lag length for the Granger causality analysis  via model.select_order() but i get an error:

"TypeError: correlate() got an unexpected keyword argument 'old_behavior'"

Thanks in advance for any help!

Here is a code:

ar = statsmodels.tsa.ar_model.AR(display_list2)
ar.select_order(15,'bic')

And the message:

  File "file.py", line 22, in <module>
    ar.select_order(15,'bic')
  File "c:\Python27\lib\site-packages\statsmodels\tsa\ar_model.py", line 435, in
 select_order
    maxiter=100, disp=0)
  File "c:\Python27\lib\site-packages\statsmodels\tsa\ar_model.py", line 580, in
 fit
    callback=callback, **kwargs)
  File "c:\Python27\lib\site-packages\statsmodels\base\model.py", line 425, in f
it
    full_output=full_output)
  File "c:\Python27\lib\site-packages\statsmodels\base\optimizer.py", line 184,
in _fit
    hess=hessian)
  File "c:\Python27\lib\site-packages\statsmodels\base\optimizer.py", line 382,
in _fit_lbfgs
    **extra_kwargs)
  File "c:\Python27\lib\site-packages\scipy\optimize\lbfgsb.py", line 188, in fm
in_l_bfgs_b
    **opts)
  File "c:\Python27\lib\site-packages\scipy\optimize\lbfgsb.py", line 320, in _m
inimize_lbfgsb
    f, g = func_and_grad(x)
  File "c:\Python27\lib\site-packages\scipy\optimize\lbfgsb.py", line 266, in fu
nc_and_grad
    f = fun(x, *args)
  File "c:\Python27\lib\site-packages\scipy\optimize\optimize.py", line 285, in
function_wrapper
    return function(*(wrapper_args + args))
  File "c:\Python27\lib\site-packages\statsmodels\base\model.py", line 403, in <
lambda>
    f = lambda params, *args: -self.loglike(params, *args) / nobs
  File "c:\Python27\lib\site-packages\statsmodels\tsa\ar_model.py", line 353, in
 loglike
    return self._loglike_mle(params)
  File "c:\Python27\lib\site-packages\statsmodels\tsa\ar_model.py", line 303, in
 _loglike_mle
    Vpinv = self._presample_varcov(params)
  File "c:\Python27\lib\site-packages\statsmodels\tsa\ar_model.py", line 260, in
 _presample_varcov
    old_behavior=False)[:-1]
TypeError: correlate() got an unexpected keyword argument 'old_behavior'

**Comment by jaimeblasco** [comment] 2015-10-21 00:51
Same here when calling ar_model.fit(maxlag=9, method='mle', disp=-1)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-178-039bc2f245d6> in <module>()
----> 1 pandas_ar_res = ar_model.fit(maxlag=9, method='mle', disp=-1)

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/tsa/ar_model.pyc in fit(self, maxlag, method, ic, trend, transparams, start_params, solver, maxiter, full_output, disp, callback, **kwargs)
    578                                          method=solver, maxiter=maxiter,
    579                                          full_output=full_output, disp=disp,
--> 580                                          callback=callback, **kwargs)
    581 
    582             params = mlefit.params

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/base/model.pyc in fit(self, start_params, method, maxiter, full_output, disp, fargs, callback, retall, skip_hessian, **kwargs)
    423                                                        callback=callback,
    424                                                        retall=retall,
--> 425                                                        full_output=full_output)
    426 
    427         #NOTE: this is for fit_regularized and should be generalized

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/base/optimizer.pyc in _fit(self, objective, gradient, start_params, fargs, kwargs, hessian, method, maxiter, full_output, disp, callback, retall)
    182                             disp=disp, maxiter=maxiter, callback=callback,
    183                             retall=retall, full_output=full_output,
--> 184                             hess=hessian)
    185 
    186         # this is stupid TODO: just change this to something sane

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/base/optimizer.pyc in _fit_lbfgs(f, score, start_params, fargs, kwargs, disp, maxiter, callback, retall, full_output, hess)
    380                                          callback=callback, args=fargs,
    381                                          bounds=bounds, disp=disp,
--> 382                                          **extra_kwargs)
    383 
    384     if full_output:

/Users/jaime/anaconda/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback)
    186 
    187     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
--> 188                            **opts)
    189     d = {'grad': res['jac'],
    190          'task': res['message'],

/Users/jaime/anaconda/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, **unknown_options)
    318                 # minimization routine wants f and g at the current x
    319                 # Overwrite f and g:
--> 320                 f, g = func_and_grad(x)
    321         elif task_str.startswith(b'NEW_X'):
    322             # new iteration

/Users/jaime/anaconda/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in func_and_grad(x)
    264     if jac is None:
    265         def func_and_grad(x):
--> 266             f = fun(x, *args)
    267             g = _approx_fprime_helper(x, fun, epsilon, args=args, f0=f)
    268             return f, g

/Users/jaime/anaconda/lib/python2.7/site-packages/scipy/optimize/optimize.pyc in function_wrapper(*wrapper_args)
    283     def function_wrapper(*wrapper_args):
    284         ncalls[0] += 1
--> 285         return function(*(wrapper_args + args))
    286 
    287     return ncalls, function_wrapper

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/base/model.pyc in <lambda>(params, *args)
    401 
    402         nobs = self.endog.shape[0]
--> 403         f = lambda params, *args: -self.loglike(params, *args) / nobs
    404         score = lambda params: -self.score(params) / nobs
    405         try:

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/tsa/ar_model.pyc in loglike(self, params)
    351 
    352         else:
--> 353             return self._loglike_mle(params)
    354 
    355     def score(self, params):

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/tsa/ar_model.pyc in _loglike_mle(self, params)
    301 
    302         # get inv(Vp) Hamilton 5.3.7
--> 303         Vpinv = self._presample_varcov(params)
    304 
    305         diffpVpinv = np.dot(np.dot(diffp.T, Vpinv), diffp).item()

/Users/jaime/anaconda/lib/python2.7/site-packages/statsmodels/tsa/ar_model.pyc in _presample_varcov(self, params)
    258         for i in range(1, p1):
    259             Vpinv[i-1, i-1:] = np.correlate(params0, params0[:i],
--> 260                                             old_behavior=False)[:-1]
    261             Vpinv[i-1, i-1:] -= np.correlate(params0[-i:], params0,
    262                                              old_behavior=False)[:-1]

TypeError: correlate() got an unexpected keyword argument 'old_behavior'

**Comment by kernc** [comment] 2016-05-05 21:26
Duplicate of https://github.com/statsmodels/statsmodels/issues/2667, fixed in https://github.com/statsmodels/statsmodels/pull/2675.

**Comment by josef-pkt** [comment] 2016-05-05 21:41
Thanks for finding, closing

**Closed by josef-pkt** 2016-05-05 21:41 UTC
