### ISSUE TITLE
Documentation on marginal effects?

### ISSUE THREAD

**Issue by dpavlic** [statsmodels/statsmodels#2767] opened 2016-01-16 18:06 UTC
Hello, and plase forgive me if I just haven't looked quite hard enough, but I am trying to run a logit regression; after that I get the (overall, dydx) marginal effects.  The estimates I get are somewhat different then when I use Stata's margins.  I can provide an example, but I of course do not know if the simple answer is that the effects are somewhat differently calculated between the statsmodels and Stata's implementation?

**Comment by josef-pkt** [comment] 2016-01-16 18:37
I never really compared the details with Stata on any examples. Skipper @jseabold  did all the work, but is most likely to busy to look into this.

If you can provide the example and discrepancy to Stata, then I can also look into it.

AFAIK, our margins are closely modeled after those in Stata and I thought they should produce the same results (except possibly corner cases, and missing functionality). I was reading the Stata documentation as documentation for our version.

My first check in cases like this is to look at the test suite and see whether there is anything similar to the example or usecase. In some cases we do use different definitions or small sample corrections compared to Stata, and the test suite has comments about this in several cases. 
But I'm not aware of any discrepancy, (which doesn't mean that there are none, because I never checked).

**Comment by jseabold** [comment] 2016-01-16 19:17
Indeed, we should follow very closely the results of Stata's margins
command. There could be some corner cases around factor variables.

An example would be helpful.

**Comment by josef-pkt** [comment] 2016-01-16 19:26
Categorical changes that are not single dummies are only supported as single dummy changes. For example, with reference coding the dummy is switching between column level and reference level, AFAIU. 
If there is a full dummy set (and no constant), then changing the value of a dummy column doesn't represent anything meaningful.

**Comment by dpavlic** [comment] 2016-01-23 01:25
I have unfortunately gotten swamped with other things, making playing around with Statsmodels (and potentially investigating a purely Python workflow into my work) impossible for the time being.  However, I will provide an example file as soon as I am able to have a moment of free time (I cannot use the data I have discovered the differences with because of confidentiality reasons).  

It should be mentioned that deviations from Stata are happening precisely with categorical variables.

**Comment by josef-pkt** [comment] 2016-01-23 01:45
@dpavlic  If you know which variables are causing the problems, then you could also just make up a simple example with random numbers, unless the problem is very specific to your actual dataset.

**Comment by josef-pkt** [comment] 2016-03-05 17:57
closing because of insufficient information

**Closed by josef-pkt** 2016-03-05 17:57 UTC
