### ISSUE TITLE
statsmodels.sandbox.regression.gmm.IV2SLS Unable to print summary

### ISSUE THREAD

**Issue by ttelfer** [statsmodels/statsmodels#3544] opened 2017-03-07 22:58 UTC
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-193-559ab9b682c5> in <module>()
---> 16 model.summary()

/econ/lib/python3.6/site-packages/statsmodels/sandbox/regression/gmm.py in summary(self, yname, xname, title, alpha)
    324         top_right = [('R-squared:', ["%#8.3f" % self.rsquared]),
    325                      ('Adj. R-squared:', ["%#8.3f" % self.rsquared_adj]),
--> 326                      ('F-statistic:', ["%#8.4g" % self.fvalue] ),
    327                      ('Prob (F-statistic):', ["%#6.3g" % self.f_pvalue]),
    328                      #('Log-Likelihood:', None), #["%#6.4g" % self.llf]),

/econ/lib/python3.6/site-packages/statsmodels/tools/decorators.py in __get__(self, obj, type)
     92         if _cachedval is None:
     93             # Call the "fget" function
---> 94             _cachedval = self.fget(obj)
     95             # Set the attribute in obj
     96 #            print("Setting %s in cache to %s" % (name, _cachedval))

/econ/lib/python3.6/site-packages/statsmodels/sandbox/regression/gmm.py in fvalue(self)
    216         restriction = np.eye(k_vars)
    217         idx_noconstant = lrange(k_vars)
--> 218         del idx_noconstant[self.model.data.const_idx]
    219         fval = self.f_test(restriction[idx_noconstant]).fvalue # without constant
    220         return fval

TypeError: list indices must be integers or slices, not NoneType

**Comment by josef-pkt** [comment] 2017-03-07 23:06
Is this with version 0.6.1 or with 0.8.0?

**Comment by ttelfer** [comment] 2017-03-07 23:14
I have tried both 0.6.1 and 0.8.0, and receive the error on both versions.

**Comment by tiagocaruso** [comment] 2017-08-01 01:07
I am having exactly the same error. Cannot find a way to print the summary. Everything else works on IV2SLS. Version 0.8.0

**Comment by josef-pkt** [comment] 2017-08-01 13:22
Based on the traceback in the issue description, this happens if const_idx is None.
This needs to be fixed, but can you check if it works with your dataset if you include an explicit constant.

IIRC I fixed this case for the regression results, but I didn't check GMM for it. #2444, #2477
But that code path should be for the case for cov_type is not 'nonrobust'. However that's in regression results, IVRegressionResults overrides the inherited fvalue and always uses Waldtest, even if that is not possible because of the missing constant column.

#3723 possible solution if const_idx is None.

Using inherited fvalue: I don't know if the ssr based f-test is valid. Given that I didn't use it and wrote the class specific fvalue, I guess not.

A "cheap" way to rescue `summary` is to set fvalue to nan if const_idx is None, similar to OLS/WLS with a robust cov_type.

**Comment by tiagocaruso** [comment] 2017-08-01 17:32
Hi, 

I added a constant to the exogenoues variable : X['const_idx'] = 1
and to the instrument: Z['const_idx'] = 1

That solved the problem. 

Thanks a lot for the feedback.

**Comment by josef-pkt** [comment] 2017-08-01 17:41
@tiagocaruso  Thanks for checking.

I have the fix of summary by setting fvalue to nan locally but still need unit tests. 
A PR should be merged into master within a few days.

**Comment by josef-pkt** [comment] 2017-08-01 17:59
PR is #3850

**Closed** 2017-09-26 14:48 UTC
Labels: comp-regression, prio-high, type-bug

**Comment by guerreroda** [comment] 2017-11-18 00:51
I am having the same error. Yet I do not know how to add the constant as @tiagocaruso suggested.
IV2SLS does not have the option hasconstant, how do I add it?

```
from statsmodels.sandbox.regression.gmm import IV2SLS
resultIV = IV2SLS(endog=df['y], exog=df[[x1', 'x2']], instrument=df[['x1', 'x2']]).fit()
```

**Comment by josef-pkt** [comment] 2017-11-19 03:43
@guerreroda 
I think this should work

df['const'] = 1
resultIV = IV2SLS(endog=df['y], exog=df[['const', 'x1', 'x2']], instrument=df[['const', 'x1', 'x2']]).fit()

otherwise you could also use `sm.add_constant`
