### ISSUE TITLE
probability plots comparing datasets with different sizes

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#2896] opened 2016-04-17 23:07 UTC
Currently, it is not possible to make a probability plot to compare differently-sized datasets:

```
ProbPlot(np.random.rand(123)).ppplot(other=np.random.rand(23))
<elided>
/usr/lib/python3.5/site-packages/matplotlib/axes/_base.py in _xy_from_xy(self, x, y)
    221         y = _check_1d(y)
    222         if x.shape[0] != y.shape[0]:
--> 223             raise ValueError("x and y must have same first dimension")
    224         if x.ndim > 2 or y.ndim > 2:
    225             raise ValueError("x and y can be no greater than 2-D")

ValueError: x and y must have same first dimension
```

That would be a nice addition.  At least the PP-plot is unambiguously defined; QQ-plots would probably require the user to pass in the quantiles to use.

**Comment by josef-pkt** [comment] 2016-06-17 14:41
I'm putting this now as bug for 0.9, it's a serious limitation

**Comment by yl565** [comment] 2016-07-22 19:42
Hi, I would like to do it as my first PR. I'm thinking about plotting the data points with two colors, each represent samples from one dataset

**Comment by josef-pkt** [comment] 2016-07-22 20:15
@yl565  A PR would be great 

If you have questions just ask and I look into it, otherwise I wait for a PR.

There might be different versions of the probability plots, e.g. if we have the two datasets on different axis, then there will not be different points for different datasets (and no need for two colors).
(If two or multiple datasets are plotted against a joint distribution, then they would have distinct points. I don't think I have looked at that case yet.)

**Comment by yl565** [comment] 2016-07-22 22:03
I think I'm confused about the P-P plot mentioned here. What I'm thinking about is as follows:

Assuming two datasets X, Y are drawn from the same distribution, so for each sorted sample x<sub>i</sub> (i=1...n), we can estimate its percentile, p1(x<sub>i</sub>) in Y. And the points to be plotted  are ( (i-1/2)/n, p1(x<sub>i</sub>) ). Conversely, we can estimate the percentile of y<sub>k</sub> (k=1...m) in X and plot points (p2(y<sub>k</sub>), (k-1/2)/m).

**Comment by josef-pkt** [comment] 2016-07-22 22:54
@yl565   I haven't really looked at the details yet. I'm more familiar with goodness of fit testing than graphics. And I usually have problems recalling the difference between pp-plots and qq-plots.

If it makes sense, and especially if there is a reference than we can include it. As I learned from @phobson work is that there are many variants of probability plots used in different fields.

What I was thinking, without having this checked yet, is to use the pooled data points and plot p1(x) on the horizontal and p2(x) on the vertical axis for x in pooled array, where p1, p2 are the empirical cdf of the first and second array.

**Comment by yl565** [comment] 2016-08-06 16:06
@josef-pkt I wasn't able to find any papers/books mention about pp/qq plots with two different data sets, but I found the following slides [http://cs.gmu.edu/~menasce/cs700/files/FittingDistributionsComparingDataSets.pdf](url) 

In slide 5, it mentioned;
>  A Q-Q plot is a plot of the type  (Q1(p), Q2(p)) where Q1(p) is the quantile function of data set 1 and Q2(p) is the quantile function of  data set 2. The values of p are (i-0.5)/n where n is the size of the smaller data set.
For P-P plot I should be similar.
Do you think this worth implementing?

**Comment by phobson** [comment] 2016-08-06 16:17
There is already this basic functionality in statsmodels. I had a hand in its creation and I'll admit it's interface and implementation leave much to be desired. 
More recently I've implemented at more robust and generic probability scale for matplotlib here:http://phobson.github.io/mpl-probscale/tutorial/getting_started.html#ready-made-probability-plots

Ultimately I'd like to see the scale included in matplotlib (or at least under their GH organization) so that statsmodels and just worry about the plotting. 
--
Sorry if this was unintelligible. I'm on my phone.

		_____________________________

**Comment by josef-pkt** [comment] 2016-08-06 16:31
@phobson  The question is how to extend the current 2-sample probability plot to unequal number of observations, and add the corresponding other plots.

@yl565 Yes, I think something like that would be the appropriate plot.
e.g. for p = 0.5 we would have a point where the median of x1 on the horizontal and the median of x2 on the vertical axis (assuming the sample sizes are odd). 
It's a bit more difficult to decide on where the points are if there is no observation with the exact p.
(There might also be an option to use linear interpolation as in the median case when nobs is even.)

To @phobson  axis scaling. Once we have decided which points or lines to plot, then it would be relatively straight forward to rescale the axes for different interpretation.

BTW: My experience is also that it's difficult to find references with a clear descriptions, including the math formulas, for various versions of the probability plots.

**Comment by yl565** [comment] 2016-08-06 16:54
@josef-pkt  Here I found two more places mentioned Q-Q plot:
[https://www.r-bloggers.com/exploratory-data-analysis-quantile-quantile-plots-for-new-yorks-ozone-pollution-data/](url)
[http://www.itl.nist.gov/div898/handbook/eda/section3/eda33o.htm](url)

They mentioned:

> If the 2 sample sizes are equal, then the Q-Q plot simply plots the sorted data of one data set against the sorted data of the other data set.
If the 2 sample sizes are different, then the quantiles are usually selected to correspond to the sorted values from the smaller data set.  The quantiles for the larger data set are then interpolated.  Thus, it is possible that none of the data from the larger data set are used in the Q-Q plot.

**Comment by yl565** [comment] 2016-08-08 16:40
@josef-pkt Hi, can I ask how may I test the gofplots? I've been running 
```python
numpy.testing.npt.run_module_suite('statsmodels/graphics/tests/test_gofplots.py')
```
It seems to be just creating and closing figures. Is it just testing if any errors will be raised? Is there another script or something to test if the plots are correct or not? I'm fairly new to unit testing. Sorry if this is a dump question.

**Comment by josef-pkt** [comment] 2016-08-08 16:52
It's definitely not a dumb question. 
So far we use almost only smoke tests for plots, i.e. check that they don't raise an exception. (and visually inspect them or add a notebook to the documentation so that a user/reader might find problems if a plot looks wrong.)
One possibility is to find the x and y values in the figure and axis objects and compare with verified or regression test data. 

(The long term option would be to use matplotlib testing facility to compare entire plots with a saved copy. I haven't looked at that in years, and it was not easy to do with older matplotlib versions.)

In most cases the plotting functions just do the plotting. If there are calculations for the plots, then we can unit test the results of those calculations directly.

**Comment by josef-pkt** [comment] 2017-04-12 02:09
related question on stackoverflow with emphasis on histograms or binned observations
http://stackoverflow.com/questions/43285752/python-compare-two-histograms-q-q-plot-with-custom-distribution/43287930#43287930

**Closed** 2019-05-09 15:14 UTC
Labels: comp-graphics, type-bug, type-enh
