### ISSUE TITLE
Unable to import statsmodels.compat tries to import unicode

### ISSUE THREAD

**Issue by Tasty213** [statsmodels/statsmodels#6100] opened 2019-08-13 08:52 UTC
#### Describe the bug

I am unable to import statsmodel.compat, when i try it raises an import error because it cannot find unicode

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.compat import unicode
>>> Traceback (most recent call last):

  File "<ipython-input-178-3d08c9ad628f>", line 7, in <module>
    from statsmodels.compat import unicode

ImportError: cannot import name 'unicode' from 'statsmodels.compat' (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\compat\__init__.py)
```
<details>

I had just tried installing pingouin but then uninstalled it. Possible that it changed something in the dependencies but i can't spot anything in the traceback. Have tried
```
pip install --upgrade --no-deps statsmodels
```
</details>

#### Expected Output

Successfull import of statsmodels.compat

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0

Statsmodels
===========

Installed: 0.10.1 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.6 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\Cython)
numpy: 1.16.2 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy)
scipy: 1.3.1 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy)
pandas: 0.24.2 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas)
    dateutil: 2.8.0 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.0.3 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib)
    backend: Qt5Agg 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 7.4.0 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython)
    jinja2: 2.10 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\jinja2)
sphinx: 1.8.5 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\sphinx)
    pygments: 2.3.1 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages\pygments)
pytest: 4.3.1 (C:\Users\26045042\AppData\Local\Continuum\anaconda3\lib\site-packages)
virtualenv: Not installed
</details>

**Comment by bashtage** [comment] 2019-08-15 23:39
This is not a bug. Compat is internal only even though it isn't marked as private. It probably should be.

**Closed by bashtage** 2019-08-15 23:39 UTC
