### ISSUE TITLE
nonparametric.KDEUnivariate returns zero bandwidth

### ISSUE THREAD

**Issue by oiegorov** [statsmodels/statsmodels#5419] opened 2018-12-11 02:38 UTC
Hi,
Does anyone have an idea why the following dataset makes KDEUnivariate return zero bandwidth?

```
data = np.array([1,1,1,1,2])
kde_sm = sm.nonparametric.KDEUnivariate(data.astype('double'))
kde_sm.fit(bw="silverman")
sup = kde_sm.support
den = kde_sm.density
print(kde_sm.bw) # prints 0
```
when `data = np.array([1,1,1,2])` the returned bandwidth is correct. When I add more 1s, the bandwidth stays zero.

Thank you!

**Comment by josef-pkt** [comment] 2018-12-11 02:45
My guess is that this comes from the robust variance, i.e. IQR which is likely zero in this case.
This is supposed to avoid the impact of outliers on the standard deviation estimate

```
bw : str, float
        "scott" - 1.059 * A * nobs ** (-1/5.), where A is min(std(X),IQR/1.34)
        "silverman" - .9 * A * nobs ** (-1/5.), where A is min(std(X),IQR/1.34)
        If a float is given, it is the bandwidth.
```

**Comment by oiegorov** [comment] 2018-12-11 02:56
you are right! I confused this with another library (pyqt_fit) which doesn't use IQR.
I wish it were possible to specify whether std or IQR should be used..

**Comment by josef-pkt** [comment] 2018-12-11 17:36
I reopen the issue, because we don't have an issue that would point out this behavior.

I'm not sure yet what to do. but either using a lower bound greater zero or adding more options would be possible.

statsmodels.robust has similar problems when the robust variance estimate is zero (`mad` in that case instead of iqr). Some authors argue that that is a feature and not a bug/problem.

The problem for many of this cases is that the theory which has the normal distribution as reference point does not tell us what to do in those corner cases that cannot come from a normal distribution.

**Comment by mycarta** [comment] 2020-03-23 16:09
This is case is posted for information, and to see if there's room to improve how this is handled.

Because it affects KDE plot in `seaborn` hence I will cross-reference this comment with a comment in that repo.

I have several dataframes for which one column always has values hovering around 1.0, 2.0, or 3.0. At times they are more monotonous.Column 'X' is the one causing zero bandwidth, but I am told by some folks I talked to (opinion, granted) that this is typical data, not edge case.
  | A | B | C | D | E | F | X
-- | -- | -- | -- | -- | -- | -- | --
5 | 7.137555 | 21.2 | 439.9543 | -0.773 | 100.1891 | 53.33888 | 2.38
8 | 4.926255 | 20.3 | 434.8608 | -0.849 | 105.6667 | 54.28129 | 3.00
11 | 8.932513 | 20.6 | 455.3215 | -0.475 | 107.9311 | 53.61902 | 3.00
14 | 10.37248 | 20.7 | 448.5906 | 0.004 | 100.2468 | 50.73556 | 2.35
17 | 10.40374 | 20.3 | 471.5983 | 0.288 | 97.23647 | 52.57565 | 2.00
20 | 13.07579 | 23.1 | 470.284 | 0.374 | 97.40481 | 52.65685 | 2.00
23 | 11.6222 | 20.4 | 465.636 | 0.365 | 96.68337 | 52.2415 | 2.00
26 | 13.69963 | 19.9 | 473.7357 | 0.249 | 98.93788 | 52.34211 | 2.00
29 | 14.9716 | 21.8 | 483.7707 | 0.049 | 104.6854 | 52.4412 | 2.00
32 | 16.49717 | 22 | 478.8973 | 0.002 | 98.70742 | 51.67327 | 2.00
35 | 18.41232 | 23.4 | 480.8015 | 0.06 | 97.68337 | 52.04151 | 2.00
38 | 19.1984 | 21.6 | 515.0517 | 0.118 | 99.4008 | 54.90969 | 2.00
41 | 21.83806 | 21.7 | 535.8684 | 0.118 | 96.06413 | 56.50744 | 2.00
44 | 22.21688 | 19.8 | 571.603 | -0.014 | 104.8377 | 59.00569 | 2.00
47 | 22.43144 | 20.4 | 634.841 | -0.345 | 104.5591 | 57.38309 | 2.00
50 | 20.25217 | 20.5 | 673.0821 | -0.736 | 108.4108 | 56.41979 | 2.00
53 | 25.19823 | 19.7 | 735.8545 | -0.791 | 95.22846 | 56.70312 | 2.00
56 | 26.13734 | 18.3 | 803.8648 | -0.608 | 89.04208 | 57.37357 | 2.00

**Comment by josef-pkt** [comment] 2020-03-23 20:41
the question is what the smoothness should be in this case, and whether we should add specific options to the bandwidth selection when a robust variance estimate like iqr is zero.

we could add an arbitrary lower bound on the variance, like 1e-10 (?), or make it depend on the variance if variance >0 and iqr == 0, or something that depends on the distance between points.

Unlimited kernels like gaussian will still average, but kernels with compact support might not find any other observations within the kernel bounds.

For usecases with many similar kdes it would be interesting to shrink towards a prior, i.e. use previous bw and partially update it as a weighted average.

**Comment by josef-pkt** [comment] 2020-03-25 20:13
(I finally thought of doing a google search)


https://cran.case.edu/web/packages/np/ChangeLog :
"
Changes from Version 0.30-1 to 0.30-2 [19-Apr-2009]

* min(std,IQR/1.348) is the adaptive measure of spread. We now test
  for the pathological case where IQR is zero but std > 0 and return
  std in this instance
"

I thought of using only a fraction of the std, or a fraction of the mean diff of sorted values

But Gretl is doing the same as R np
https://gretl-users.ricardo.ecn.wfu.narkive.com/G7J4ZUMp/on-kernel-density#post4
"
This is now fixed in CVS: if the IQR is zero we'll use the standard
deviation in setting the bandwidth instead.
"

One case would be if the user tries to use a gaussian kde with a binary or discrete variable.
Using std might oversmooth in that case and hide the discreteness too much

**Comment by josef-pkt** [comment] 2020-03-25 20:15
Also, I don't like the huge discontinuity at iqr=0, if we switch to std at that point.

**Comment by mycarta** [comment] 2020-04-01 01:17
Thanks for the updates!

**Comment by bashtage** [comment] 2020-08-11 14:59
This has been fixed in master.

**Closed by bashtage** 2020-08-11 14:59 UTC
Labels: FAQ, comp-nonparametric, corner-case, design
