### ISSUE TITLE
running Sarimax on rasberry pi

### ISSUE THREAD

**Issue by fgilbert01** [statsmodels/statsmodels#3318] opened 2016-12-13 16:28 UTC
Hello Chad,
I have implemented a load forecast model using only endogenuous hourly data that is running on a rasberry pi computer. The Sarimax is relatively time and memory consuming for such a weak processor. Coming from the world of hydrology, I thought I could fit the model, save my parameters and forecast using the saved parameters. Using saved parameters worked but does not give good results. I have a much better forecast when I fit the model immediately before running the forecast. My residential load data are on a 24 hours season. Would you have a strategy that would allow me to use previous model fit results and have a good forecast. I suppose Sarimax model are strongly influenced by recent data which is not the case with rainfall-run off hydrology model. When I used rainfall runoff model, I was calibrating once a year with 10 years of hourly data, and forecasting semi empirical model with the saved calibration parameters.

**Comment by ChadFulton** [comment] 2016-12-14 00:03
The problem is that you need to initialize the state vector and covariance matrix in the model on the pi to the values from the end of the original model in addition to using the parameters.

The easy fix is just to include at least as much of the data from the fitted model in your model on the pi as you have lags. So for e.g. an AR(12), include 12 datapoints, or for e.g. an SARIMAX(1,0,1)x(2,0,0,12) include 25 data points. This is because the state vector and covariance matrix will converge pretty quickly from their initialized value to the value you would get from the full model.

The slightly (but not much) harder fix is to save the relevant `res.predicted_state[:, t]` and `res.predicted_state_cov[:, :, t]` values from the fitted model and then pass them to the `mod.initialize_known` call on the pi's model. The slight difficulty is knowing which `t` you want to use, since it would depend on what data you're using on the pi. If it's all new data, starting immediately after the data from the fitted model, you'd use `t = -1`. If you are re-using `s` datapoints, then you would want to set `t = -1 - s`.

Here's an example notebook showing what I'm talking about. In the example where I save the relevant state and covariance matrix, I set `t = -1 - 1 = -2` because I'm re-using the last data point.

http://nbviewer.jupyter.org/gist/ChadFulton/548df244da5f0375eeea28d0afd38692

**Comment by ChadFulton** [comment] 2016-12-14 00:09
It may be hard to see from the graph, but the green line from the "Fitted model" is directly underneath the yellow line from "Correctly initialized model"

**Comment by fgilbert01** [comment] 2016-12-14 20:07
Chad,
I am running sarimax with the whole 960 observation values. I fit the model with the following instruction

`mod = sm.tsa.SARIMAX(df_load_hist,order=(1,0,0),seasonal_order=(0,1,1,24),trend='c', simple_differencing=False)`

I save the parameter;

    fileIO.write_to_csvfile(sarimax_model_results.params, cur_w_dir + os.sep + LAST_FILE_SARIMAX_MODEL_PARAMETER, '%Y-%m-%d %H:%M:%S', '%0.10f')
  
    # save the model state
    fileIO.write_to_csvfile(sarimax_model_results.predicted_state[:, -1], cur_w_dir + os.sep + LAST_FILE_STATE_PARAMETER, '%Y-%m-%d %H:%M:%S', '%0.12f')

    # save the model covariance
    fileIO.write_to_csvfile(sarimax_model_results.predicted_state_cov[:, :, -1], cur_w_dir + os.sep + LAST_FILE_COVARIANCE_PARAMETER, '%Y-%m-%d %H:%M:%S', '%0.16f')


when I want to use previous calibration , i do


       `saved_model_parameter, saved_state, saved_cov = read_model_state_parameter(path)

        mod = create_sarimax(df_load_hist, df_exogenous_hist, sarimax)

        mod.initialize_known(saved_state, saved_cov)

        sarimax_model_results = mod.smooth(saved_model_parameter)`

I always run with the last 960 accumulated observations. What I would like to do is to fit the model only once a day at the beginning of the day and use the saved model parameter for the remaining 23 hours. I then repeat the process continuously.

**Comment by ChadFulton** [comment] 2016-12-15 00:58
I can't tell which part of my solution isn't working for you. Can you post an example (ideally with some data) showing what problem you're running into?

**Comment by josef-pkt** [comment] 2016-12-15 06:16
@ChadFulton I think the question is how we can update the state without refitting.

In your example
```
# Forecast using a model with only on the last data point,
# this time correctly initializing
mod_rpi = sm.tsa.SARIMAX(endog[-1:], order=(12,0,0))
mod_rpi.initialize_known(res_fit.predicted_state[:, -2], res_fit.predicted_state_cov[:, :, -2])
res_rpi = mod_rpi.smooth(res_fit.params)
fcast_rpi = res_rpi.forecast(20)
```
IIUC, you use `res_fit.predicted_state` to intitialize for forcasting with one additional observations.
After this the next observation will arrive, and we need to update the state. And then repeat as new observations arrive, until we want to refit. 
Can we get a new updated state that includes one additional observation, or do we have to always initialize from the last fit period?

ARIMA does not directly support this kind of sequential, online, out of sample forecasting, without refitting each time.

**Comment by ChadFulton** [comment] 2016-12-16 01:38
> Can we get a new updated state that includes one additional observation, or do we have to always initialize from the last fit period?

Thanks for helping Josef, I think I understand now.

So the full answer is that the parameters of the model and the state of the model are entirely separate. The model can be initialized from any period for which the `predicted_state` and `predicted_state_cov` are available.

Lets suppose that you are (I'm not sure if this lines up completely with what you're doing, but maybe it will give the idea):
- Collecting data every hour of a day.
- Fitting the model using prior 960 observations at midnight each night.
- Running forecasts covering the current day at midnight (after fitting), at 08:00, and at 16:00.

Then you would do the following:

**At midnight**

```python
# Load history of data
endog1 = ...

# Fit the model on previous 40 days of data
mod = sm.tsa.SARIMAX(endog1, order=(1,0,0), seasonal_order=(0, 1, 1, 24))
res = mod.fit()

# Perform forecasting for the next day
fcast1 = res.forecast(24)

# Save parameters and state
fileIO.write_to_csvfile(res.params, ...)
fileIO.write_to_csvfile(res.predicted_state[:, -1], ...)
fileIO.write_to_csvfile(res.predicted_state_cov[:, :, -1], ...)
```

**At 08:00**

```python
# Load new data (data from 01:00, 02:00, ..., 08:00)
endog2 = ...

# Load parameters and state
midnight_params, midnight_state, midnight_state_cov = ...

# Create a model with those observations
mod = sm.tsa.SARIMAX(endog2, order=(1,0,0), seasonal_order=(0, 1, 1, 24))
mod.initialize_known(initial_state, initial_state_cov)
res = mod.smooth()

# Perform forecasting for the remaining 16 hours of the day
fcast2 = res.forecast(16)

# Save the state
fileIO.write_to_csvfile(res.predicted_state[:, -1], ...)
fileIO.write_to_csvfile(res.predicted_state_cov[:, :, -1], ..)
```

**At 16:00**

```python
# Load new data (data from 09:00, 10:00, ..., 16:00)
endog3 = ...

# Load parameters and state (note that params will still be the ones from
# the fitted model at midnight, but the initial_state and initial_state_cov
# will be the ones from 08:00)
midnight_params, t0800_state, t0800_state_cov = ...

# Create a model with those observations
mod = sm.tsa.SARIMAX(endog3, order=(1,0,0), seasonal_order=(0, 1, 1, 24))
mod.initialize_known(t0800_state, t0800_state_cov)
res = mod.smooth()

# Perform forecasting for the remaining 8 hours of the day
fcast3 = res.forecast(8)
```

Does that help?

**Comment by josef-pkt** [comment] 2016-12-16 01:57
good, I think the missing piece relative to the gist was that we can get the updated state from the `.smooth()` results.

aside: I was looking a bit at control charts, and methods to detect online anomalies or out-of-control observations, where something like this will be useful. We don't want to update parameters all the time because we might include outliers or undetected structural shifts with the new sample, at least that's what most of the control chart literature does. (There is also a literature that does online updating similar to recursive estimation.)

**Comment by fgilbert01** [comment] 2016-12-16 14:45
Chad,
I think you understood what I want to do. This is called operational forecasting. In my case I will always forecast 24 hours ahead though.
I will test if I get the same forecast values with the 2 cases:
-- update the state parameter and forecast
-- re-fit the model with the complete historic and forecast

**Comment by fgilbert01** [comment] 2016-12-16 19:54
`    import numpy as np
    import pandas as pd
    import statsmodels.api as sm

    dta = sm.datasets.macrodata.load_pandas().data
    dta.index = pd.date_range(start='1959-01-01', end='2009-07-01', freq='QS')
    initial_sample = dta.realgdp.ix[:'1999-10-01']

    # Estimate the model with the initial sample fit and forecast
    est_mod = sm.tsa.SARIMAX( initial_sample, order=(4,1,1))
    est_res = est_mod.fit()
    iend_index= int(initial_sample.shape[0]-1 +5 )
    print (est_res.predict(start= 0, end= iend_index))[-5:]

    #save the state parameter
    est_params = est_res.params
    est_state = est_res.predicted_state[:, -1]
    est_state_cov = est_res.predicted_state_cov[:, :, -1]

    # recreate the model with the saved parameters and forecast
    mod_updated = sm.tsa.SARIMAX(initial_sample, order=(4,1,1))
    mod_updated.initialize_known(est_state, est_state_cov)
    pure_forecast_res = mod_updated.smooth(est_params)
    iend_index= int(initial_sample.shape[0]-1+5) 
    print (pure_forecast_res.predict(start= 0, end= iend_index))[-5:]`

**Comment by fgilbert01** [comment] 2016-12-16 19:57
I forgot to comments before inserting the code.
I have tested the following code and I do not understant why I do not get the exact same forecast for the 2 cases.

    import numpy as np
    import pandas as pd
    import statsmodels.api as sm

    dta = sm.datasets.macrodata.load_pandas().data
    dta.index = pd.date_range(start='1959-01-01', end='2009-07-01', freq='QS')
    initial_sample = dta.realgdp.ix[:'1999-10-01']

    # Estimate the model with the initial sample fit and forecast
    est_mod = sm.tsa.SARIMAX( initial_sample, order=(4,1,1))
    est_res = est_mod.fit()
    iend_index= int(initial_sample.shape[0]-1 +5 )
    print (est_res.predict(start= 0, end= iend_index))[-5:]

    #save the state parameter
    est_params = est_res.params
    est_state = est_res.predicted_state[:, -1]
    est_state_cov = est_res.predicted_state_cov[:, :, -1]

    # recreate the model with the saved parameters and forecast
    mod_updated = sm.tsa.SARIMAX(initial_sample, order=(4,1,1))
    mod_updated.initialize_known(est_state, est_state_cov)
    pure_forecast_res = mod_updated.smooth(est_params)
    iend_index= int(initial_sample.shape[0]-1+5) 
    print (pure_forecast_res.predict(start= 0, end= iend_index))[-5:]

case#1
2000-01-01    11139.514303
2000-04-01    11253.072703
2000-07-01    11354.408224
2000-10-01    11450.097780
2001-01-01    11542.376380
case#2
2000-01-01    11139.400806
2000-04-01    11252.813324
2000-07-01    11353.978702
2000-10-01    11449.486175
2001-01-01    11541.575966

**Comment by josef-pkt** [comment] 2016-12-16 20:20
I think you are initializing the wrong date

Your mod_updated has the full sample starting in 1959
`mod_updated = sm.tsa.SARIMAX(initial_sample, order=(4,1,1))`
but you take your state from the last estimation period, i.e. 1999
`est_state = est_res.predicted_state[:, -1]`

So, AFAICS, you are intializing the state in 1959 with the 1999 state. Given the small persistence, there is still a small effect in the forecast left over from the initial pre-1959 state.

In the examples that Chad showed, you save the state of a given date, and then you create a new model with the data **after** that date, so the initializing state refers to the correct date in the new model.

**Comment by fgilbert01** [comment] 2016-12-18 20:00
Joseph,
I finally understand how state parameters and forecast works. To save computer time, I will need to save the end date of my last simulation and pad the missing historical values if I want to forecast a week later than the previous run. This is the case case when I forecast forward. If I forecast backward, I have no choice but to refit and forecast if I do not want to save the state for all the dates that I have previously simulated.

**Comment by josef-pkt** [comment] 2016-12-18 20:22
> I will need to save the end date of my last simulation and pad the missing historical values if I want to forecast a week later than the previous run.

If I understand you correctly:
In the last example of Chad, he showed how to get the new state from the smooth, so you don't have to go back to the original fit end period and state. You can save the state whenever to run a forecast with updated data, and reuse it the next time you make a forecast adding just the new data (no need for historical data if the saved state corresponds to the last `fit` or `smooth`ed time period).

**Comment by fgilbert01** [comment] 2016-12-18 23:13
joseph wrote: _adding just the new data ..._
To know what is the new data to add, I need to know the end of the state from my latest run. I will use the later date to build the new historical load data to create the Sarimax model and run the smooth command.

**Comment by fgilbert01** [comment] 2016-12-20 19:40
Hello,
I am implementing the change described above in my model. In case I rerun and rebuild a Sarimax model with no historical data, I create the Sarimax model with an empty dataframe.

`mod = sm.tsa.SARIMAX([], freq= horizon['frequency'], exog= df_exogenous_hist ,order=(sarimax['p']...`

when I run the following command
`mod.smooth(saved_model_parameter)
error: Observation index out of range`

Maybe in that case I do not need to run the smooth() command

**Comment by josef-pkt** [comment] 2016-12-20 20:05
(I'm surprised empty dataframe works.)

From Chad's examples: `smooth` is needed to bring your state forward with new data. If your state is already at the forecast starting point, then you don't need to smooth. 
However, at some point you might want to update the state with new data, and then you need to smooth.

**Comment by fgilbert01** [comment] 2016-12-20 20:40
If, for instance, I rerun with no new historical data, **I do not need to smooth** but how do I set the sarimax model results,  right after the initialization function below has been called. I have always done it with the smoot() function
`mod.initialize_known(saved_state, saved_cov)`

**Comment by fgilbert01** [comment] 2016-12-21 04:23
This is cool. The updating mecanism is working and it saves a lot of calculation time. The only case I am not able to run is when I run a calibration and with the exact same historical values, I try to build a model from the one that I have just saved. I tried to create a Sarimax model with an empty Dataframe [ ] but It did not work.

**Comment by josef-pkt** [comment] 2016-12-21 04:45
IIUC, what you could try to do is to save the state at index `-2` i.e. one period earlier, then you would have the data for one period left that you could use for a non-empty dataframe and model.
You would have one period redundant smooth but no empty models.

**Comment by josef-pkt** [comment] 2016-12-21 04:47
BTW, if you have everything working, then it would be great if you could write a example with all the steps. I'm sure it will be popular.  Maybe as a FAQ issue "How do we repeatedly forecast with SARIMAX without reestimating the model?"

**Comment by fgilbert01** [comment] 2016-12-21 14:43
OK,
I will write a first version that I will put on this thread. It should be ready before Christmas.
Francois

**Comment by fgilbert01** [comment] 2016-12-28 19:31
Hello Josef,
Here is my FAQ contribution.

**FAQ: "How do we repeatedly forecast with SARIMAX without reestimating the model?"** 

Yes, the Sarimax model can be created, calibrated and saved for future use. The programmer can choose to save only the last current state or save the state of the whole historical simulation period. If the user is simulating in a forward manner, only the current state is needed to update the model. 

Once the model has been fitted, the user needs to recreate the Sarimax model using only the new observed values (compared to the one used during the last run).
mod = create_sarimax(df_load_hist_recent, None, sarimax)
 
From there, instead of fitting (calibrating) the new model, the latter can be updated using the state that has been saved previously.

mod.initialize_known(saved_state, saved_cov)
sarimax_model_results = mod.smooth(saved_model_parameter)
sarimax_model_results.forecast(‘2016-12-06 00:00’)

This make the forecasting process much faster to execute because the fitting of the model is needed only for the first run. For the subsequent runs, model is updated only and forecast.

**Comment by fgilbert01** [comment] 2017-01-06 15:48
Happy 2017,
I forgot one important question about the updating mechanism. When simulating forward, do you expect the forecast values to be exactly the same whether the forecast is done through state parameter updating or fresh model fitting method.

**Comment by josef-pkt** [comment] 2017-01-06 16:08
@fgilbert01 Updating the state does not reestimate the parameters, those are based on the data when fit was last called. So, if two cases use different data for fit, then the parameters and, consequently, the forcasts will differ. 
(exception is in models that only update the state without "fitting" any parameters as in recursive OLS, AFAIU, i.e. when the state are the only parameters.)

**Comment by fgilbert01** [comment] 2017-01-06 16:23
This is what I was expecting. My workflow will then be the following for an operational forecast, I will start  using a year of historical hourly data. Calibrate and forecast. To save time, for hour 1 to 23, I will update state and forecast but for hour 0, I will recalibrate and forecast. This will speed-up calculation while keeping good forecast quality.

**Comment by josef-pkt** [comment] 2017-01-06 16:40
In case you are not doing it already:
warm start: If you use the previously estimated parameters as start_params, then a new fit should converge in just a few iterations, and fitting should also be pretty fast, although fitting still needs the full data (*).

(*) I don't think a SARIMAX model can be estimated in the style of online or Bayesian updating.

**Comment by josef-pkt** [comment] 2017-04-21 14:10
reopen as FAQ issue until we have a cleaned up documentation or FAQ answer

**Comment by bashtage** [comment] 2019-07-23 11:02
Closing as answered.

**Closed by bashtage** 2019-07-23 11:02 UTC
Labels: FAQ, comp-tsa
