### ISSUE TITLE
Using SARIMAX to fit several time series simultaneously?

### ISSUE THREAD

**Issue by vss888** [statsmodels/statsmodels#4249] opened 2018-02-05 21:47 UTC
The hypothesis: a number of time series can be modeled with a single SARIMAX model (i.e. the same parameters work for all the time series). What is wanted: to fit them all simultaneously, i.e. the likelihood function should be calculated as a sum of likelihoods for each time series. Input should be either a list of time-series or a single DataFrame with an additional column storing labels of each individual time-series, i.g.

```
A 1.0
A 2.0
A 3.0
B 1.1
B 2.2
B 3.3
```
One could of course chain all the time series into a single one, but then each switch from one series to the next one would contribute to noise, which is especially undesirable if one has many short series.

Question: is it possible in statsmodels to use SARIMAX (or something equivalent) to perform such a fit? It sounds like a rather simple thing to do: one just needs to modify likelihood function calculation with a summation over a number of likelihoods.

Thank you.

**Comment by ChadFulton** [comment] 2018-02-05 22:01
Yes, it is possible to do this. The most straightforward way is to write a custom state space model, for example I have a gist where I do this for an AR(p) model, but it should be straightforward to extend it to include the more general SARIMAX case:

https://gist.github.com/ChadFulton/583020ea3740f91bec308212d48a12db

**Comment by ChadFulton** [comment] 2018-02-07 14:42
Closing this, but feel free to reopen if you want.

**Closed by ChadFulton** 2018-02-07 14:42 UTC
Labels: comp-tsa

**Comment by vss888** [comment] 2018-02-07 19:00
Hi Chad,

Thank you for your reply and for the provided code! I am still working on adapting your example to my needs. The main question for me is how I should provide exogenous data to the code. 

I wonder, if you could create a new example, which would start with a list of pandas series (the list of endogenous variables) "endog", and a list of pandas DataFrame's "exog" (such that `len(endog)==len(exog) and len(endog[i])==len(exog[i])`), which would fit all the inputs simultaneously by a single model.

Or maybe, you could point me to some relevant documentation or to the relevant piece of SARIMAX code, I need to understand: all I need is to sum up likelihoods (potentially, with some weights) for each set of inputs to find a joint likelihood function.

Thank you very much for your help!

**Comment by ChadFulton** [comment] 2018-02-07 23:18
> Thank you for your reply and for the provided code! I am still working on adapting your example to my needs. The main question for me is how I should provide exogenous data to the code.

In SARIMAX models, the usual way of incorporating exogenous variables is by estimating the regression coefficients by maximum likelihood and then putting the `X * beta` part as an time-varying observation intercept. You could do that here, by augmenting `param_names` and `start_params` with the regression coefficients, and then including additional lines in the `update` method where you multiply the given parameters by `exog` and then use that to set the observation intercept.

> Or maybe, you could point me to some relevant documentation or to the relevant piece of SARIMAX code, I need to understand: all I need is to sum up likelihoods (potentially, with some weights) for each set of inputs to find a joint likelihood function.

If all you want to do is sum up the likelihoods for a given parameter array, then you could just create separate SARIMAX instances, as follows:

```python
# Suppose that your data looks like:
endog_list = [pd.Series(...), pd.Series(...), ... ]
exog_list = [pd.DataFrame(...), pd.DataFrame(...), ...]

# Then create a bunch of models
models = []
for i in range(len(endog_list)):
    models[i] = sm.tsa.SARIMAX(endog_list[i], order=(p, d, q), exog=exog_list[i])

# Then your joint loglikelihood function looks like:
def joint_loglikelihood(params, models):
    return np.sum([model.loglike(params) for model in models])

# And if the parameters at which you want to evaluate the likelihood function are:
params = [ ... ]

# Then your answer is:
print(joint_loglikelihood(params, models)


```

**Comment by vss888** [comment] 2018-02-08 15:59
Hi Chad,

Thank you very much for your reply! What you wrote is exactly what I have been attempting to do to calculate joint likelihood. The goal however is to be able to fit the model and to do Kalman filtering and smoothing of parameters for all of the inputs simultaneously. I am reading your paper now to see 

[http://www.chadfulton.com/files/fulton_statsmodels_2017_v1.pdf](http://www.chadfulton.com/files/fulton_statsmodels_2017_v1.pdf)

if can manage to implement such a model. My understanding is that I need to override `update`, `loglike`, `filter`, `smooth` methods in my subclass:

``` python
def update(self, params, transformed=True, complex_step=False):
    [model.update(params, transformed, comple_step) for model in models]
def filter(self, params, **kwargs):
    [model.filter(params, **kwargs) for model in models]
def joint_loglikelihood(models, params, *args, **kwargs):
    return np.sum([model.loglike(params) for model in models])
def loglike(params, *args, **kwargs):
    return joint_loglikelihood(models, params, *args, **kwargs)
def smooth(params, **kwargs):
    [model.smooth(params, **kwargs) for model in models]
```    

Please, let me know if I am missing anything. Or if I am on a completely wrong path here.

Thank you very much for your help!

**Comment by ChadFulton** [comment] 2018-02-10 17:58
There are really two ways to go about this:

The first way is to create a single joint state space model. That would be along the lines of the notebook and the suggestions I posted above. Although you have to do the work setting up the joint state space model, then you get all of the typical results (e.g. `summary()`, etc.) for free. I think this approach is probably the better one, although I think it might seem harder at first.

The second way, along the lines of the code you posted, is to approach this as maximizing a "black box" likelihood function that you happen to know how to evaluate. In this case, it's easy to jump directly to the loglikelihood function (along the lines of your code and my example above), but then you have to work a little harder to get e.g. the `summary()` output.

If you want to take this second way, then it probably makes more sense to extend `statsmodels.base.model.LikelihoodModel`, since you're really not working in a state space context anymore.

**Comment by josef-pkt** [comment] 2018-02-10 18:06
To the last point, I guess a tsa.base model would be better because it still includes the time handling and associated helper functions.

**Comment by ChadFulton** [comment] 2018-02-10 18:12
Yes, that's a good point - I wasn't sure which to recommend.

In the end, I thought `LoglikelihoodModel` might be a little better fit, since I'm thinking of the "wrapper" model as really just a black box likelihood model, and the individual `SARIMAX` models would already have the benefit of the time handling and helper functions for their individual series, e.g. for forecasting etc. But I can see arguments for either one.

**Comment by leelaprabhu** [comment] 2019-03-29 07:33
Hi @ChadFulton, 

Thank you for the gist! I was trying to do something similar- a vectorized SARIMAX- how would you suggest I adapt your gist?  
From the notation in the documentation (https://www.statsmodels.org/stable/statespace.html) it seems like only a univariate time series can be fed as input. 
Alternatively, would it be easier for me to add a seasonal component to VARMAX?

Please let me know if I should move this comment to another issue.

Thanks!

**Comment by Pouyan-Jahangiri** [comment] 2020-01-16 21:55
@ChadFulton is it possible to use SARIMAX model for multivariate time-series prediction with exog variables ? I am not sure but is that what this issue discussing OR is it about using SARIMAX to fit to multiple independent parallel time series ?

Thank you

**Comment by Pouyan-Jahangiri** [comment] 2020-01-17 02:06
@ChadFulton Thank you for your reply. Please correct me if I am wrong but I think VARMAX does not capture seasonality as good as SARIMAX does. If this is correct, is there any algorithm that can handle seasonality with exog variables for a multivariate problem in this library? Do you have any suggestion/advice ?

**Comment by sophiegonzalez3** [comment] 2022-03-10 19:27
@vss888, I'm exactly in the same scenario (multiple sensor time series that I want to fit to 1 Sarimax), would you mind posting a more complete version of your solution ?

**Comment by jakubu12** [comment] 2023-05-26 08:59
@sophiegonzalez3 @vss888 I am also struggling with this problem. Did you find a solution? If so, do you mind sharing it?

**Comment by JeppeKlitgaard** [comment] 2024-04-24 10:48
I would also like to have a way of fitting on multiple datasets in order to obtain a single model and would be happy to contribute this back to statsmodels and/or do a quick write-up on the outcome.

My use-case is using multiple time-series obtained from a couple of sensors (1 would the endog, another would be added as an exogenous regressor) in order to obtain a single model that can then be used for prediction and forecasting.

From a user-perspective, I think the ideal output would be the ability to call a `fit` method that works with multiple datasets (effectively just adding a dimension to `endog` and `exog`). Possibly this could be implemented on a more general subclass such as `TimeSeriesModel`, `LikelihoodModel`, `MLEModel`, as I think the scenario of wanting to obtain a single model by fitting to multiple datasets is a fairly common and generalises well.

If any of the maintainers have any pointers or opinions on how to implement this I would be very keen to hear them!
