### ISSUE TITLE
Unit test failure of `test_lltrend_cycle_seasonal_reg_ar1`

### ISSUE THREAD

**Issue by toddrme2178** [statsmodels/statsmodels#6505] opened 2020-02-12 20:25 UTC
The unit test  under statmodels 0.11.0 and master is failing with the following backtrace:

```
_____________________ test_lltrend_cycle_seasonal_reg_ar1 ______________________

close_figures = <function close_figures.<locals>.close at 0x9f9a826c>

    @pytest.mark.slow
    def test_lltrend_cycle_seasonal_reg_ar1(close_figures):
>       run_ucm('lltrend_cycle_seasonal_reg_ar1_approx_diffuse')

../../BUILDROOT/python-statsmodels-0.11.0-22.1.i386/usr/lib/python3.7/site-packages/statsmodels/tsa/statespace/tests/test_structural.py:248: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../BUILDROOT/python-statsmodels-0.11.0-22.1.i386/usr/lib/python3.7/site-packages/statsmodels/tsa/statespace/tests/test_structural.py:139: in run_ucm
    res.summary()
../../BUILDROOT/python-statsmodels-0.11.0-22.1.i386/usr/lib/python3.7/site-packages/statsmodels/tsa/statespace/structural.py:1784: in summary
    model_name=model_name
../../BUILDROOT/python-statsmodels-0.11.0-22.1.i386/usr/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py:4072: in summary
    " unstable." % np.linalg.cond(cov_params))
<__array_function__ internals>:6: in cond
    ???
/usr/lib/python3.7/site-packages/numpy/linalg/linalg.py:1731: in cond
    s = svd(x, compute_uv=False)
<__array_function__ internals>:6: in svd
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([[nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, na...nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan]])
full_matrices = True, compute_uv = False, hermitian = False

    @array_function_dispatch(_svd_dispatcher)
    def svd(a, full_matrices=True, compute_uv=True, hermitian=False):
        """
        Singular Value Decomposition.
    
        When `a` is a 2D array, it is factorized as ``u @ np.diag(s) @ vh
        = (u * s) @ vh``, where `u` and `vh` are 2D unitary arrays and `s` is a 1D
        array of `a`'s singular values. When `a` is higher-dimensional, SVD is
        applied in stacked mode as explained below.
    
        Parameters
        ----------
        a : (..., M, N) array_like
            A real or complex array with ``a.ndim >= 2``.
        full_matrices : bool, optional
            If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
            ``(..., N, N)``, respectively.  Otherwise, the shapes are
            ``(..., M, K)`` and ``(..., K, N)``, respectively, where
            ``K = min(M, N)``.
        compute_uv : bool, optional
            Whether or not to compute `u` and `vh` in addition to `s`.  True
            by default.
        hermitian : bool, optional
            If True, `a` is assumed to be Hermitian (symmetric if real-valued),
            enabling a more efficient method for finding singular values.
            Defaults to False.
    
            .. versionadded:: 1.17.0
    
        Returns
        -------
        u : { (..., M, M), (..., M, K) } array
            Unitary array(s). The first ``a.ndim - 2`` dimensions have the same
            size as those of the input `a`. The size of the last two dimensions
            depends on the value of `full_matrices`. Only returned when
            `compute_uv` is True.
        s : (..., K) array
            Vector(s) with the singular values, within each vector sorted in
            descending order. The first ``a.ndim - 2`` dimensions have the same
            size as those of the input `a`.
        vh : { (..., N, N), (..., K, N) } array
            Unitary array(s). The first ``a.ndim - 2`` dimensions have the same
            size as those of the input `a`. The size of the last two dimensions
            depends on the value of `full_matrices`. Only returned when
            `compute_uv` is True.
    
        Raises
        ------
        LinAlgError
            If SVD computation does not converge.
    
        Notes
        -----
    
        .. versionchanged:: 1.8.0
           Broadcasting rules apply, see the `numpy.linalg` documentation for
           details.
    
        The decomposition is performed using LAPACK routine ``_gesdd``.
    
        SVD is usually described for the factorization of a 2D matrix :math:`A`.
        The higher-dimensional case will be discussed below. In the 2D case, SVD is
        written as :math:`A = U S V^H`, where :math:`A = a`, :math:`U= u`,
        :math:`S= \\mathtt{np.diag}(s)` and :math:`V^H = vh`. The 1D array `s`
        contains the singular values of `a` and `u` and `vh` are unitary. The rows
        of `vh` are the eigenvectors of :math:`A^H A` and the columns of `u` are
        the eigenvectors of :math:`A A^H`. In both cases the corresponding
        (possibly non-zero) eigenvalues are given by ``s**2``.
    
        If `a` has more than two dimensions, then broadcasting rules apply, as
        explained in :ref:`routines.linalg-broadcasting`. This means that SVD is
        working in "stacked" mode: it iterates over all indices of the first
        ``a.ndim - 2`` dimensions and for each combination SVD is applied to the
        last two indices. The matrix `a` can be reconstructed from the
        decomposition with either ``(u * s[..., None, :]) @ vh`` or
        ``u @ (s[..., None] * vh)``. (The ``@`` operator can be replaced by the
        function ``np.matmul`` for python versions below 3.5.)
    
        If `a` is a ``matrix`` object (as opposed to an ``ndarray``), then so are
        all the return values.
    
        Examples
        --------
        >>> a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
        >>> b = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)
    
        Reconstruction based on full SVD, 2D case:
    
        >>> u, s, vh = np.linalg.svd(a, full_matrices=True)
        >>> u.shape, s.shape, vh.shape
        ((9, 9), (6,), (6, 6))
        >>> np.allclose(a, np.dot(u[:, :6] * s, vh))
        True
        >>> smat = np.zeros((9, 6), dtype=complex)
        >>> smat[:6, :6] = np.diag(s)
        >>> np.allclose(a, np.dot(u, np.dot(smat, vh)))
        True
    
        Reconstruction based on reduced SVD, 2D case:
    
        >>> u, s, vh = np.linalg.svd(a, full_matrices=False)
        >>> u.shape, s.shape, vh.shape
        ((9, 6), (6,), (6, 6))
        >>> np.allclose(a, np.dot(u * s, vh))
        True
        >>> smat = np.diag(s)
        >>> np.allclose(a, np.dot(u, np.dot(smat, vh)))
        True
    
        Reconstruction based on full SVD, 4D case:
    
        >>> u, s, vh = np.linalg.svd(b, full_matrices=True)
        >>> u.shape, s.shape, vh.shape
        ((2, 7, 8, 8), (2, 7, 3), (2, 7, 3, 3))
        >>> np.allclose(b, np.matmul(u[..., :3] * s[..., None, :], vh))
        True
        >>> np.allclose(b, np.matmul(u[..., :3], s[..., None] * vh))
        True
    
        Reconstruction based on reduced SVD, 4D case:
    
        >>> u, s, vh = np.linalg.svd(b, full_matrices=False)
        >>> u.shape, s.shape, vh.shape
        ((2, 7, 8, 3), (2, 7, 3), (2, 7, 3, 3))
        >>> np.allclose(b, np.matmul(u * s[..., None, :], vh))
        True
        >>> np.allclose(b, np.matmul(u, s[..., None] * vh))
        True
    
        """
        a, wrap = _makearray(a)
    
        if hermitian:
            # note: lapack returns eigenvalues in reverse order to our contract.
            # reversing is cheap by design in numpy, so we do so to be consistent
            if compute_uv:
                s, u = eigh(a)
                s = s[..., ::-1]
                u = u[..., ::-1]
                # singular values are unsigned, move the sign into v
                vt = transpose(u * sign(s)[..., None, :]).conjugate()
                s = abs(s)
                return wrap(u), s, wrap(vt)
            else:
                s = eigvalsh(a)
                s = s[..., ::-1]
                s = abs(s)
                return s
    
        _assert_stacked_2d(a)
        t, result_t = _commonType(a)
    
        extobj = get_linalg_error_extobj(_raise_linalgerror_svd_nonconvergence)
    
        m, n = a.shape[-2:]
        if compute_uv:
            if full_matrices:
                if m < n:
                    gufunc = _umath_linalg.svd_m_f
                else:
                    gufunc = _umath_linalg.svd_n_f
            else:
                if m < n:
                    gufunc = _umath_linalg.svd_m_s
                else:
                    gufunc = _umath_linalg.svd_n_s
    
            signature = 'D->DdD' if isComplexType(t) else 'd->ddd'
            u, s, vh = gufunc(a, signature=signature, extobj=extobj)
            u = u.astype(result_t, copy=False)
            s = s.astype(_realType(result_t), copy=False)
            vh = vh.astype(result_t, copy=False)
            return wrap(u), s, wrap(vh)
        else:
            if m < n:
                gufunc = _umath_linalg.svd_m
            else:
                gufunc = _umath_linalg.svd_n
    
            signature = 'D->d' if isComplexType(t) else 'd->d'
>           s = gufunc(a, signature=signature, extobj=extobj)
E           ValueError: On entry to DLASCL parameter number 5 had an illegal value

/usr/lib/python3.7/site-packages/numpy/linalg/linalg.py:1638: ValueError
```
Here are the dependency versions I think could be useful.  Numpy was compiled with openblas.  I could provide more package versions if they could be helpful.

```
openblas 0.3.7
python 3.7.3
Bottleneck 1.3.1
Cython 0.29.14
numexpr 2.7.1
numpy 1.18.1
pandas 1.0.1
scipy 1.4.1
```

**Comment by bashtage** [comment] 2020-02-12 21:29
If you pip install binaries do you get the same failure? Which OS and CPU
are you using?

**Comment by bashtage** [comment] 2020-02-12 21:30
Are your cross compiling?

**Comment by bashtage** [comment] 2020-05-13 08:24
No feedback and cannot reproduce, so closing.

**Closed by bashtage** 2020-05-13 08:24 UTC
