### ISSUE TITLE
TypeError: seasonal_decompose() got an unexpected keyword argument 'extrapolate_trend'

### ISSUE THREAD

**Issue by carkar7** [statsmodels/statsmodels#4793] opened 2018-07-10 01:25 UTC
Im getting an error when trying to use the extrapolate trend argument. It had worked perfectly in the past. Error seems to have started after installing fbprophet

**Comment by josef-pkt** [comment] 2018-07-10 16:21
That’s not much information to go on.
Check that you still have the correct version of statsmodels.

**Comment by josef-pkt** [comment] 2018-07-16 07:51
closing, I don't see how this could be any problem caused by statsmodels.

reopen and provide more information if there is something we need to fix

**Closed by josef-pkt** 2018-07-16 07:51 UTC
