### ISSUE TITLE
SARIMAX predict output breaks for combinations of start, end, and dynamic

### ISSUE THREAD

**Issue by jamesuber** [statsmodels/statsmodels#2554] opened 2015-07-21 21:18 UTC
Using version 0.7.0.dev0+0cee5a1

Adapting an example from @ChadFulton -- specifically the (helpful) dynamic forecasting example 1 at http://nbviewer.ipython.org/gist/ChadFulton/5127108f4c7025ed2648/stata_examples.ipynb -- I am unable to predict for subsets of the endogenous data index range while specifying dynamic prediction. For example,

# Fit the model
mod = sm.tsa.SARIMAX(endog.ix[:'1978-01-01'], exog=exog.ix[:'1978-01-01'], order=(1,0,1))
fit_res = mod.fit()
# Prediction
mod = sm.tsa.SARIMAX(endog.ix['1978-01-01':], exog=exog.ix['1978-01-01':], order=(1,0,1))
res = mod.filter(fit_res.params)
predict_res = res.predict(alpha=0.05, start=0, end=10, dynamic=5)

This leads to the error "Invalid dimensions for time-varying observation intercept vector. Requires shape (*,11), got (1, 16)"

If I do not specify dynamic then it all works, and if I specify dynamic but take the entire endog data range, then that seems OK too.

As far as I can tell the filter prediction is not the problem, but rather a limitation in how the output is wrapped up. But I am not certain cause I've found this a little tricky for me to debug into.

Also not certain if I'm using the methods correctly above, specifically the updating of the filter with the fitted parameters.

**Comment by ChadFulton** [comment] 2015-07-21 21:25
Thanks for the new bug report! As you can see, most of this hasn't been taken for a "test drive" yet, so it's great to get feedback. I'll take a look.

**Comment by jamesuber** [comment] 2015-07-21 21:38
Not a problem! I am just very thankful you have done the statespace project. Looking forward to learning more about it.

**Comment by ChadFulton** [comment] 2015-07-21 22:25
> Also not certain if I'm using the methods correctly above, specifically the updating of the filter with the fitted parameters.

You should usually just be able to use `fit_res` directly. That particular example from that gist notebook is pretty artificial (it was done to match Stata's documentation). What was done is the following:

1. The parameters were fit using a subset of the data (1959 - 1978), that's what is going on in `fit_res` (`fit_res` is an SARIMAXResults object).
2. But they then wanted to get results for the *entire* dataset (1959 - 1981), but using the fitted parameters from step (1). So a new model was constructed using the entire dataset, and an results object `res` was created (`res` is also an SARIMAXResults object), but using the specific parameters passed to it (from step 1) rather than by finding optimal parameters as is done in the `fit` function.

Now that the documentation is being rebuilt (Statsmodels is transitioning it's documentation right now due to a sustained outage at the previous documentation web host), you can find an updated version of that notebook with explanatory text at:

http://statsmodels.github.io/dev/examples/notebooks/generated/statespace_sarimax_stata.html

(unfortunately for the moment the graphs are not appearing, but I think that will be fixed soon - as I said the docs are in transition)

there are a couple of other state space notebooks at:

http://statsmodels.github.io/dev/examples/index.html#statespace

and you can find the general state space documentation at:

http://statsmodels.github.io/dev/statespace.html

**Comment by jamesuber** [comment] 2015-07-22 19:03
Thanks Chad - this documentation is very helpful. The thing I'm doing now is similar to what motivated the stata examples; I'm interested in measuring forecast accuracy over a larger dataset, given a model that was estimated on prior data. In my case it's because we will be using these models in real-time applications where we'll probably be updating them periodically or adaptively in some manner.

And thanks for the fixes to the code, of course. I've used them, and I'm still showing that predict is not necessarily interpreting the start, end, and dynamic inputs. In the context of the same stata example, I just ran through the following various predictions, with the summarized results (note: endog has 92 observations)

predict_res = res.predict(start=0, end=20, full_results=True) # ignores start/end and produces full span of 92 forecasts
predict_res = res.predict(start=0, end=20, dynamic=10, full_results=True) # correctly produces forecasts for span 0:20
predict_res = res.predict(start='1978-01-01', end='1981-01-01', dynamic='1978-01-01', full_results=True) # listens to end but ignores start, produces 89 forecasts

Again I believe I'm interpreting the intended behavior correctly, but if I'm wrong it would be great to know - thanks again!

**Comment by ChadFulton** [comment] 2015-07-23 01:36
Thanks for the new report - it's invaluable to have other eyes on this. (and yes, you are interpreting the intended behavior correctly!)

As an explanation of what's going on right now:

The `full_results` is a stop-gap measure because right now all of the `predict`, `forecast` functions are defined to return just an array of the predicted or forecasted results. But since the Kalman filter gives us covariances, it's nice sometimes to be able to calculate confidence intervals, etc. In the future, I think there will be a `prediction()` (or something) method which returns a prediction results object which has confidence intervals, etc. already built in.

In the meantime, `full_results` returns the results from KalmanFilter object on which the prediction was performed, which is:

1. In the first case (92 results) the `predict` function notices that there is no out-of-sample or dynamic prediction, so nothing new has to be calculated and it can use already calculated results (which is for the full sample, 92 periods).
2. In the second case, because `dynamic=10`, it realizes that it needs to do new calculations, so it creates a new KalmanFilter object with the correct endpoint and performs calculations from the beginning of the sample to `end=20`, starting dynamic prediction at the correct point. In this case, beginning calculations at the beginning of the sample is the desired behavior (`start=0`).
3. In this case, because `dynamic` is set, it realizes that it needs to do new calculations, so again it creates a new KalmanFilter object with the correct endpoint. Because of a number of things (in particular the details of how the Kalman filter is initialized) it is more consistent to always begin calculations at the start of the sample.

In all of these cases, the upshot is just that it simply returns the FilterResults object rather than going through and truncating each of the arrays one by one. This is clearly not a good behavior, I'm just not sure what to do about it yet.

I guess the most straightforward would just be to run through each of the outputs in the FilterResults object and truncate them to the appropriate time period.

Thanks again.

**Comment by jamesuber** [comment] 2015-07-23 11:30
Thanks for taking that time to explain. It makes sense to me now that I know it goes back to the KF object design. I need to take a closer look at that from a theoretical and implementation perspective, for any number of reasons, and this is just maybe one more.

**Comment by ChadFulton** [comment] 2015-08-01 01:37
I think that the best way to handle the remaining issue here is to eliminate the `full_results` option, in favor of a `get_prediction` method. This should be handled in PR #2566

**Comment by josef-pkt** [comment] 2016-05-30 21:58
I think we can close this, should be all done with #2566 and earlier fixes

**Closed by josef-pkt** 2016-05-30 21:58 UTC
Labels: comp-tsa, type-bug, type-refactor
