### ISSUE TITLE
Two-Way (Factor) ANOVA - Repeated Measures

### ISSUE THREAD

**Issue by Jeffalltogether** [statsmodels/statsmodels#1863] opened 2014-08-01 14:32 UTC
Multiple repeated measures ANOVA is a cornerstone method for analysis of many experimental designs, especially in biomedical sciences and clinical studies.  Most statistics programs support this method, It would be very helpful if it were added to the tools of this Python library.

To one-up some other well known scientific computing programs you will want to include a formula to calculate the "power of the performed test" (i.e., sample size determination, or power analysis).

Ref: Zar, J.H. (1999) Biostatistical Analysis: Fourth Edition. Prentice Hall, New Jersey.

**Comment by josef-pkt** [comment] 2015-01-11 19:42
closing as essentially a duplicate of #749

I have no idea when repeated measures anova might arrive in statsmodels. 
(Whenever I try to get started, I give up after a few hours.)

**Closed by josef-pkt** 2015-01-11 19:42 UTC
Labels: comp-stats, wishlist
