### ISSUE TITLE
[Doc] Discrepancy in default scale description

### ISSUE THREAD

**Issue by tashrifbillah** [statsmodels/statsmodels#6674] opened 2020-04-29 19:33 UTC
[Here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L963), it says chi-square divided by `df_resid` which is supported by the [code](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L772).

On the other hand, [here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L741) it says chi-square only.

The discrepancy gets propagated to the docstring where we would look in the first place to understand the method. So, we should fix it. Happy to submit a PR if I am right.

**Comment by josef-pkt** [comment] 2020-04-29 19:52
duplicate of #6673
closing

**Closed by josef-pkt** 2020-04-29 19:52 UTC

**Comment by tashrifbillah** [comment] 2020-04-29 19:55
Sorry about that. When submitting the issue, I got a `Page Not Found` error and so I reported again. It looks like the issue was actually reported the first time.
