### ISSUE TITLE
FAQ: OLS does not protect model data and deferred results are incorrect

### ISSUE THREAD

**Issue by ptrcarta** [statsmodels/statsmodels#6603] opened 2020-03-26 10:59 UTC
If regressions are fitted within a call of the apply function of pandas DataFrame, their statistics behave differently depending on wether they are accessed in the inner function or not. The following two methods should return the same result, but they don't.

#### Code sample

```python
import statsmodels.api as sm
import pandas as pd
import numpy as np

np.random.seed(42)

# Ys is a panel of response variables for different experiments 
Ys = pd.DataFrame(np.random.randn(4,10))
regressors = np.random.randn(10,2)

def regress1(s):
    return sm.OLS(s.values, regressors).fit()
def regress2(s):
    r =  sm.OLS(s.values, regressors).fit()
    r.rsquared
    return r

r1 = pd.DataFrame(Ys).apply(regress1, axis='columns')
print(r1.iloc[0].rsquared)

r2 = pd.DataFrame(Ys).apply(regress2, axis='columns')
print(r2.iloc[0].rsquared)
```
#### Output
```
-inf
0.548863589139653
```
(+ a divide by zero warning)

#### Expected Output
the same thing for both `print`s

#### Solution
**edit**
pandas `apply` mutates the temporary array, which changes the data, endog and exog, before they are used for lazy evaluation of results attributes.

The solution is to make a copy of the required data before calling OLS

```
def regress1(s):
    return sm.OLS(s.values.copy(), regressors).fit()
```

Note, The exog `regressors` does not need to be copied in this case because it stays the same throughout the `apply` loop.

#### Versions

```
INSTALLED VERSIONS
------------------
Python: 3.8.2.final.0
OS: Linux 4.4.109-1-lts44 #1 SMP Thu Jan 4 13:54:43 CET 2018 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.11.1 (/home/pietro/.local/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.16 (/usr/lib/python3.8/site-packages/Cython)
numpy: 1.18.2 (/usr/lib/python3.8/site-packages/numpy)
scipy: 1.4.1 (/usr/lib/python3.8/site-packages/scipy)
pandas: 1.0.3 (/usr/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.1 (/usr/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/usr/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.1 (/usr/lib/python3.8/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: 1.2.4 (/usr/lib/python3.8/site-packages/cvxopt)
joblib: 0.14.1 (/usr/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.13.0 (/usr/lib/python3.8/site-packages/IPython)
    jinja2: 2.11.1 (/usr/lib/python3.8/site-packages/jinja2)
sphinx: 2.4.4 (/usr/lib/python3.8/site-packages/sphinx)
    pygments: 2.6.1 (/usr/lib/python3.8/site-packages/pygments)
pytest: 5.4.1 (/usr/lib/python3.8/site-packages/pytest)
virtualenv: 16.2.0 (/usr/lib/python3.8/site-packages)
```

**Comment by bashtage** [comment] 2020-03-26 12:24
Internally I can see that the data stored in the model is wrong.  I suspect this is happening since a reference is being lost and this is possibly reading corrupt memory.  I would guess this happens since pandas creates a transitory Series. Somehow the data inthis series is being lost.  OLS doesn't make a copy.  The "fix" if it is desirable is to change the OLS function

```
def whiten(x):
    return x
```   

to 
```
def whiten(x):
    return x.copy()
```
which ensures that the model has an immutable copy.

This will increase memory use, so it isn't a free lunch. GLS and WLS automatically create new arrays and so do not have this issue.

```
import statsmodels.api as sm
import pandas as pd
import numpy as np

np.random.seed(42)

# Ys is a panel of response variables for different experiments
Ys = pd.DataFrame(np.random.randn(4,10))
regressors = np.random.randn(10,2)

def regress1(s):
    return sm.WLS(s.values, regressors).fit()
def regress2(s):
    r =  sm.WLS(s.values, regressors).fit()
    r.rsquared
    return r

r1 = pd.DataFrame(Ys).apply(regress1, axis='columns')
print(r1.iloc[0].rsquared)

r2 = pd.DataFrame(Ys).apply(regress2, axis='columns')
print(r2.iloc[0].rsquared)

0.4362196642459433
0.4362196642459433
```

**Comment by josef-pkt** [comment] 2020-03-26 15:19
In python we cannot loose a reference.

AFAICS pandas must be mutatin the endog array that the OLS instances get and keep references for.

solution is to make an explicit copy for the arrays that are mutated, or extract all desired results inside the apply loop
```
def regress1(s):
    return sm.OLS(s.values.copy(), regressors).fit()
```

Without the copy, all endog refer to the same underlying array, I don't think there is code in statsmodels that mutates endog.

```
[id(r2.iloc[i].model.endog) for i in range(len(r2))]
[63666871072, 63666871072, 63666871072, 63666871072]

[id(r1.iloc[i].model.endog) for i in range(len(r1))]
[63666870672, 63666870672, 63666870672, 63666870672]
```

Not making a copy of endog and exog is intentional exactly for use cases like this. In this case all models correctly hold a reference to `regressors` and the code doesn't need to make separate copies for each model in the loop.

**Comment by josef-pkt** [comment] 2020-03-26 15:26
The plain loop over pandas rows also works fine

```
res_all = [sm.OLS(Ys.T[i], regressors).fit() for i in Ys.T]
[i.rsquared for i in res_all]
[0.4362196642459433,
 0.011922654209731376,
 0.31130804443466886,
 0.16468214939479187]
```

So, I guess there is something weird in how pandas creates the temporary arrays for the apply loop.
AFAICS, statsmodels OLS works as intended. But I don't remember how much this is explained in the docs.

**Comment by bashtage** [comment] 2020-03-26 15:27
I still think that this is a bug.  Consider something like:

```
x = np.random.randn(10,2)
y = np.random.randn(10,1)
res = sm.OLS(y,x).fit()
y[5:] = 0.0
another_res =sm.OLS(y,x).fit()
```
res will produce incorrect results.  The only safe way to do what OLS is doing would be to ha ve a copy-on-write version of the data. 

Basically unless x and y are read-only, they should be copied.

**Comment by josef-pkt** [comment] 2020-03-26 15:42
it's not on the `pitfalls` list, https://www.statsmodels.org/dev/pitfalls.html

This is intentional, and the old preference of the behavior of statsmodels for library use.
Everyone with some experience in Python should know about mutating arrays, either the user makes a copy him/herself, or gets the results and let the instances get out of scope.

I have a model where inplace mutation of exog is a trick to avoid copying the entire exog during a specification search loop (piecewise regression, searching for knots)

Also there is no easy way for us to detect when the user changes endog or exog, copy-on-write would only apply if statsmodels changes them, and we avoid doing that.

(I don't even know how to create a read-only array in pandas or numpy, so that's not much of an option.)

**Comment by bashtage** [comment] 2020-03-26 15:58
Then the only other way to make the behavior correct is to immediately compute all results that depend on an array that may mutate.  I think it is unreasonable for more end-users, even library writers, to think that they have to pass an immutable array in order to get correct output at a later point in their program.  IOW, a result should behave like a frozen object or should act-as-if frozen if deferring computation.

**Comment by josef-pkt** [comment] 2020-03-26 16:10
I cannot figure out what pandas apply is doing. We can loop through it without problems, but saving the data in a list produces some weird results.

I think this is a problem in pandas `apply`, which would be a hidden usecase to trip up users. In all other cases, mutating the data will take a intentional decision by users.

All other regular changes of the data by users will NOT be inplace, and those users will not run into a mutability problem. Also, AFAIR, this is the first time in 10 years that we have this mutability problem for endog and exog.

```
s_all = []
def func(s):
    print(id(s),id(s.values), s)
    s_all.append(s)
    #print(s_all)
    return s.values
res = pd.DataFrame(Ys).apply(func, axis='columns')
print(res)
print(s_all)
```

**Comment by josef-pkt** [comment] 2020-03-26 16:37
Changing this would punish 99% of cases, to protect less than 1% of cases, except for the "stupid" pandas `apply`. 

statsmodels was from the beginning designed for covering many usecases, including just minimal results.
e.g. one of the criticism about R is that `lm` is slow, but it's slow only because of formula and other overhead. As R supporters pointed out, the underlying fit function that can be directly used with the data matrices is much faster.
In statsmodels, the relatively fast way (without a lot of overhead) is in the main class. And the overhead is outside, so plain usages are not punished.

**Comment by josef-pkt** [comment] 2020-03-26 16:44
snarky aside: I don't think statsmodels needs to attract Hadleyverse fans.

**Comment by josef-pkt** [comment] 2020-03-26 17:11
converted to faq issue

**Comment by bashtage** [comment] 2020-05-13 08:53
I'm going to close this since this is confirmed bug in pandas.

**Closed by bashtage** 2020-05-13 08:53 UTC
Labels: FAQ, comp-regression, corner-case
