### ISSUE TITLE
documentation OLSresults.get_robustcov_results

### ISSUE THREAD

**Issue by MMCMA** [statsmodels/statsmodels#2713] opened 2015-11-23 20:34 UTC
I was trying to use Discroll-Kraay robust cov matrix in `OLSresults.get_robustcov_results`, however, the documentation is not correct. 'nw-groupsum' should be used in the documentation instead of ‘hac-groupsum'.

**Comment by josef-pkt** [comment] 2016-06-17 16:08
closing as duplicate of #2578

**Closed by josef-pkt** 2016-06-17 16:08 UTC
