### ISSUE TITLE
SARIMAX - numerical instabilities w.r.t. `exog` with `mle_regression=False`

### ISSUE THREAD

**Issue by plore** [statsmodels/statsmodels#8351] opened 2022-07-25 09:25 UTC
#### Describe the bug

We are seeing some numerical instabilities in `SARIMAX` with respect to the `exog` variable when using `mle_regression = False` (example output from the code below):
![Screenshot 2022-07-22 at 15 26 46](https://user-images.githubusercontent.com/8141516/180740271-070545bd-0e57-4fdd-b38c-dc37564a12f6.png)

So far, we have not been able to establish a systematic pattern when these instabilities occur.
We have observed them for several time series and with multiple order parameters.

- Is this something to be generally expected when using the Kalman filter for getting the regression coefficients? Are there any parameters we could try to give to make the behavior more stable?
- Is there any way to directly observe the fitted exogenous regression coefficients or judge the quality of fit?
- When using `mle_regression = True` instead, the results get significantly more stable, but on some of our systems we observe a significant runtime increase (very roughly a factor of 2-3, this was actually our initial reason for switching from the default). Is this something to be expected, for example because the MLE is slower to converge in some cases?

Any insight into these questions would be much appreciated.

#### Code Sample, a copy-pastable example if possible

```python
import matplotlib.pyplot as plt
import pandas as pd

from statsmodels.tsa.statespace.sarimax import SARIMAX

endog_data = [826.,  618.,  701.,  693.,  590.,  428.,  199.,  388.,  747.,  673.,  744.,  694.,  458.,
        226.,  926.,  764.,  796.,  661.,  686.,  500.,  225.,  747.,  622.,  720.,  600.,  656.,
        412.,  226.,  838.,  757.,  765.,  742.,  673.,  378.,  220.,  789.,  636.,  752.,  606.,
        754.,  435.,  303., 1021.,  766.,  954.,  744.,  857.,  534.,  851., 1033.,  803.,  809.,
        719.,  810.,  565.,  324., 1036.,  956., 1038.,  972., 1012.,  648.,  349., 1358., 1112.,
       1147.,  918., 1023.,  736.,  351., 1862., 1482., 1273., 1227., 1240.,  951.,  431., 1852.,
       1701., 1219., 1247., 1098.,  990.,  433., 1452., 1212., 1588., 1467., 1312.,  862.]

exog_train_data = [1115.90956400414 , 1030.902751847925, 1013.611232727704,  928.253710232375,
        872.477252365173,  553.393299446787,  311.661292484906, 1093.022320092382,
       1006.339098109983,  994.85189759128 ,  867.720608741802,  862.744203463866,
        525.862060747375,  326.66154368402 , 1011.05596433807 , 1099.314283020306,
        993.950842264824,  891.029016854426,  878.500206156687,  537.682087385948,
        345.324560869919, 1039.508801479495, 1120.873450369337,  926.869989385235,
       1007.824349132811,  857.515679971991,  563.549896597977,  346.905156368248,
       1160.72567063497 ,  946.40302790969 ,  914.884859260236,  941.787354916858,
        820.759826095874,  597.244474165812,  364.248352399321, 1165.090072335397,
       1135.583606737696, 1007.071327129616,  942.129379531842,  870.567398799905,
        579.21925586317 ,  373.588271684595, 1164.587442552904, 1130.1530682608  ,
       1013.943547780111,  925.336357514179,  901.45811315154 ,  665.840157304521,
        366.569457461314, 1159.230824802788, 1049.761092603477, 1067.416462618074,
       1025.682413584452,  918.71895086848 ,  604.645828025305,  384.466273379518,
       1244.2487496739  , 1167.337667001114, 1120.222758815893, 1027.674699581872,
        981.62011030751 ,  670.708138248489,  502.940296718492, 1245.989659824868,
       1216.583051181109, 1112.863064821486, 1106.174577631253, 1066.932660852305,
        779.184398480945,  522.477809836657, 1100.654418780366, 1241.015545336241,
       1113.634708266134, 1126.295596786877,  995.966916897822,  728.675974623643,
        448.260885109182, 1092.763885919116, 1124.294499611237, 1111.683702368881,
       1059.439862466608,  967.937985597982,  706.291395855897,  424.683047626686,
       1171.13441221401 , 1120.436735489753, 1024.60210504868 , 1036.808518643461,
        918.715435781789,  622.387896010659]

exog_future_data = [374.0420018 , 1090.8446976 , 1038.77525642,  983.63567515,  895.77625025,  804.06905186,
        565.98764201,  325.98525829, 1033.61020136,  991.57091529,  918.38919593,  900.47497383,
        766.00651424,  521.23565625,  309.90392433, 1041.22982932,  993.95825524, 1002.27274995,
        886.25942178,  763.60608774,  550.90797409,  338.58202048, 1058.43658278,  927.2042228 ,
        923.0836533 ,  914.93571089,  785.57280291,  524.05093286,  371.23861574, 1067.65840995,
        943.31443422,  911.64564541,  919.20578547,  871.98167317,  618.68001351,  381.28633775,
       1165.42355084, 1063.63866753, 1038.54207367,  967.72009797,  894.81145742,  574.40010368,
        368.70164211, 1163.83083948, 1011.31573559,  971.66924532,  944.93074627,  900.8615587 ,
        613.49210663,  408.1107303 , 1009.19323441, 1143.57550535, 1044.10752682,  959.70059045,
        917.92183553,  598.75562541,  455.6924516 , 1034.09333629, 1096.61228071, 1104.49379057]

endog = pd.DataFrame(
    data=endog_data,
    index=pd.date_range(start="2021-08-23", freq="1D", periods=len(endog_data))
)

exog_train = pd.DataFrame(data=exog_train_data, index=endog.index)

exog_future = pd.DataFrame(
    data=exog_future_data,
    index=pd.date_range("2021-11-21", freq="1D", periods=len(exog_future_data))
)

plt.plot(endog, label="endog")
plt.plot(exog_train, label="exog") 

p, d, q, P, D, Q, s = 1, 1, 1, 1, 0, 1, 7

for i in range(6):
    exog_train_perturb = exog_train.copy()
    perturbation = i * 1e-10
    exog_train_perturb.iloc[-13] *= (1 - perturbation)

    model = SARIMAX(
        endog=endog,
        exog=exog_train_perturb,
        order=(p, d, q),
        seasonal_order=(P, D, Q, s),
        mle_regression=False,
    )  

    model_results = model.fit(disp=False)

    prediction = model_results.forecast(60, exog=exog_future.iloc[:60])
    prediction.index = exog_future.iloc[:60].index

    plt.plot(prediction, label=f"forecast with exog perturbation {perturbation}")

plt.legend()
```

#### Expected Output

Forecasts stable w.r.t. small perturbations of the exogenous variable.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.10.5.final.0
OS: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: None

statsmodels
===========

Installed: 0.13.2 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.30 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/Cython)
numpy: 1.23.0 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/numpy)
scipy: 1.8.1 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/scipy)
pandas: 1.4.3 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/pandas)
    dateutil: 2.8.2 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/dateutil)
patsy: 0.5.2 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.5.2 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.1.0 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/joblib)

Developer Tools
================

IPython: 8.4.0 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/IPython)
    jinja2: 3.1.2 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.12.0 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/pygments)
pytest: 7.1.2 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/pytest)
virtualenv: 20.14.1 (/Users/peter.lorenz/.local/share/virtualenvs/forecast-model-python-GWARpObd/lib/python3.10/site-packages/virtualenv)

</details>

**Comment by ChadFulton** [comment] 2022-08-02 01:33
> Is this something to be generally expected when using the Kalman filter for getting the regression coefficients?

When using `mle_regression=False`, the regression coefficients are treated as part of the unobserved state vector with a diffuse prior. When `SARIMAX` was first created, we did not have an exact diffuse prior available, so we used an approximate diffuse prior (i.e. zero mean with very large variance term). This is a common approach, but it can lead to numerical instabilities.

> Are there any parameters we could try to give to make the behavior more stable?

We have since added an exact diffuse prior, which you can access using `use_exact_diffuse=True` in the `SARIMAX` model constructor.  When I try this with your example, I get much better results:

![image](https://user-images.githubusercontent.com/280864/182272458-ca46d67c-51dd-416c-960b-87c7a3deab77.png)

Thank you for posting this great example! This will be helpful in deciding whether we want to deprecate the approximate diffuse prior and move to the exact diffuse version.

Closing the issue as answered, but please feel free to follow up if you have other questions / comments.

**Closed by ChadFulton** 2022-08-02 01:33 UTC

**Comment by plore** [comment] 2022-08-02 15:00
Thank you very much for your fast response! `use_exact_diffuse=True` indeed seems to get rid of almost all the instabilities we saw in this and other time series of similar nature. If there is no straightforward way to identify the cases when numerical instabilities are likely to occur, deprecating the approximate diffuse prior feels like the right thing to do.
