### ISSUE TITLE
DOC: add citation information

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2403] opened 2015-05-14 14:10 UTC
we still don't have any official citation information, only a few discussions on the mailing list

**Comment by njsmith** [comment] 2015-05-14 14:58
You might want to sign up with zenodo. They have github integration, and provide a service where they make an archival backup of each of your release tags and assign then each a DOI. It doesn't replace a paper citation for the project as a while, but does provide a nice tool for people who want to cite a specific version.

**Comment by jseabold** [comment] 2015-07-11 16:55
We should write a paper for JSS. As I understand it, they've relaxed their GPL-stance.

**Comment by jseabold** [comment] 2015-07-11 17:05
I flipped the zenodo switch for us.

**Comment by jseabold** [comment] 2015-07-11 17:14
Leaving this open though addressed in #2525, so I can add zenodo tagging stuff to the maintainer release docs.

**Comment by bashtage** [comment] 2019-08-02 12:59
@josef-pkt zenodo isn't setup correctly and so isn't picking up new releases.

**Comment by bashtage** [comment] 2020-07-09 07:15
Duplicate of #6576

**Closed by bashtage** 2020-07-09 07:15 UTC
Labels: FAQ, comp-docs, prio-high
