### ISSUE TITLE
** On entry to DLASCL parameter number  4 had an illegal value Crashes Python

### ISSUE THREAD

**Issue by Berowne** [statsmodels/statsmodels#3596] opened 2017-04-06 05:52 UTC
G'day. 

I'm trying to test the VAR model on multivariate TS. 
http://statsmodels.sourceforge.net/devel/vector_ar.html#granger-causality
from statsmodels.tsa.vector_ar.var_model import VAR

when I run 
    results=model.fit(2) 
I get the error 
    ** On entry to DLASCL parameter number  4 had an illegal value

**Comment by bashtage** [comment] 2017-04-06 11:30
There is a nan or inf in the matrix being inverted.

**Comment by Berowne** [comment] 2017-04-06 22:24
Thanks Kevin
Damn data wrangling. The dumping out of python is a bit of a harsh error! 

Cheers, 
Berowne

**Comment by bashtage** [comment] 2017-04-07 08:32
This crash is a feature of Intel's MKL, not Python/statsmdodels/numpy.  Best would be to check for nan/inf in sm and raise with a nice error message.

**Comment by daw3rd** [comment] 2017-08-04 15:50
It seems to call System.exit() though

**Comment by bashtage** [comment] 2019-06-08 14:00
Closing since fixed as far as it can since mostly a MKL issue.

**Closed by bashtage** 2019-06-08 14:00 UTC

**Comment by dario-passos** [comment] 2020-08-11 14:27
I can reproduce this error as well! But my fist notice of a similar error came from sklearn PLSRegression model fit. It raises a problem with linalg svd decomposition but only for the first time it is run. If I run the same cell for a second time it will work, Any clues from where this problem might come in your case with the ARIMA model?

Cheers
Dário

**Comment by bashtage** [comment] 2020-08-11 14:52
@dario-passos Are you using Windows by chance?

**Comment by dario-passos** [comment] 2020-08-11 15:38
@bashtage , yes, I'm on a Windows 10 (version 2004) PC and I have my numpy installed through pip!
A few minutes ago I installed the numpy+mkl version on my system and those svd errors seem to have disappeared. However this was not the best solution because my tensorflow-gpu install is now giving me warnings... But that is a battle to another day. Thanks for sharing the information. I'll definitely take a look.
Cheers
Dário

**Comment by bashtage** [comment] 2020-08-11 15:41
This OpenBLAS bug is definitely a nasty one that will be catching a lot out until fixed.
