### ISSUE TITLE
wls_prediction_std needs to be update to handle formula-like syntax

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#987] opened 2013-07-25 22:23 UTC
From mailing list

``` python
import pandas as pd
import numpy as np
import statsmodels.formula.api as sm
from statsmodels.sandbox.regression.predstd import wls_prediction_std

d = pd.DataFrame({'x': np.random.randn(100) })
d['y'] = d.x + np.random.randn(100)
f = sm.ols('y~x', d).fit()
print f.predict({'x':0.5})
#  => array([ 0.46793312])
print np.shape(wls_prediction_std(f, [0, 0.5]))
#  => (3, 100)
np.shape(wls_prediction_std(f, {'x':0.5}))
```

**Comment by mizzao** [comment] 2015-08-20 21:54
I'm also trying to get the CI prediction for an OLS so that I can use pandas to `fill_between` smoothly on an entire plot, instead of just for the estimated points. It would also be nice to be able to do this for the SE of the mean, as in https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/outliers_influence.py

The code at http://nbviewer.ipython.org/gist/thatneat/10286720 works for individual predictions, but not so much for a formula like `y~poly(x,2)` because it's lacking the code to generate a table of values for `exog`.

Would be happy to contribute if you guys want to point in the right direction.

**Comment by josef-pkt** [comment] 2015-08-20 22:44
I had forgotten to add some cross-links to this issue and didn't remember it. (I added  0.8 milestone.)
I remember only partially what the status of predict enhancements is. 

I added `get_prediction` in #2151, but I wasn't completely happy with the API and design.
https://github.com/statsmodels/statsmodels/pull/2151/files#diff-1284e9db0263a5cc4f79ece0c2a27220R126
looks like it should work with formula and transformations in it. When I tried a brief example yesterday for the end of http://stackoverflow.com/questions/32101233/appending-predicted-values-and-residuals-to-pandas-dataframe/32103366#32103366 , I didn't manage to get it to work with a new exog in an obvious way. 

only partially related, I guess:
we still need a few more generalizations for constructing exog for predict at some other places
https://github.com/statsmodels/statsmodels/issues/2177

You could give `get_prediction` a try and check where it doesn't work properly in the formula or pandas handling or where the api is "not nice".

The version for the linear model, OLS, WLS, returns both confidence intervals for mean and prediction intervals for new observations assuming either normal or t distribution.
The version for GLM only returns the confidence interval for the predicted mean because the distribution of observations is not normal or t, e.g. it's Poisson or Binomial conditional on the predicted mean.

(The idea is to add the bells and whistles to `get_prediction` but to keep `predict` lean for cross-validation and similar.)

**Comment by josef-pkt** [comment] 2015-08-20 23:00
Ok, I found the long SUMM issue, #2150, 
(FYI: That's just a collection of issues and a table of content and most of it is not relevant here.)

**Comment by mizzao** [comment] 2015-08-21 18:15
@josef-pkt [`get_prediction`](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/_prediction.py#L169) seems to refer to `self.scale` right now which is not defined anywhere; how did you run the example at http://stackoverflow.com/a/32103366/586086 to work?

**Comment by josef-pkt** [comment] 2015-08-21 18:53
here is my script that I used for stackoverflow which works for me.

about the comment in http://stackoverflow.com/questions/17559408/confidence-and-prediction-intervals-with-statsmodels

There might be an issue how to get weights in WLS for out of sample prediction intervals. If there is heteroscedasticity as in your plot, we would need the corresponding weights for new observations. By default we would use weights = 1. The latter could be missing if you get an exception with it.

```

import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

df = pd.DataFrame({'x1': [3.17, 4.76, 4.17, 8.70, 11.45],
                   'x2': [23, 26, 73, 72, 16],
                   'y': [880.37, 716.20, 974.79, 322.80, 1054.25]},
                   index=np.arange(10, 20, 2))

result = smf.ols('y ~ x1 + x2', df).fit()
df['yhat'] = result.fittedvalues
df['resid'] = result.resid


result2 = sm.OLS(df['y'], sm.add_constant(df[['x1', 'x2']])).fit()
df['yhat2'] = result2.fittedvalues
df['resid2'] = result2.resid

# predict doesn't return pandas series and no index is available
df['predicted'] = result.predict(df)

print(df)

print(result.get_prediction().summary_frame())
```

**Comment by mizzao** [comment] 2015-08-21 20:47
Yeah, right now if you specify `exog`, you need to specify `weights` as well, that might be fine because usually you'd want weights anyway like in the scenario you described. In this case I just wanted the CI of the regression line itself so I just set weights = 1 for a range of values generated by `np.linspace`.

**Comment by josef-pkt** [comment] 2015-08-21 21:06
@mizzao  Thanks, missing defaults weights=1 is a bug. 
Does it work for the transformation examples like in your initial question?

**Comment by mizzao** [comment] 2015-08-21 21:20
I actually didn't try the `y ~ poly(x,2)` formula; I generated the squared and constant terms myself and just ran an OLS. That's because the following does not work:

```
result = smf.ols('y ~ poly(x,2)', df).fit()
xp = np.linspace(0, 30, 100) # or whatever over the range of data
pred = result.get_prediction(exog=xp,weights=1)
```

which throws

```
/usr/local/lib/python2.7/dist-packages/patsy/eval.pyc in eval(self, expr, source_name, inner_namespace)
    164         code = compile(expr, source_name, "eval", self.flags, False)
    165         return eval(code, {}, VarLookupDict([inner_namespace]
--> 166                                             + self._namespaces))
    167 
    168     @classmethod

<string> in <module>()

NameError: name 'poly' is not defined
```

I imagine transforming `exog` for a quadratic regression would require a bit more work than what is currently implemented.

**Comment by josef-pkt** [comment] 2015-08-21 21:36
I'm not sure about the 'poly' not defined, but patsy won't understand `exog= a_numpy:array`, patsy needs to have a variable name to associate with the variables in the formula
My guess is that this should be a dict or dataframe, e.g. `pred = result.get_prediction(exog={'x': xp}, weight=1)` or something like this.

Also, IIRC, poly in patsy is a categorical trend encoding, not a polynomial of a continuous variable.

**Comment by mizzao** [comment] 2015-08-21 21:43
So I'm going by the [`stat_smooth`](http://docs.ggplot2.org/0.9.3.1/stat_smooth.html) function in ggplot,  which lets you do fit a quadratic regression to a scatter plot like

```r
ggplot(results, aes(x=foo, y=bar)) + 
  geom_point() + 
  stat_smooth(method = "lm", formula = y ~ poly(x, 2), size = 1)
```

It does seem like patsy doesn't support doing this automatically yet, e.g. https://github.com/pydata/patsy/issues/20.

I understand the need to specify `exog={'x': xp}` but this arises before that.

**Comment by josef-pkt** [comment] 2015-08-21 21:56
Since I have the stackoverflow example still open

this works correctly, as expected in the example.

```
>>> from numpy import exp
>>> result = smf.ols('y ~ exp(x1) + x2', df).fit()
>>> print(result.get_prediction(df, weights=1).summary_frame())
```

If you want a plain polynomial (that doesn't depend on a data specific state), then you can use a user defined transform. Or, I guess using numpy.polynomial   vander functions should work.

For example, this doesn't raise and exception:

```
result = smf.ols('y ~ np.vander(x1, 2) + x2', df).fit()
print(result.get_prediction(df, weights=1).summary_frame())
```

but I didn't verify if the numbers are correct.

**Comment by josef-pkt** [comment] 2015-08-21 22:03
BTW: patsy has built-in splines that you could use for a `smooth` feature. 
(penalized splines and GAM will be in statsmodels 0.8, but maybe without full patsy integration in the first version.)

**Comment by tbarrios2** [comment] 2016-01-07 02:32
@mizzao Can you share the code you used to get that plot from Aug 21st?
Thanks!

**Comment by josef-pkt** [comment] 2023-01-30 21:25
closing,
old issue, and we have `get_prediction` in most models

**Closed by josef-pkt** 2023-01-30 21:25 UTC
Labels: type-bug, type-enh, comp-formula
