### ISSUE TITLE
ENH: Add support for inequality constraints in LS estimators

### ISSUE THREAD

**Issue by luoluoluoluojunxi** [statsmodels/statsmodels#7060] opened 2020-09-28 03:30 UTC
i want to use LinearRegression by statsmodel . and i need to creat model than sure the params >0 ,but i can't find any args can do that.

**Comment by bashtage** [comment] 2020-09-28 10:37
The regression estimators do no support inequality constraints since inference in these models is non-standard and so any results would not be correct.

**Comment by emailhy** [comment] 2020-10-01 16:50
@luoluoluoluojunxi  you can try use .fit() with "minimize" as optimization methods, the spicy optimizer allow you to pass the inequality constraints, however it may impact the assumption for linear regression.

**Comment by josef-pkt** [comment] 2024-06-06 16:48
see #1382 and other previous issues

closing this as duplicat

**Closed by josef-pkt** 2024-06-06 16:48 UTC
Labels: type-enh, comp-regression
