### ISSUE TITLE
Ridge regression in GLM gives incorrect results

### ISSUE THREAD

**Issue by lbogaardt** [statsmodels/statsmodels#6431] opened 2020-01-17 15:59 UTC
#### Describe the bug

Something unexpected occurs when I perform a **logistic regression**. I believe it has got something to do with the **intercept** in the model. It only occurs when I use **fit_regularised()** and, in particular, when **L1_wt** is zero. In this case, the [hidden function](https://github.com/statsmodels/statsmodels/blob/1212616d27ab820d303377f0bcf421cd3f46c289/statsmodels/genmod/generalized_linear_model.py#L1260) **_fit_ridge()** is used.

**Note**:  Possibly related to https://github.com/statsmodels/statsmodels/issues/3624.

#### Code Sample, a copy-pastable example if possible

```python
import numpy
import scipy.special
import statsmodels.api
import matplotlib.pyplot
import sys
print("sys version: " + sys.version)
print("statsmodels version: " + statsmodels.__version__ )
print()
numpy.random.seed(123)
n = 50
interceptData = numpy.repeat(1, n)
timeData = numpy.arange(0, n)
sinData = numpy.sin(2 * numpy.pi * timeData / n)
errorData = numpy.random.normal(0, 1, n)
yData = scipy.special.expit(2.3 - 0.1 * timeData + 2.0 * sinData + 0.6 * errorData)
print("yData min: " + str(numpy.min(yData)))
print("yData mean: " + str(numpy.mean(yData)))
print("yData max: " + str(numpy.max(yData)))
for timeAdd in [0, 999]:
    for interceptAdd in [0, 999]:
        for L1_wtValue in [0, 1e-9]:
            print()
            print("timeAdd: " + str(timeAdd) + " interceptAdd: " + str(interceptAdd) + " L1_wtValue: " + str(L1_wtValue))
            interceptDataNew = interceptData + interceptAdd
            timeDataNew = timeData + timeAdd
            exogData = numpy.transpose([interceptDataNew, timeDataNew, sinData])
            model = statsmodels.api.GLM(endog=yData, exog=exogData, family=statsmodels.api.families.Binomial())
            fit = model.fit_regularized(alpha=0, L1_wt=L1_wtValue)
            print("parameters: " + str(fit.params))
            print("fit min: " + str(numpy.min(fit.fittedvalues)))
            print("fit mean: " + str(numpy.mean(fit.fittedvalues)))
            print("fit max: " + str(numpy.max(fit.fittedvalues)))
            print("MSE: " + str(numpy.mean(numpy.power(fit.fittedvalues - yData, 2))))
            matplotlib.pyplot.scatter(timeData, yData, color="red")
            matplotlib.pyplot.scatter(timeData, fit.fittedvalues, color="green")
            matplotlib.pyplot.show()
```

#### Expected Output

The models should all produce identical output, with a low MSE.

#### Output of ``import statsmodels.api statsmodels.__version__ `

sys version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
statsmodels version: 0.10.2

**Comment by lbogaardt** [comment] 2020-01-20 12:03
Here is a simpler example which goes wrong only for GLM ridge regression (fun: GLM | y: y2 | L1_wt: 0).

```
import numpy
import pandas
import statsmodels.api
import matplotlib.pyplot
numpy.random.seed(123)
n = 50
data = pandas.DataFrame(numpy.arange(0, n), columns=["x"])
data["e"] = numpy.random.normal(0, 1, n)
data["y1"] = 1.1 * data["x"] + 0.2 * data["e"]
data["y2"] = 1000.1 * data["x"] + 0.2 * data["e"]
for fun in [statsmodels.api.formula.ols, statsmodels.api.formula.glm]:
    for y in ["y1", "y2"]:
        for L1_wtValue in [0, 1e-9]:
            print("fun: " + str(fun) + " | y: " + y + " | L1_wt: " + str(L1_wtValue))
            formula = y + " ~ x"
            model = fun(formula, data)
            fit = model.fit_regularized(alpha=0, L1_wt=L1_wtValue)
            print("parameters: " + str(fit.params))
            print("fit min: " + str(numpy.min(fit.fittedvalues)))
            print("fit mean: " + str(numpy.mean(fit.fittedvalues)))
            print("fit max: " + str(numpy.max(fit.fittedvalues)))
            print("MSE: " + str(numpy.mean(numpy.power(fit.fittedvalues - data[y], 2))))
            matplotlib.pyplot.scatter(data["x"], data[y], color="red")
            matplotlib.pyplot.scatter(data["x"], fit.fittedvalues, color="green")
            matplotlib.pyplot.show()
```

**Comment by josef-pkt** [comment] 2020-01-20 15:13
> Something unexpected occurs ...

What are we supposed to see in these examples? What is unexpected?

I ran both examples but I don't see anything obviously unexpected or wrong.
(using a statsmodels branch that is based on maybe 2 months old master)

**Comment by lbogaardt** [comment] 2020-01-20 16:06
> Expected Output: The models should all produce identical output, with a low MSE.

**Comment by josef-pkt** [comment] 2020-01-20 16:18
They are all close to each other when I run it, at least at 4 decimals.

collecting all mse from second example:

```
mse_all
[0.056102742263092586,
 0.056102742302644136,
 0.05610274226301426,
 0.05613534360829357,
 0.05610274226309277,
 0.05610274230264396,
 0.05610274258968962,
 0.056135343608498804]
```

**Comment by josef-pkt** [comment] 2020-01-20 16:23
with case
```
[(0.056102742263092586, 'OLS', 'y1', 0),
 (0.056102742302644136, 'OLS', 'y1', 1e-09),
 (0.05610274226301426, 'OLS', 'y2', 0),
 (0.05613534360829357, 'OLS', 'y2', 1e-09),
 (0.05610274226309277, 'GLM', 'y1', 0),
 (0.05610274230264396, 'GLM', 'y1', 1e-09),
 (0.05610274258968962, 'GLM', 'y2', 0),
 (0.056135343608498804, 'GLM', 'y2', 1e-09)]
```

**Comment by bashtage** [comment] 2020-01-20 16:36
The top shows much more broken behavior:

![image](https://user-images.githubusercontent.com/5585221/72743159-05b9eb80-3ba3-11ea-94cd-03cc2a91150a.png)

Moving form 0 to 1e-09 makes a huge difference.

**Comment by lbogaardt** [comment] 2020-01-20 17:22
Perhaps this has been updated recently. For example 1, I get:

```
[0.003934268752320802,
 0.003934454475040054,
 0.007325498193498485,
 0.003934454475040054,
 0.07199935382475343,
 0.012145489538340904,
 0.017848822470291844,
 0.012145489538340904]
```

For example 2, I get:

```
[1.4025685565773134,
 1.4025685566104167,
 1.4025685565773134,
 1.4025685566104251,
 1.4025685565773187,
 1.4025685566104173,
 143414.5987595207,
 1.4025685566104251]
```

Note that I am not using the master branch, but the latest release:

> Output of ``import statsmodels.api statsmodels.version `: sys version: 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)], statsmodels version: 0.10.2

I'll try pulling the dev version and test again.

**Comment by josef-pkt** [comment] 2020-01-20 17:29
I didn't see the plots for the first example before. Now I also see the "bad" fit

BUG/ENH: AFAICS, there is no way to change the optimizer in `_fit_ridge` through fit regularized

using fit_ridge directly, 'bfgs' is even worse than default newton-cg
However, using "nm", I get results where all plots show approximately the same good fit.
`fit = model._fit_ridge(0, None, method='Nelder-Mead')`

So I guess this is an optimization problem in Ridge with badly scaled data.

**Comment by josef-pkt** [comment] 2020-01-20 17:41
mse_all using ridge with "nm"
`mse_all.append((mse, timeAdd, interceptAdd, L1_wtValue))`

```
mse_all
[(0.00393427035334331, 0, 0, 0),
 (0.00393427035334331, 0, 0, 1e-09),
 (0.003934227662235426, 0, 999, 0),
 (0.003934227662235426, 0, 999, 1e-09),
 (0.003934268825027017, 999, 0, 0),
 (0.003934268825027017, 999, 0, 1e-09),
 (0.003934270476165579, 999, 999, 0),
 (0.003934270476165579, 999, 999, 1e-09)]
```

**Comment by kshedden** [comment] 2020-01-21 01:49
It appears to me that the problem is resolved by changing the optimizer in `_fit_ridge`, even passing `None` as the method to minimize works.

```
import numpy as np
import pandas                                                                                                                                     
import statsmodels.api

np.random.seed(123)                                
n = 50
data = pandas.DataFrame(np.arange(0, n), columns=["x"])
data["e"] = np.random.normal(0, 1, n)                                                                                                             data["y"] = 1000 + data["x"] + data["e"]

for method in "newton-cg", "bfgs", None:                                                                                                              
    for fun in [statsmodels.api.formula.ols, statsmodels.api.formula.glm]:                                                                                
        for L1_wtValue in [0, 1e-9]:                                                                                                                          
            model = fun("y ~ x", data)
            if fun == statsmodels.api.formula.ols:                                                                                                             
                fit = model.fit_regularized(alpha=0, L1_wt=0) 
            else:                                                
                fit = model._fit_ridge(alpha=0, start_params=None, method=method)                                                                             
    print("parameters: ", np.asarray(fit.params))
 ````

**Comment by lbogaardt** [comment] 2020-01-21 08:23
If `None` is given, the default option '_BFGS_' is chosen. For example 2, this method does work. However, for example 1, I still get incorrect answer.

The method '_Nelder-Mead_' always works. This is because it is a robust method which only computes function values and not gradient values. Unfortunately, it is much slower than gradient-methods like '_Newton-Raphson_'. It would really be ashame to not be able to use the gradient during optimisation.

Could the error lie in the definition of `gr()` in `_fit_ridge()`? Or could it have to do with `start_params=None`?

**Comment by lbogaardt** [comment] 2020-01-21 11:17
Adding `options={"maxiter": 10000}` also works, in the sense that it finally converges to the correct answer. It is extremely slow however.

Changing `self.score(x) / self.nobs` to `self.score(x)` in `gr()` also seems to help. But this may be a coincidence. I'm still unsure if `gr()` is correct, given that the likelihood function uses `log`. What does `score(x)` return?

**Comment by bashtage** [comment] 2020-01-21 11:25
Score is a derivative of the objective function. Dividing by nobs can be good if the sample size is very large since it reduces the magnitude. OTOH, it can be bad in smaller models since it makes the function look flatter. The theory comes from the fact that score(x) and score(x)/nobs are both 0 if and only if score(x) is 0.  Numerical reality is harder.

**Comment by kshedden** [comment] 2020-01-21 13:13
I have not seen any issues when the intercept is 1.  When the intercept is 1000 there was an issue that seems to be resolved by #6438.

In general, with penalized regression (ridge and/or Lasso) people center and standardize the covariates.  So the scaling problem tends not to arise in practice.  Maybe that's why we didn't notice it before.

```
import numpy as np
import statsmodels.api as sm                                                                                                                                                                                                                                                                        

np.random.seed(123)
n = 50
x = np.ones((n, 2))
x[:, 1] = np.arange(0, n)
y = 1 + x[:, 1] + np.random.normal(size=n)

for method in "newton-cg", "bfgs", None:
    print(method)
    for fun in [sm.OLS, sm.GLM]:
        for L1_wtValue in [0, 1e-9]:
            model = fun(y, x)
            if fun == sm.OLS:
                fit = model.fit_regularized(alpha=0, L1_wt=L1_wtValue)
            else:
                fit = model._fit_ridge(alpha=0, start_params=None, method=method)
            print("parameters: ", np.asarray(fit.params))
    print()
```

Output of above code:

```
newton-cg
parameters:  [0.82244348 1.0077889 ]
parameters:  [0.82245482 1.00778855] 
parameters:  [0.82244325 1.0077889 ]
parameters:  [0.82244325 1.0077889 ]                                                                                                                                                                                                                                                                

bfgs
parameters:  [0.82244348 1.0077889 ]  
parameters:  [0.82245482 1.00778855] 
parameters:  [0.82244998 1.0077887 ] 
parameters:  [0.82244998 1.0077887 ]

None
parameters:  [0.82244348 1.0077889 ]  
parameters:  [0.82245482 1.00778855]  
parameters:  [0.82244998 1.0077887 ]   
parameters:  [0.82244998 1.0077887 ]
```

**Comment by lbogaardt** [comment] 2020-01-21 14:45
> 
> In general, with penalized regression (ridge and/or Lasso) people center and standardize the covariates. 

You're [right](https://stats.stackexchange.com/questions/111017/question-about-standardizing-in-ridge-regression). Intuitively, it makes sense to center and standardized. Otherwise, an arbitrary offset or different units would influence the amount of penalisation. Silly of me not to realise that earlier.

Nonetheless, in my examples, I set `alpha = 0`, it should not have mattered in this limiting case. So have we figured out why it failed exactly? Eventhough it seems to work with https://github.com/statsmodels/statsmodels/pull/6438, I still don't fully understand the initial error and I'm curious.

**Comment by josef-pkt** [comment] 2020-01-21 16:04
My guess is that is a similar scaling problem as we have with Poisson because of the `exp` function.
In Poisson large exog, make gradient and hessian very large because of the `exp` and can result in over-and underflow problems.
In one version bfgs was changed in scipy which made it less robust to large gradients and many of our Poisson unit test cases started to fail with bfgs.

I don't like standardizing data when the parameters should have an interpretation, but often some rescaling can be meaning full and makes it numerically much easier.
example: In Poisson we had a test case with age as explanatory variable, where age in the sample was around 65 to 90. Our Poisson couldn't handle this without changing the scale, e.g. subtracting 65 or 75 and/or dividing by 10 (i.e. decades).

It's still an open question whether we should add internal rescaling, #1131. We traditionally don't automatically change the data that the user provides.
alternative: a `fit_transformed` method, but that wouldn't work with `fit_regularized`.

**Comment by kshedden** [comment] 2020-01-21 23:47
newton-cg was a poor choice of default.  It can work well when the analytic Hessian is given, but when no analytic Hessian is passed, it numerically approximates the Hessian with finite differences.  When the function is quite flat, the numerical Hessian is not accurate enough.  You get negative curvature here:

https://github.com/scipy/scipy/blob/cb42f2f683f0ff4bcf42d33b1aaa3fa555c9d2c4/scipy/optimize/optimize.py#L1742

The new default is bfgs which does not approximate the Hessian explicitly (it sort of adapts to the Hessian in a more indirect way using the successive gradient values).

**Comment by lbogaardt** [comment] 2020-01-22 08:18
The _Hessian_ is only used to check for convergence, right? The _Jaccobian_ is used during iterations to take steps in particular directions. Can the _Hessian_ be giving analytically for _Loglikelihood_ of a _GLM_? If `self.score()` provides the analytical gradient, I would assume it's possible to differentiate once more.

**Comment by kshedden** [comment] 2020-01-22 12:43
Newton CG uses the Hessian to get the search direction, you can see this on line 1763 of the scipy code linked above.  We do have the analytic Hessian for GLM, but we currently don't pass it to minimize (at least not in this special case of fit_regularized with L2 but no L1 penalty).  It would be easy enough to do (around line 1293 of generalized_linear_model.py).  But I think that in general the Hessian is too espensive and BFGS will come out ahead.

**Closed** 2020-02-18 01:50 UTC
