### ISSUE TITLE
Implement generalized additive models, ordered model (ordinal)

### ISSUE THREAD

**Issue by dsaxton** [statsmodels/statsmodels#4908] opened 2018-08-15 03:15 UTC
It seems that there are a couple fledgling Python projects working on similar things, but might it be worthwhile implementing these models within `statsmodels`?  This is one domain where I feel that R still surpasses Python, so there's certainly some fertile ground for new development.

**update (josef)**

second part of this issue is for ordered model starting https://github.com/statsmodels/statsmodels/issues/4908#issuecomment-414087639

GAM merged in #5481
OrderedModel (in miscmodels) merged in #7035

**Comment by jbrockmendel** [comment] 2018-08-15 03:49
There exists `statsmodels.sandbox.gam`.  `sandbox` code is not for the most part in useable form, but there may be something worth salvaging from it.

**Comment by josef-pkt** [comment] 2018-08-15 04:37
#4575 and precursor PRs

sandbox.gam predates statsmodels and uses backfitting instead of plain scipy optimizers which is more useful for including kernel regression but not as useful for splines.

**Comment by dsaxton** [comment] 2018-08-15 19:53
Thanks, is there a certain place (conceptually) that would make a sensible starting point for new contributions?

**Comment by josef-pkt** [comment] 2018-08-15 20:37
GAM is a difficult PR because it needs to be integrated with several other things.
I applied for a NUMFOCUS small development grant that includes merging GAM, but the decision is not out yet. If I get it, then GAM should be merged within a month or two.

Conceptually what is incomplete or insufficient in GAM are covariance matrices. R's mgcv has several options and changed its behavior several times during its lifetime.
Currently my plan is mainly to focus on the standard HC1 sandwich covariance for M-estimators.
It is however difficult to work on that until after GAM has been integrated with the penalized mixin class #4576 where I fixed some bugs that are still in the GAM version.

One related possibility is to get started with the pattern of penalized models would be to add an official PoissonPenalized class. The plan is to add several XXXPenalized classes.
Currently I'm using generic version as test cases, but there are no public model specific classes yet.
e.g. https://github.com/statsmodels/statsmodels/pull/4576/files#diff-998ca927d33550860463cd03cb0cbbdcR20
The main work would be to see what Results methods need to be overwritten from the basic model class, e.g. inherited from Poisson results.

Another conceptual issue that I was struggling with are effective degrees of freedom for generic cases, e.g. when we don't have directly the WLS/IRLS interpretation available.
As a related issue, I added experimental support for GLMInfluence and MLEInfluence #4732
The basic statistics looke good but it needs a second round of review and will need extensions.

**Comment by josef-pkt** [comment] 2018-08-16 00:05
The basic structure is penalized maximum likelihood similar to GAM. Our GAM uses the PenalizedMixin with a specific L2 penalization structure for the spline terms. 
The GAM PR (GSOC project) also had added a penalized IRLS optimization method in analogy to the unpenalized GLM.
The GAM PR does not include anything specific for the additive linear model, e.g. penalized least squares, but includes penalized MLE with Gaussian family as (essentially) equivalent model.

The PenalizedMixin is designed for using different penalization classes, e.g. I was using "structured" SCAD that can penalize linear transformation of the parameters with an example for penalization of pairwise contrasts for a categorical variable.

Penalization is a large topic, so it might be useful for you to narrow down to what you are interested in.
e.g. https://github.com/statsmodels/statsmodels/issues/4038
I have been using a 'topic-penalization' label for related issues (likely missing some issue) https://github.com/statsmodels/statsmodels/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Atopic-penalization+

I'm available to answer question related to this (or other topics outside tsa) AFAIR or as far as I can quickly look them up.

**Comment by dsaxton** [comment] 2018-08-17 20:58
Are there any papers you'd recommend that give a general survey of the literature?

**Comment by josef-pkt** [comment] 2018-08-17 20:58
To follow up on the above: I just got a notification that the NumFOCUS small development grant has been approved, so finishing and merging GAM, and refactoring of Probability Plots is on my schedule for the next one to two months.

It would be great if you were to work on something related because that would make discussing and reviewing problems and design decisions much easier.

I won't start right away, I have two PRs to finish before switching topics again (and my wife an I are buying a house on Monday).

**Comment by dsaxton** [comment] 2018-08-17 21:03
Congrats!  I'd be happy to help out.  Just as a heads up, my background is primarily in statistics / mathematics and so my software development skills are definitely not expert level.

**Comment by josef-pkt** [comment] 2018-08-17 21:42
> Are there any papers you'd recommend that give a general survey of the literature?

I need to look it up, I don't find anything right now.
The main reference for the GAM implementation is Simon Wood and his mgcv package which should have additional references.

I have piles of articles that I printed but I haven't looked at splines and GAM much since 2015, although a lot more on general penalized MLE for various models.

In general there was debate between two groups/approaches, one put effort in selecting knots and knot location, and the second put more effort on penalization with a simple knot selection.
I hat strong preference for the later because knot selection is much more computing intensive, 
e.g. using equal spaced knots and simple difference penalization
Eilers, Paul H. C.; Marx, Brian D. Flexible smoothing with B -splines and penalties. Statist. Sci. 11 (1996), no. 2, 89--121. doi:10.1214/ss/1038425655. https://projecteuclid.org/euclid.ss/1038425655

They, or Marx with co-authors, have several similar articles. Eilers has a (relatively simple) book, AFAIR, that I partially read but don't have available right now. (AFAIR, it wasn't detailed enough to help a lot with implementation details).

For more general or other penalization topics, I'm a big fan of Jianqing Fan's work.

> my background is primarily in statistics / mathematics and so my software development skills are definitely not expert level.

That's great, we don't have enough statisticians working on statsmodels.
(My background is economics and econometrics and I had and have to learn "statistician's statistics", and also parts of "Modern Econometrics", while working on scipy and statsmodels.)

(For GSOC I have been arguing that statistics, econometrics or math background is more important than software development skill or familiarity with Python, because the latter are easier to pick up quickly at the level that we require.)

**Comment by josef-pkt** [comment] 2018-08-18 12:46
I still had the google search for eilers and marx open

Eilers, P. H. and Marx, B. D. (2010), Splines, knots, and penalties. WIREs Comp Stat, 2: 637-653. doi:10.1002/wics.125
AFAIR, this is an overview article that I read early on

https://www.researchgate.net/publication/290086196_Twenty_years_of_P-splines
seems to be a more recent version on the same topic, but AFAIR I haven't read it

**Comment by dsaxton** [comment] 2018-08-18 21:34
How do you feel about incorporating penalized ordinal regression into `statsmodels`?  I came across this Cross Validated post suggesting there may be some interest in this feature:

https://stats.stackexchange.com/questions/168262/ordinal-logistic-regression-in-python

Coincidentally one of my PhD advisor's former students (Bret Hanlon) has done some work on implementing these models in R:

https://arxiv.org/pdf/1706.05003.pdf

I will get in touch with him and see if he has any ideas on this front.

**Comment by josef-pkt** [comment] 2018-08-18 22:08
2015 was a year when I wrote a lot of prototypes
#2600 has a draft version for ordered models, with logit and probit. There is a large demand for it but personally I have too many "high priority" projects which often can be my taste and not current user demand.

Note, I write a lot of prototype code not because I want to add immediately a new model, but more to help be understand the underlying structure for medium to long term planning for statsmodels, e.g. what changes or enhancements do we need to the generic structure of our models, results, and supporting functions, and it helps in reviewing PRs when someone is working on something related.

In terms of approaches to penalized estimation Kerby Shedden and I are splitting the work. Kerby added elastic net based on coordinate descend closer to the machine learning literature. I'm working mainly on problems where we don't have too many explanatory variables and where we can use standard optimization. For example GAM and PenalizedMixin are based on standard dense linear algebra or scipy optimizers, and we just use a penalized version of our standard models.

(I need to run. Bottom line: There is a large number of models that are still missing and that would find a large user base when they become available. What gets added depends on a mix of priority and personal interest of developers.)

**Comment by dsaxton** [comment] 2018-08-18 22:16
I can try to work on this if you think it is worthwhile.

**Comment by dsaxton** [comment] 2018-08-19 00:50
Would you say then that getting an OrderedLogit model (e.g., proportional odds model) might be a worthwhile goal for the near term?  I could work on this.

**Comment by josef-pkt** [comment] 2018-08-19 01:31
Getting Ordered categorical models into statsmodels is definitely worthwhile and would find a user audience.

I was looking briefly at my PR which is closer to cumulative link function with Logit/proportional odds just as a special case.
Note, genmod.generalized_estimating_equations also has a OrdinalGEE added by @kshedden.
The approaches across different models for ordered categorical endog varies a bit, OrdinalGEE is an extended version in the structure of GLM.
My approach uses a univariate endog and follows more closely the discrete.discrete_model.BinaryModel structure which includes Logit and Probit as subclasses.

Adding a model like this would be a good learning "exercise" going incrementally from prototype as in my PR to a full model. We keep adding many bells and whistles to our models, but it's an incremental process where only the base functionality (with associated unit tests) needs to be available on initial merge. Over time this can be extended to have most or all of the extras. (Depending on how closely a new model fits into the existing pattern, many extra features will be inherited.)
There are some specific extras that can be added as time and interest allows. In the case of ordered categoricals, one of them would be to support the ordered categorical factor type in pandas, which we don't use or support anywhere yet.

**Comment by josef-pkt** [comment] 2018-08-19 01:41
(possibly a correction
Cumulative link model might be the wrong reference for the model in my PR. The basic structure in my PR is similar to interval censored regression with unobserved thresholds. I don't really remember the details of the various versions and definitions and what they are called in different strands of the literature.)

**Comment by dsaxton** [comment] 2018-08-19 17:33
Question: is there a certain framework that `statsmodels` uses for optimization / likelihood maximization?  I'm assuming `scipy.optimize` plays a role, but wanted to make sure.

**Comment by jbrockmendel** [comment] 2018-08-19 17:44
Most likelihood-maximization is done by subclassing base.model.LikelihoodModel and calling that classe's `fit` method.  That will in call into base.optimizers, which wrap scipy.optimize.

**Comment by josef-pkt** [comment] 2018-08-19 20:29
You can look at GLM.fit which delegates now to two private _fit methods. `_fit_irls` is the usual GLM reweighted least squares solver that was specifically written for GLM. `_fit_gradient` calls the `super` method that does the actual optimization as jbrockmendel mentioned.

The `base.model.LikelihoodModel` defines the fit method that calls the optimization functions. Those are currently hard coded to use (negated) loglike, score and hessian methods of the model for the objective function and first and second derivatives.

**Comment by dsaxton** [comment] 2018-08-19 20:35
Thanks, I'll take a look at the code. Do the fit methods support the inclusion of constraints by chance? It looks like for the cumulative logit model the sequence of intercepts needs to satisfy a monotonicity requirement.

**Comment by josef-pkt** [comment] 2018-08-19 20:48
> Do the fit methods support the inclusion of constraints by chance?

maybe by chance but not by design.
We have a generic access to scipy minimize which could include constraints, but we don't use that anywhere yet.

Our standard way of handling constraints is by transformation, e.g. using exp(param) if a param has to be positive or non-negative. For example, in my PR I impose monotonicity by using exp of the increment of the thresholds/intercept.
(This was suggested in one of the econometrics references that I read for ordered models.)

**Comment by dsaxton** [comment] 2018-08-20 00:04
Ah yes, that's a clever way to force monotonicity. Will give that a try.

**Comment by dsaxton** [comment] 2018-08-20 13:59
@josef-pkt Another quick question, does `statsmodels` contain a collection of continuous cumulative distribution functions (I believe `scipy` does, but perhaps `statsmodels` has friendly wrappers around these)?  It may be helpful for an `OrderedModel` to accept the inverse of a cdf (or just the cdf itself) as its link, with the logit and probit being special cases.

**Comment by josef-pkt** [comment] 2018-08-20 14:19
you can check my PR for how I did it which is just using the corresponding methods from scipy's distribution.

The direct answer is no, we don't have wrappers around scipy's distributions. Whether and how much to add to those is still open.

the longer answer:
Scipy's distributions do not include derivatives of the loglike, so the main models use our own implementation of loglike, score and hessian. (It also avoids scipy distribution overhead for generic input checking in the optimization loops.)
statsmodels.distributions have some distribution functions that are not in scipy (or not in the form/parameterization that we need), e.g. GeneralizedPoisson.
One problem that we have is that because the loglike, score and hessian are built into specific models it is difficult to reuse them.

For ordered or censored models it is easiest just to reuse the scipy distributions as much as possible because it defines more methods like cdf, ppf where reimplementing them didn't sound worthwhile so far.
e.g. discrete Probit just uses scipy stats https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/discrete_model.py#L1927 but uses explicit code for score and hessian
Logit has easy analytical formulas and implements cdf pdf directly
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/discrete_model.py#L1725

i.e. the current approach is eclectic and depends on the model, there is no good reusable structure yet.

**Comment by josef-pkt** [comment] 2018-08-20 14:40
> the current approach is eclectic and depends on the model, there is no good reusable structure yet.

Adding a more general comment:
Designing modular components that can be reused for different models and functionality is difficult work. Often we don't have an overview of possible applications and for authors of individual models or functionality it is easier to work with the specific implementation.
Much of the work making things more generic, more general and more reusable happens ex-post when we have a better idea what the common pieces of different models are, and when we need more consistent behavior across models to add new generic functionality.

**Comment by dsaxton** [comment] 2018-08-20 16:03
Got it.  Seems like simply focusing on link functions that cover the overwhelming majority of use cases (logit, probit, complementary log-log, and perhaps Cauchy) would be enough, instead of trying to extend to "all possible" link functions.

**Comment by dsaxton** [comment] 2018-08-20 18:36
@josef-pkt I have a very simple working example (uniformly distributed ordered categories and predictors unrelated to those categories) where it seems we can consistently estimate the parameters of a proportional odds model.  I will need to figure out how to fit the pieces into the `statsmodels` framework, but in the meantime is there a way I can share a notebook for you to look over when you have time?

**Comment by josef-pkt** [comment] 2018-08-20 18:57
put a notebook in a gist which makes it easy to look at.

(aside for later if needed: When we include notebooks in the statsmodels documentation, then we remove the output so that the repository memory usage doesn't get increased by generated plots and tables.)

**Comment by josef-pkt** [comment] 2018-08-20 18:59
(written earlier today)

there is also a difference in tradition, origin in literature for essentially the same models.
e,g GLM binomial with probit link is the same as discrete Probit
in GLM the distribution is binomial and probit is just a specific link function.
in discrete Probit is build on a latent underlying variable that has a normal distribution, but we only observe a "censored" version.

GLM comes from the statistics tradition and Probit from the econometrics tradition.
The difference is in the surrounding code/results and what is easier to add under one or the other version.
My OrderedModel follows the latent variable interpretation so it should be able to share pattern and code with censored or truncated models.

**Comment by dsaxton** [comment] 2018-08-20 20:12
I've created a gist here: <script src="https://gist.github.com/dsaxton/92baf15b74c859e714a83f09029bf5b4.js"></script>

**Comment by bashtage** [comment] 2019-07-19 14:49
Master has some support for GAM. Closing.

**Comment by bashtage** [comment] 2019-07-19 14:51
Probably worth saving the notebook.

**Comment by josef-pkt** [comment] 2021-06-04 14:49
both GAM and OrderedModel have been merged in initial versions.
comment with notebook is cross-linked in #7069

closing this

**Closed by josef-pkt** 2021-06-04 14:49 UTC
Labels: comp-discrete, reference, type-enh
