### ISSUE TITLE
VAR Model Forecasting for dependent variable

### ISSUE THREAD

**Issue by bhavana012** [statsmodels/statsmodels#5884] opened 2019-06-25 07:20 UTC
I'm trying to use VAR model for forecasting 10 future points by considering one variable as dependent and rest of them as independent but this model considers all the variables interdependent on each other and it predicts for all the variables. How can I use it for predicting just one variable considering all the others as independent variables.

**Comment by bashtage** [comment] 2019-06-25 07:30
The 10 step forecast depends on the 9 step forecast of all variables in the model.  How are you forecasting these?

**Comment by bhavana012** [comment] 2019-06-25 08:59
Not for the future but suppose the last 10 data points based on rest of the data.
This is the snapshot of the data:
|index | holiday | temp | rain_1h | snow_1h | clouds_all | weather_main | weather_description| volume |
					
|2012-10-02 09:00:00 | None | 288.28 | 0.0 | 0.0 | 40 | Clouds | scattered clouds | 5545|
|2012-10-02 10:00:00 | None | 289.36 | 0.0 | 0.0 | 75 | Clouds | broken clouds | 4516|
|2012-10-02 11:00:00 | None | 289.58 | 0.0 | 0.0 | 90 | Clouds | overcast clouds | 4767|
|2012-10-02 12:00:00 | None | 290.13 | 0.0 | 0.0 | 90 | Clouds | overcast clouds | 5026|
|2012-10-02 13:00:00 | None | 291.14 | 0.0 | 0.0 | 75 | Clouds | broken clouds | 4918|
________________________________________________________________________________________________
And this is the code I've written:
```
exog=data[["temp","rain_1h","snow_1h","clouds_all"]]
endog=data["traffic_volume"]
mod = sm.tsa.VARMAX(exog = exog, order=(2,0), trend='nc', endog = endog)
res = mod.fit(maxiter=1000, disp=False)

```
I want to forecast the traffic volume based on the rest of the variables.

**Comment by bashtage** [comment] 2019-06-25 09:11
If you are only making a prediction 1 step in teh future, then you can use an OLS

```
# These are obs 0...nobs-1
predictors = sm.add_constant(data[["temp","rain_1h","snow_1h","clouds_all"]].iloc[:-1]
# This is obs 1,...,nobs
predicted = data["traffic_volume"].iloc[1:]
mod = sm.OLS(predicted, predictors )
```

**Comment by TianzhuQin** [comment] 2019-06-28 13:16
I guess I had similar question with Havana before. I was also wondering why VAR model also gives the coefficient of other variables (which are time series respectively), because I was thinking the model for each variable should be independent. It is actually wrong. 

VAR fully considers the correlation between time series, and the A in Yt = A * Yt-1 + E, is a n by n matrix, which means each entry of Yt respectively will be calculated as a model of each entry of Yt-1.

I hope it helps, but please forgive me if I mistook your question, since it used to bother me a lot.

**Comment by bashtage** [comment] 2019-07-22 07:47
Closing this as expected behavior.  Feel free to open a new issue if this is a persistent problem.

**Closed by bashtage** 2019-07-22 07:47 UTC
