### ISSUE TITLE
Poisson Regression example not working

### ISSUE THREAD

**Issue by swdipple** [statsmodels/statsmodels#8716] opened 2023-03-03 21:36 UTC
I was following along the example provided here https://www.statsmodels.org/dev/examples/notebooks/generated/postestimation_poisson.html#Prediction
In the "Prediction" section I ran into the following exception "'PoissonResults' object has no attribute 'get_prediction'".
I checked the attribute list
`['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_cache', '_data_attr', '_data_in_cache', '_get_endog_name', '_get_robustcov_results', '_use_t', 'aic', 'bic', 'bse', 'conf_int', 'cov_kwds', 'cov_params', 'cov_type', 'df_model', 'df_resid', 'f_test', 'fittedvalues', 'get_margeff', 'initialize', 'k_constant', 'llf', 'llnull', 'llr', 'llr_pvalue', 'load', 'mle_retvals', 'mle_settings', 'model', 'nobs', 'normalized_cov_params', 'params', 'predict', 'predict_prob', 'prsquared', 'pvalues', 'remove_data', 'resid', 'resid_pearson', 'resid_response', 'save', 'scale', 'set_null_options', 'summary', 'summary2', 't_test', 't_test_pairwise', 'tvalues', 'use_t', 'wald_test', 'wald_test_terms']`
and get_prediction was not included.

version is 
statsmodels     0.13.5

Is there a more up to date documentation page or is there a bug with PoissonResults?

**Comment by josef-pkt** [comment] 2023-03-03 21:54
This will be in 0.14. `dev` documentation is for current `main`, but it's not released yet.

the 0.14 release should be soon. 

It looks like we don't have nightly builds anymore, at least I don't find any. So, the only way to get `main` is to install from github (which requires build dependencies)

**Comment by swdipple** [comment] 2023-03-03 22:43
Awesome thanks!

**Comment by josef-pkt** [comment] 2024-02-11 14:52
closing, this is outdated and not a bug

**Closed by josef-pkt** 2024-02-11 14:52 UTC
Labels: comp-discrete, type-invalid
