### ISSUE TITLE
SARIMAX model too large

### ISSUE THREAD

**Issue by sammo** [statsmodels/statsmodels#5727] opened 2019-05-15 14:53 UTC
#### Describe the bug

Team, I'm running SARIMAX for daily data and trying to catch annual seasonality. I used seasonal_order = (0, 1, 0, 365) but I faced the following issues:
- Model took a few minutes to generate, which is too long (x10 or so) compared to R's forecast$auto.arima function
- Model generated was over 7 GB which is also too large compared to R's forecast$auto.arima

The seasonal_order I'm using is what auto.arima (in R) suggested for the data I'm feeding the model. Data is confidential but I generated a similar dataset (below) to replicate the issue and show my code.

If I'm missing something please let me know. Otherwise, any suggestions on how to make SARIMAX work for this data. I'd like to catch the annual seasonality first, I can account for the weekly later.

I greatly appreciate you looking into this.

Thanks,
Sam

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
import statsmodels as sm
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt

print(f"statsmodels version: {sm.version.full_version}")
# >>> statsmodels version: 0.9.0

# Variables and data
figsize = (16, 8)
freq = "D"
n = 800
np.random.seed(7)
df = pd.DataFrame(
    data={
        "ds": pd.date_range("2016-11-01", periods=n, freq=freq),
        "y": np.random.rand(n),
    }
)
df.set_index("ds", drop=False, inplace=True)
df["exo1"] = df.index.month
df["exo2"] = df.index.week

df.loc[:, "y"] = df["y"] + df.index.dayofweek
add_fact = (
    (df.index.month == 12)
    * 1
    * (df.index.week.values - pd.to_datetime("2018-11-25").week)
    * 4
)
add_fact[add_fact < 0] = 0
df["add_fact"] = add_fact
df.loc[:, "y"] += df["y"] * df["add_fact"]

df.loc[:, "y"].plot(figsize=figsize)

# Train / predict
split_date = "2018-11-30"
m = SARIMAX(
    endog=df.loc[:split_date, "y"],
    exog=df.loc[:split_date, ["exo1", "exo2"]],
    order=(1, 1, 0),
    seasonal_order=(0, 1, 0, 365),
)
m_fit = m.fit()
pred = m_fit.forecast(
    df.loc[split_date:, "y"].shape[0], exog=df.loc[split_date:, ["exo1", "exo2"]]
)

# Visualize
fig = plt.figure(figsize=figsize)
ax = fig.add_subplot(111)
df["y"].plot(figsize=figsize, ax=ax)
pred.plot(figsize=figsize, ax=ax)
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``sm.show_versions()`` here below this line]

statsmodels version: 0.9.0

I got this error running sm.show_version():
AttributeError: module 'statsmodels' has no attribute 'show_versions'

</details>

**Comment by ChadFulton** [comment] 2019-05-16 00:33
Thanks for the report. Yes, a period of 365 is really too much for the SARIMAX model - we should at least add a warning.

In your case you're just doing seasonal differencing, so you can use the argument `simple_differencing=True` and that will allow you to run the specification.

More generally, if the seasonal AR or MA terms were not zero, the model is basically unsupported (i.e. very slow to estimate) for such a large period (and the same is true of R's arima function).

**Comment by sammourad** [comment] 2019-05-16 15:37
@ChadFulton thank you for your time and help on this.
I tried simple_differencing which definitely speeds things up. However, the results are far off.
Here is code snippet (addition to the above) along with comparison to R's forecast$arima

```python
df.to_csv("data/sm_sarimax_issue.csv") # for the R snippet below
split_date = "2018-11-30"
train_df = df.loc[:split_date]
test_df = df.loc[split_date:].iloc[1:]

m = SARIMAX(
    endog=train_df["y"],
    exog=train_df[["exo1", "exo2"]],
    order=(1, 0, 1),
    seasonal_order=(0, 1, 0, 365),
    simple_differencing=True,
)
m_fit = m.fit()
pred = m_fit.forecast(
    test_df.shape[0], exog=test_df[["exo1", "exo2"]]
)

# Visualize
fig = plt.figure(figsize=figsize)
ax = fig.add_subplot(111)
df["y"].plot(figsize=figsize, ax=ax)
pred.plot(figsize=figsize, ax=ax)
ax.set_title("Actual w/ forecast")
ax.set_xlabel("Time")
ax.set_ylabel("Value")

# Focus on forecast
fig = plt.figure(figsize=figsize)
ax = fig.add_subplot(111)
test_df["y"].plot(figsize=figsize, ax=ax)
pred.plot(figsize=figsize, ax=ax)
ax.set_title("Actual w/ forecast - focused")
ax.set_xlabel("Time")
ax.set_ylabel("Value")
```
Time-plot with forecast:
![image](https://user-images.githubusercontent.com/47832587/57867080-5035cd80-77b5-11e9-8963-8069b71cf89c.png)

Focused time-plot with forecast:
![image](https://user-images.githubusercontent.com/47832587/57867037-3eecc100-77b5-11e9-9762-5ef04e8a2030.png)

Results from R's forecast$arima

```R
# Packages
require("forecast")
library(forecast)

# Load data
df = read.csv(file="data/sm_sarimax_issue.csv") # df saved in python (snippet above)
df = df[c("y", "ds", "exo1", "exo2")]
df$ds = as.Date(df$ds, format = "%Y-%m-%d")

train.start = df$ds[1]
train.end = as.Date("2018-11-30")
test.start = as.Date("2018-12-01")
test.end = as.Date(df$ds[length(df$ds)])

inds = seq(train.start, test.end, by = "day")
df.ts = ts(df$y,
            start = c(as.numeric(format(inds[1], "%Y")),
                      as.numeric(format(inds[1], "%j"))),
            frequency = 365)

# Split lookback and horizon
ts.train = window(x = df.ts,
                      start = c(
                        as.numeric(format(train.start, "%Y")),
                        as.numeric(format(train.start, "%j"))
                        ),
                      end = c(
                        as.numeric(format(train.end, "%Y")),
                        as.numeric(format(train.end, "%j"))
                      ))

ts.test = window(x = df.ts,
                 start = c(
                   as.numeric(format(test.start, "%Y")),
                   as.numeric(format(test.start, "%j"))
                   ),
                 end = c(
                   as.numeric(format(test.end, "%Y")),
                   as.numeric(format(test.end, "%j"))
                   ))

# Train and forecast
mod.arima.man = arima(ts.train, order=c(1, 0, 1), seasonal=c(0, 1, 0))
pred.arima.man = forecast(mod.arima.man, h=length(ts.test))
plot(pred.arima.man)
```
R's time plot with forecast:
![image](https://user-images.githubusercontent.com/47832587/57867316-c3d7da80-77b5-11e9-96bf-ce021d0c169a.png)

Do you know where the difference might be coming from?

**Comment by ChadFulton** [comment] 2019-05-16 22:33
The problem is that "simple differencing" does differencing before handling the model, so the forecasts are for the differenced series and not for the original series. You can manually cumulate them back to the original series, but we should do this automatically.

**Comment by sammourad** [comment] 2019-05-20 12:38
Does that mean when simple_differencing is True the model is just returning the differencing itself in the output and nothing else?

**Comment by bashtage** [comment] 2019-05-20 12:40
It is as-if you difference the data your self (y[365:]-y[:-365]) and then run the model without the difference.

**Comment by sammourad** [comment] 2019-05-21 13:20
Thanks Kevin, this explain the results as on the graph! So this will be the middle part of the equation (below), and from what I understand, I'd need to train an arima(1, 0, 1) and add it to the simple differencing model to get the final forecast.

![image](https://user-images.githubusercontent.com/47832587/58099022-a1680780-7b8f-11e9-92ec-b4a7c17c0f80.png)

Is there a better way to get to the final results that I'm overlooking? Maybe without training multiple models?

I'm working with sarimax based off of [this example](http://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_stata.html) please let me know if there is a better/closer example that I'm missing.

Thanks again for your help!

**Comment by utkarshch9** [comment] 2020-07-19 09:47
Hey
I am also facing the same problem of high time and memory while using SARIMAX(with s=365), so is there any solution except the simple differencing one?

**Comment by ChadFulton** [comment] 2020-07-20 01:02
One option in v0.11 is the new `arima.ARIMA` model with the `innovations_mle` algorithm, which allows fitting models with long seasonal effects (although it has some downsides, like not allowing missing values). It can used as follows:

```python
mod = sm.tsa.arima.ARIMA(endog, order=(p, d, q), seasonal_order=(P, D, Q, 365))
res = mod.fit(method='innovations_mle', low_memory=True, cov_type='none')
```

**Comment by ChadFulton** [comment] 2020-07-20 01:02
Closing this issue as answered, plus we have the option that I just gave for fitting these models.

**Closed** 2020-07-20 01:02 UTC
Labels: comp-tsa, comp-tsa-statespace

**Comment by advaitk13** [comment] 2020-07-20 03:45
> One option in v0.11 is the new `arima.ARIMA` model with the `innovations_mle` algorithm, which allows fitting models with long seasonal effects (although it has some downsides, like not allowing missing values). It can used as follows:
> 
> ```python
> mod = sm.tsa.arima.ARIMA(endog, order=(p, d, q), seasonal_order=(P, D, Q, 365))
> res = mod.fit(method='innovations_mle', low_memory=True, cov_type='none')
> ```

does this also work for sm.tsa.arima.SARIMAX?

**Comment by advaitk13** [comment] 2020-07-20 03:50
> One option in v0.11 is the new `arima.ARIMA` model with the `innovations_mle` algorithm, which allows fitting models with long seasonal effects (although it has some downsides, like not allowing missing values). It can used as follows:
> 
> ```python
> mod = sm.tsa.arima.ARIMA(endog, order=(p, d, q), seasonal_order=(P, D, Q, 365))
> res = mod.fit(method='innovations_mle', low_memory=True, cov_type='none')
> ```

does this work with exogenous variables?

**Comment by ChadFulton** [comment] 2020-07-20 03:52
> does this work with exogenous variables?

Yes

**Comment by advaitk13** [comment] 2020-07-20 03:53
> > does this work with exogenous variables?
> 
> Yes

So I can pass in exog=exog_df like in SARIMAX into this ARIMA method?

**Comment by advaitk13** [comment] 2020-07-20 20:32
This is the output I'm getting when I run it:
![Screen Shot 2020-07-20 at 4 31 53 PM](https://user-images.githubusercontent.com/12476578/87983566-9156fb00-caa6-11ea-9033-06966b68a351.png)

**Comment by ChadFulton** [comment] 2020-07-21 03:00
> is it common for the model fitting to take a while? @ChadFulton

It depends on the data, but it could take a while.

> @ChadFulton This is the output I'm getting when I run it:

Yes, the `cov_type='none'` means that the output will not have standard errors, p-values, etc. If you need those, you can do:

```python
res = mod.fit(method='innovations_mle', low_memory=True)
```

but it will take potentially much longer to run.

**Comment by muazzam13** [comment] 2020-11-16 18:37
> 
> 
> One option in v0.11 is the new `arima.ARIMA` model with the `innovations_mle` algorithm, which allows fitting models with long seasonal effects (although it has some downsides, like not allowing missing values). It can used as follows:
> 
> ```python
> mod = sm.tsa.arima.ARIMA(endog, order=(p, d, q), seasonal_order=(P, D, Q, 365))
> res = mod.fit(method='innovations_mle', low_memory=True, cov_type='none')
> ```
are there any other downsides to this? Is there a place I can find out those downsides?

**Comment by ChadFulton** [comment] 2020-11-17 12:08
Each of the three arguments to `fit` is required for the long seasonal models, and each implies different restrictions. In general, these are not problematic, but it depends on what you need:

- The downside to using `innovations_mle` is primarily that it doesn't support missing data. There are also differences in the way that it handles integration (the `d` and `D` specifications), although these differences are likely to be small unless you have relatively few periods.

- The downside to using `low_memory=True` is that you will not have access to output from the Kalman smoother, and you can't perform dynamic in-sample predictions or compute in-sample confidence intervals. However, you can still perform out-of-sample forecasting.

- The downside to using `cov_type='none'` is that you will not get standard errors (or t-stats or p-values) associated with the model parameters.

**Comment by muazzam13** [comment] 2020-11-17 13:21
> 
> 
> Each of the three arguments to `fit` is required for the long seasonal models, and each implies different restrictions. In general, these are not problematic, but it depends on what you need:
> 
>     * The downside to using `innovations_mle` is primarily that it doesn't support missing data. There are also differences in the way that it handles integration (the `d` and `D` specifications), although these differences are likely to be small unless you have relatively few periods.
> 
>     * The downside to using `low_memory=True` is that you will not have access to output from the Kalman smoother, and you can't perform dynamic in-sample predictions or compute in-sample confidence intervals. However, you can still perform out-of-sample forecasting.
> 
>     * The downside to using `cov_type='none'` is that you will not get standard errors (or t-stats or p-values) associated with the model parameters.

Thank you, I understand now.

**Comment by jelc53** [comment] 2022-08-29 11:17
This works for me initially (saving trained model is only 40 Mb), but then I reload model and run `append` to update its state, followed by `forecast` to make an out-of-sample prediction. Now when I resave the model as joblib, it is 2 Gb again. Any tips?
