### ISSUE TITLE
SARIMAX PyMC3 Bayesian estimation example fails

### ISSUE THREAD

**Issue by ilia-sharafutdinov** [statsmodels/statsmodels#7398] opened 2021-04-03 13:00 UTC
The [notebook ](https://github.com/statsmodels/statsmodels/blob/main/examples/notebooks/statespace_sarimax_pymc3.ipynb) fails after sampling the chains, unable to create trace object.

`Sampling 2 chains for 3 tune and 10 draw iterations (6 + 20 draws total) took 1 seconds.
---------------------------------------------------------------------------
MissingInputError: Input 0 of the graph (indices start from 0), used to compute Elemwise{exp,no_inplace}(sigma2_log__), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.`

Python 3.9.1
Theano-PyMC 1.1.2
PyMC3 3.11.2
StatsModels 0.12.2

Complete log attached below.

[error.txt](https://github.com/statsmodels/statsmodels/files/6252586/error.txt)

**Comment by bashtage** [comment] 2021-04-07 14:29
Do you get the error when you don't use Theano-PyMC?  We don't use this package, and the error indicates that it comes from Theano.

**Comment by ilia-sharafutdinov** [comment] 2021-04-07 14:48
Hi, @bashtage! Yes, it's the library I use. Which one should I use instead?

**Comment by bashtage** [comment] 2021-04-07 15:07
It is required, so that is not it.  The error has to do with pickling.  I suspect that something changed in they way they handle multicore. Simple solution is to use `cores=1`.

**Comment by ilia-sharafutdinov** [comment] 2021-04-07 16:14
@bashtage, I tried, but it then fails after performing the simulations. The error in the description is what happens next. Imo, something changed in how they handle the algebra in theano.

**Comment by ilia-sharafutdinov** [comment] 2021-04-09 17:25
Hi, @bashtage! Is there any update on this?

**Comment by ChadFulton** [comment] 2021-04-10 17:08
If the notebook no longer runs, then we may need to get help from someone who is familiar with the current direction of pymc (after several hours of trying, I can't even get a working pymc installation on my Mac due to [this bug](https://github.com/Theano/Theano/issues/6645) which pymc devs [apparently do not want to fix](https://github.com/pymc-devs/aesara/issues/355)).

I will try to run the notebook in linux soon to see if it works for me there.

**Comment by bashtage** [comment] 2021-04-12 10:17
@aeturrell it would be great if you have some time to look into the changes that have occurred upstream.

**Comment by aeturrell** [comment] 2021-04-13 18:35
Hmm.. I know there are a lot of changes happening with Theano as the PyMC3 team take it over. Could be related. @junpenglao if you had a moment, would you be able to take a look at this? You're much more likely to know if there's a quick fix/solution! (If not, I'll take a more in-depth look myself.)

**Comment by junpenglao** [comment] 2021-04-14 08:09
Hi folks,
We have some pretty big refactoring going on right now so installation from HEAD might be a bit bumpy.
I will try to run the notebook on my side and report back.

**Comment by junpenglao** [comment] 2021-04-14 08:53
Here is what I did (based on https://github.com/pymc-devs/pymc3/wiki/Installation-Guide-(MacOS), but conda channel have some weird delay of version so I need to use pip instead):
```shell
conda create -n pymc3-env
conda activate pymc3-env 
conda install -c conda-forge mkl mkl-service statsmodels
conda install jupyter
pip install theano-pymc
pip install pymc3
pip install pandas-datareader
```
And I can reproduce the two issues on the main thread:
- pickling/multi-threading
workaround: use `cores=1`
- missing symbolic input
after sampling, pymc3 will try to compute elementwise data log-likelihood conditioned on the posterior samples. For that it needs the input in raw unbounded space - not sure why but that is not working properly currently. In any case we can skip that step because ArviZ will compute the other diagnostics, and since we don't have a elementwise data likelihood anyway, this is safe to skip by doing `compute_convergence_checks=False`

Overall, the below should work:
```python
# Construct an instance of the Theano wrapper defined above, which
# will allow PyMC3 to compute the likelihood and Jacobian in a way
# that it can make use of. Here we are using the same model instance
# created earlier for MLE analysis (we could also create a new model
# instance if we preferred)
loglike = Loglike(mod)

with pm.Model() as m:
    # Priors
    arL1 = pm.Uniform('ar.L1', -0.99, 0.99)
    maL1 = pm.Uniform('ma.L1', -0.99, 0.99)
    sigma2 = pm.InverseGamma('sigma2', 2, 4)

    # convert variables to tensor vectors
    theta = tt.as_tensor_variable([arL1, maL1, sigma2])

    pm.DensityDist('likelihood', loglike, observed=theta)
    
    # Draw samples
    trace = pm.sample(ndraws, tune=nburn, return_inferencedata=True, cores=1, compute_convergence_checks=False)
```

**Comment by bashtage** [comment] 2021-04-14 11:29
Thanks @junpenglao - that worked for me using recent PyMC3 and dependencies. Fix is in master now.

**Closed** 2021-04-14 11:28 UTC

**Comment by aeturrell** [comment] 2021-04-14 12:45
Thank you @junpenglao!!

**Comment by ChadFulton** [comment] 2021-04-14 23:22
Thanks so much, @junpenglao @aeturrell and @bashtage !

**Comment by ilia-sharafutdinov** [comment] 2021-04-15 04:19
@ChadFulton, @bashtage, @aeturrell, @junpenglao, thank you all! It works now on windows 10 as well.
