### ISSUE TITLE
ValueError: Invalid value for design matrix. Requires a 2- or 3-dimensional array, got 1 dimensions

### ISSUE THREAD

**Issue by mdavala** [statsmodels/statsmodels#5911] opened 2019-07-04 08:01 UTC
I see I am sending two dimensional data but statsmodel throws me error that this numpy array is 1 dimension.

**data in numpy array where I want to do prediction:**
array([[Timestamp('2019-06-29 00:00:22'), 669150459],
       [Timestamp('2019-06-29 00:00:22'), 669185406],
       [Timestamp('2019-06-29 00:00:52'), 670070318],
       ...,
       [Timestamp('2019-07-02 09:44:42'), 103777512],
       [Timestamp('2019-07-02 09:45:12'), 100467360],
       [Timestamp('2019-07-02 09:45:12'), 100567515]], dtype=object)

y.shape
(19302, 2)

**Sample Code:**
mod = sm.tsa.statespace.SARIMAX(y,
                                order=(1, 1, 1),
                                seasonal_order=(1, 1, 1, 12),
                                enforce_stationarity=False,
                                enforce_invertibility=False)
results = mod.fit()
print(results.summary().tables[1])

**Python Traceback:**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-52-fbdee454670a> in <module>()
      3                                 seasonal_order=(1, 1, 1, 12),
      4                                 enforce_stationarity=False,
----> 5                                 enforce_invertibility=False)
      6 
      7 results = mod.fit()

~/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/sarimax.py in __init__(self, endog, exog, order, seasonal_order, trend, measurement_error, time_varying_regression, mle_regression, simple_differencing, enforce_stationarity, enforce_invertibility, hamilton_representation, concentrate_scale, **kwargs)
    535 
    536         # Initialize the fixed components of the statespace model
--> 537         self.ssm['design'] = self.initial_design
    538         self.ssm['state_intercept'] = self.initial_state_intercept
    539         self.ssm['transition'] = self.initial_transition

~/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/representation.py in __setitem__(self, key, value)
    419                 raise IndexError('"%s" is an invalid state space matrix name'
    420                                  % key)
--> 421             setattr(self, key, value)
    422         # If it's a tuple (with a string as the first element) then we must be
    423         # setting a slice of a matrix

~/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/representation.py in __set__(self, obj, value)
     53 
     54         if len(shape) == 3:
---> 55             value = self._set_matrix(obj, value, shape)
     56         else:
     57             value = self._set_vector(obj, value, shape)

~/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/representation.py in _set_matrix(self, obj, value, shape)
     68         # Enforce that the matrix is appropriate size
     69         validate_matrix_shape(
---> 70             self.name, value.shape, shape[0], shape[1], obj.nobs
     71         )
     72 

~/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/tools.py in validate_matrix_shape(name, shape, nrows, ncols, nobs)
   1419         raise ValueError('Invalid value for %s matrix. Requires a'
   1420                          ' 2- or 3-dimensional array, got %d dimensions' %
-> 1421                          (name, ndim))
   1422     # Enforce the shape of the matrix
   1423     if not shape[0] == nrows:

ValueError: Invalid value for design matrix. Requires a 2- or 3-dimensional array, got 1 dimensions

All inputs and suggestions are welcome.

Thanks,
Mohan Raj

**Comment by ChadFulton** [comment] 2019-07-04 15:26
We should clearly have a better error message here, but the problem is that `SARIMAX` models are univariate models and can't handle multivariate `endog`.

**Comment by bashtage** [comment] 2019-07-18 09:54
Have you tried squeezing it to have 1 dimension?

**Comment by LoveenDyall** [comment] 2019-07-30 21:27
Hi I think this is a bug as I have a 1d list like the example here:
https://machinelearningmastery.com/how-to-grid-search-sarima-model-hyperparameters-for-time-series-forecasting-in-python/

**Comment by bashtage** [comment] 2019-07-30 22:12
The example works as expected in master with no error. I think you have some other issue. Is history actually a 1-d pandas Series?

**Comment by bashtage** [comment] 2019-07-30 22:48
Closing since there is no bug in SARIMAX. Best practice is to use a pandas Series with a DatetimeIndex that has a frequency.

**Closed by bashtage** 2019-07-30 22:48 UTC
Labels: comp-tsa, maybe_close

**Comment by aayushagrawal24** [comment] 2019-11-13 06:25
I am still getting this error. I have univariate endogenous variable and bivariate exogenous variable and using the regression with time varying coefficients and SARIMA errors.

```
mod = sarimax.SARIMAX(endog = conversion_series, 
                                            exog = airings_series.iloc[:,:2],
                                            order=param,
                                            seasonal_order=param_seasonal,
                                            initialization='approximate_diffuse',
                                            enforce_stationarity= False,
                                            enforce_invertibility= False,
                                            mle_regression=False,
                                            time_varying_regression=True)
```

Here param = (0,0,0) and param_seasonal = (1,0,0) and the error I am getting is:

```
   1545     if not shape[1] == ncols:
   1546         raise ValueError('Invalid dimensions for %s matrix: requires %d'
-> 1547                          ' columns, got %d' % (name, ncols, shape[1]))
   1548 
   1549     # If we don't yet know `nobs`, don't allow time-varying arrays

ValueError: Invalid dimensions for design matrix: requires 13 columns, got 1
```
