### ISSUE TITLE
Repeated Measures ANOVA

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#749] opened 2013-04-03 16:59 UTC
[Request](http://stackoverflow.com/questions/15790708/how-can-i-perform-a-2-way-repeated-measures-anova-using-statsmodels/15793366) to support repeated measures ANOVA

see #786 for PR

**Comment by tomwallis** [comment] 2015-01-19 22:18
Just wanted to add another bump here. I'm teaching a stats course using Python / statsmodels, and it would be great to have a repeated-measures ANOVA implemented. It's an extremely common design in biomed, psychology and neuroscience. Would help out if I could but I am only an intermediate Python user.

It may help to look into R's implementation of the problem. One way to think about repeated-measures ANOVA is that the error term that a within-subjects factor is tested against is *stratified* or *nested* within subjects. For an example using R, see [here](http://www.psych.upenn.edu/~baron/rpsych/rpsych.html#htoc60). Perhaps Patsy's nesting can provide some help here?

**Comment by josef-pkt** [comment] 2015-01-19 22:59
I was looking at this recently again, trying to replicate some of the test cases of the PR as a linear model, however without success.

The reference looks helpful. For example I never figured out what the corresponding contrast for the tests are, something like  the following paired t-test equivalent
`t.test(hays.mat %*% c(1, 1, -1, -1))`
which uses the difference between means instead of a coding of the difference from the total within subject mean (which is one of the ways of removing subject specific unobserved heterogeneity used in econometrics)

My impression is that we could do most of it with patsy but we still need to create the encodings or contrasts for the different within or between effects.
Also we have anova_lm or now wald_test_terms #2132 as pattern to create F or chisquare tests for a sequence contrasts.

**Comment by josef-pkt** [comment] 2015-01-19 23:09
The other thing I haven't figured out yet in terms of equivalence to a linear model is how much code needs to depend on the specific experimental design, split-plot, cross-over and so on, and how much could be independent of the structure of the experimental design by just using general patsy formulas and contrasts.

**Comment by josef-pkt** [comment] 2015-01-20 01:30
And one more. Are the different test statistics in repeated measures anova separate tests or based on one model? anova_lm has the different types, like type 2 and type 3 anova, while in wald_test_terms I only looked at type 3 (or similar) which tests contrasts on coefficients estimated in the full model.
(AFAIR, in a completely balanced or orthogonal design it doesn't make a difference under standard assumptions.)

**Comment by subhacom** [comment] 2015-02-16 22:51
Waiting eagerly for this.

**Comment by TheChymera** [comment] 2015-02-17 13:08
:+1: we need ANOVA and prospectively even more flexible linear models for python!

**Comment by dengemann** [comment] 2015-02-17 13:15
Guys, why don't you give me a hand to extend the implementation we have in MNE-Python. I don't have time to do the work now but I can assist you. Once we have the generalized m-way rANOVA (a few lines to change only) we can backport it here and wrap it in a native statsmodel API.

**Comment by subhacom** [comment] 2015-02-17 16:57
Thanks for the suggestion. I am still learning the statistics part, but will take a look at MNE and see if I can put my teeth into it.

**Comment by springcoil** [comment] 2015-02-27 15:22
Has there been any progress on this? I'm new to statsmodels - can anyone inform me of how much ground work there has been here.

**Comment by dengemann** [comment] 2015-02-27 15:39
Hi, we implemented a 2 way version in [mne-python](https://github.com/mne-tools/mne-python/blob/master/mne/stats/parametric.py) with two public functions, one for thresholds, one for the actual computation:

https://github.com/mne-tools/mne-python/blob/master/mne/stats/parametric.py#L143

https://github.com/mne-tools/mne-python/blob/master/mne/stats/parametric.py#L182

The implementation is optimized for mass univariate use cases, it estimates thousands of anova models for each observation in a vectorized manner [and is tested against SPSS and R](https://github.com/mne-tools/mne-python/blob/master/mne/stats/tests/test_parametric.py#L10), 'simultaenously'. See this [neuroimaging example](http://martinos.org/mne/dev/auto_examples/stats/plot_cluster_stats_spatio_temporal_repeated_measures_anova.html) in which the rmANOVA is used inside a permutaiton test on a couple of thousands of observations. 

To continue with this, we would need to slightly modify the [contrast machinery](https://github.com/mne-tools/mne-python/blob/master/mne/stats/parametric.py#L115), which is not fully generalized and does not support a one way and muti-way rmANOVA. Once the correct contrasts are computed, the [main function](https://github.com/mne-tools/mne-python/blob/master/mne/stats/parametric.py#L182) will carry out the expected computations without modification.

Unfortunately I don't have time to look into this, because I'm not having such use case in the moment.

It would be nice to generalize the code and make it interfacable / port it to statsmodels. Who ever wants to take a look at it, I'm happy to assist.

**Comment by springcoil** [comment] 2015-02-27 15:48
I'm not having any uses for this personally right now. But ANOVA seems like a good exercise and there is considerable code in your examples. I'll try to have a look at this sometime soon.

**Comment by dengemann** [comment] 2015-05-27 15:22
FYI we just merged https://github.com/mne-tools/mne-python/pull/2153 which implements a general M-way repeated measures ANOVA for balanced designs.

**Comment by josef-pkt** [comment] 2015-05-27 15:45
@dengemann   Thanks
some additional information
https://github.com/mne-tools/mne-python/pull/2153#issuecomment-105757377 and follow up
and 
https://gist.github.com/dengemann/5539403
to see the relationship to R's aov

I skimmed the code, and it looks good to me, and I followed the comments. But I'm too distracted right now to think about what to do with this (for either scipy.stats or statsmodels).

(for extensions in general: We have one GSOC project for MixedGLM and one for MixedLM this year.)

**Comment by dengemann** [comment] 2015-05-27 15:49
> to see the relationship to R's aov

The data from the R script are the data tested against in the unit tests:

https://github.com/mne-tools/mne-python/blob/7bf70e956c24ac5daea4c60e7c6dff230406cf98/mne/stats/tests/test_parametric.py


> (for extensions in general: We have one GSOC project for MixedGLM and one for MixedLM this year.)

Awesome! So far I've understood that getting the entire rANOVA bench done is a matter of assembling the correct design matrices, then GLM does the job.

**Comment by josef-pkt** [comment] 2015-05-27 15:56
> So far I've understood that getting the entire rANOVA bench done is a matter of assembling the correct design matrices, then GLM does the job

My problem is that I never figured out what the design matrices are, especially for a general case with an incomplete factorial design and both within and between effects. So, I never managed to find the **regression equivalent** of rANOVA.

**Comment by dengemann** [comment] 2015-05-27 16:00
Take a look here:

http://www.fil.ion.ucl.ac.uk/~wpenny/publications/rik_anova.pdf

http://www.mrc-cbu.cam.ac.uk//personal/rik.henson/personal/PennyHenson_SPM_06b.pdf

It's pretty illustrative.

The MNE code partially implements these.

**Comment by josef-pkt** [comment] 2015-05-27 16:25
@dengemann Thanks, I very quickly skimmed the second paper, and it looks helpful.

BTW:  We follow the statistics convention where `GLM` is generalized linear model and not general linear model.

**Comment by dengemann** [comment] 2015-05-27 16:26
thanks, excuse my typo, doing to many things at the same time ;)

2015-05-27 18:25 GMT+02:00 Josef Perktold <notifications@github.com>:

**Comment by donaldbraman** [comment] 2016-09-21 17:17
A huge thanks to those working on this, and a bump as I would love to have this as well.

**Comment by louist87** [comment] 2016-09-21 17:42
Hi Donald,

I'm not part of the core statsmodels team, but my impression is that this
issue is currently dead in the water.

Lately I've been using statsmodels' linear mixed-effect models as a drop-in
replacement for rm-anovas.  I suspect you may be able to do so as well.

Louis

On Sep 21, 2016 7:17 PM, "Donald Braman" <notifications@github.com> wrote:

A huge thanks to those working on this, and a bump as I would love to have
this as well.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/statsmodels/statsmodels/issues/749#issuecomment-248680544>,
or mute the thread

**Comment by kshedden** [comment] 2016-09-22 01:21
I don't know anything about the original RE ANOVA code, but I am very familiar with the Statsmodels linear mixed models code.  It should be possible to fit basically any type of random effects ANOVA with our MixedLM.  However we may be missing some small sample degrees of freedom corrections and other inferential tools or outputs that are usually seen with RE ANOVA.  If you have specific requests along these lines please open an issue.

**Comment by yl565** [comment] 2016-11-27 12:31
@josef-pkt Is any one working on RE ANOVA currently. If not, I'd like to work on it. Also, is there any one working on mixed ANOVA?

**Comment by josef-pkt** [comment] 2016-11-27 15:15
@yl565 Nobody is working on it. It was a highly requested method. Most users and statisticians seems to have switched to using MixedLM models as a more modern replacement.

We have #786 which would need heavy refactoring to bring it into a form that fits into our pandas/patsy/statsmodels style.
 https://github.com/scipy/scipy/issues/4913 and the corresponding function in mne-python, I guess: https://github.com/dengemann/mne-python/blob/m-way-ranova/mne/stats/parametric.py#L248
(seems to be for fully balanced design only)

my caveat still applies: I never "figured out* the theoretical background, whether it has a consistent "model" or whether it's just a collection of independently performed F-tests.

What's mixed ANOVA?
Based on https://statistics.laerd.com/spss-tutorials/mixed-anova-using-spss-statistics.php it's just a special case with one within and one between factor?

(The list of assumptions sounds quite restrictive. Based on what I was reading in the last months, I'd like to get, eventually, outlier or heavy-tailed distribution robust methods for most of the models and multivariate tests.)

**Comment by hoechenberger** [comment] 2018-02-21 21:24
I believe this issue was closed via #3303.

**Comment by jona-sassenhagen** [comment] 2019-05-25 13:56
I think so too, closed by #3303

**Comment by PavloFesenko** [comment] 2022-12-10 11:38
@josef-pkt, @jseabold, @ChadFulton, @bashtage Could you guys please close this issue as completed by #3303? Although it was quite interesting to read the implementation history of the repeated measures ANOVA. 😀

**Closed** 2022-12-10 15:00 UTC
Labels: wishlist, type-enh, comp-stats, good first issue
