### ISSUE TITLE
fit_constrained de-duplication

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3985] opened 2017-10-05 18:16 UTC
`GLM.fit_constrained` and `Poisson.fit_constrained` and _almost_ identical to `base._constraints.fit_constrained_wrap`.  The main difference is that the former two do not pass `start_params=params` into `self.fit`.  Is there a compelling reason not to de-duplicate these?

There are several TODO comments in these functions; I'd rather de-dup them before trying to address those issues.  Also all three are places that do one of my least-favorite things: modify df_model&df_resid in-place, so de-duping will move us away from that pattern.

**Comment by josef-pkt** [comment] 2017-10-05 18:28
I doubt I will touch this unless it is a round 2 refactoring.

That is it needs a full review, because it was never reviewed since it was merged.
Some models like those in discrete are waiting for a extra `offset` option.
I think I also have an issue to allow only homogeneous constraints, which should work also with models that don't have offset.

Another item is that it we don't have much score_tests in the models yet, which are another main TODO item and was one of the reasons for fit_constrained.
It's easier to experiment and unit test with just one model class, instead of getting it to work for all.

(It's a bit similar to cov_type, start in one model and work slowly towards full generic support.)

**Comment by jbrockmendel** [comment] 2017-10-05 18:36
> I doubt I will touch this unless it is a round 2 refactoring.

The in-place adjusting of `df_model` and `df_resid` bother me enough that I'll volunteer to take on the round 1 if you'll meet me  half-way and agree to de-duplicate the following verbatim lines duplicated in all three locations:

```
    res._results.params = params
    res._results.normalized_cov_params = cov
    k_constr = len(q)
    res._results.df_resid += k_constr
    res._results.df_model -= k_constr
    res._results.constraints = lc
    res._results.k_constr = k_constr
    res._results.results_constrained = res_constr
```

The main bit that is _not_ verbatim is the call to `self.fit`, where I suspect the differences are irrelevant because of the `maxiter=0` (a matter we can save for another day)

```
# base._constraints.fit_constrained_wrap:
    # create dummy results Instance, TODO: wire up properly
    res = self.fit(start_params=params, maxiter=0,
                   warn_convergence=False) # we get a wrapper back

# Poisson.fit_constrained:
        # create dummy results Instance, TODO: wire up properly
        res = self.fit(maxiter=0, method='nm', disp=0,
                       warn_convergence=False) # we get a wrapper back

# GLM.fit_constrained:
        # create dummy results Instance, TODO: wire up properly
        res = self.fit(start_params=params, maxiter=0) # we get a wrapper back
```

**Comment by josef-pkt** [comment] 2017-10-05 18:37
> modify df_model&df_resid in-place, 

I only looked at Poisson: It doesn't modify the model.df_xxx only the results instance, so at least it doesn't cause stale state, out-of-sync attributes.
see #2393 for the general issue, and some ideas how to avoid "retrofitting" the results instance

**Comment by jbrockmendel** [comment] 2017-10-05 18:43
> It doesn't modify the model.df_xxx only the results instance, so at least it doesn't cause stale state, out-of-sync attributes.

Yah, it's not an especially big deal, but it still bothers me in part because it shows up when I grep for `(df_model|df_resid) [\+\-]=`.

**Comment by josef-pkt** [comment] 2017-10-05 18:48
>  ... and agree to de-duplicate the following verbatim lines duplicated in all three locations

The problem is that I don't want to de-dup and hide away one piece of the ugly code. First the entire method duplication needs to go away. Second, the design for (re)creating results instances is not yet clear, so I don't know yet how to remove the ugly parts of the code.

For sure there would be things that could be improved in the code first, but overall it is more the size of a topic week where the overall design needs to be evaluated or at least the main problems get a better solution.

**Comment by jbrockmendel** [comment] 2017-10-05 21:55
> The problem is that I don't want to de-dup and hide away one piece of the ugly code. First the entire method duplication needs to go away. Second, the design for (re)creating results instances is not yet clear, so I don't know yet how to remove the ugly parts of the code.

Please reconsider.  Do not let the perfect be the enemy of the good.

There will always be more Topic Week-sized issues than weeks in which to address them.  For many things, small (ideally small enough that they are trivial for a reviewer to verify correctness) incremental improvements are the only type of improvements we are going to get.

**Comment by josef-pkt** [comment] 2017-10-06 01:12
Even though I agree in general, I prefer making changes when there is an actual demand for it, e.g. bug fixes, smaller extensions or preparing for bigger extensions, at least that's where I try to put my priority.

> incremental improvements are the only type of improvements we are going to get

However, this incremental improvements are not enough in some cases.
E,g, the contrast here versus MNLogit
MNLogit is essentially settled as a model, but we need to fix the things that are currently not working because the pattern differs. Each incremental change works toward finishing up the missing pieces, and anything that is fixed now, does not need to be fixed again.

In cov_type, fit_constrained and similar, another round of big refactoring is needed. Why do we spend now time on small refactorings that won't survive the next big round, in maybe a year or so?

(After a bit of issue triage, I'm back to 25 bug issues that should be checked and possibly fixed for 0.9, first column in https://github.com/statsmodels/statsmodels/projects/8 )

**Comment by jbrockmendel** [comment] 2017-10-06 03:10
OK, I'm hereby committing to this being my last post on the thread, so you'll get the last word.

> I prefer making changes when there is an actual demand for it, e.g. bug fixes, smaller extensions or preparing for bigger extensions

This is a recipe for ignoring technical debt.

> However, this incremental improvements are not enough in some cases.

I barely know how to parse this sentence.  Do your preferences [not satisfy IIA](https://www.youtube.com/watch?v=0LPIc5JIFwk)?  The option space here is ["status quo", "slightly better than the status quo"].  

> In cov_type, fit_constrained and similar, another round of big refactoring is needed.

There's risk of a catch-22 here.  I could make a big PR that de-duplicates `ModelClasses.get_robustcov_results` in one swoop, but that would be a big enough diff as to not be obvious at a glance.  You would (correctly) respond that you have higher priorities.  By contrast, you (or Kevin, or Chad [or me if it wasn't my PR]) can pretty immediately* confirm that #3974 is cut/paste, affects zero logic, and makes a small dent in this code smell.  And small improvements add up, especially if your attention ceases to be the limiting factor.

\* Under a non-trivial topology, the size of the PR can be reduced to satisfy any finite number of reviewers' preferred definition of "immediately".

> MNLogit is essentially settled as a model, but we need to fix the things that are currently not working because the pattern differs.

Consider incentives.  I've been working on MNLogit for bill-paying work, so have the Issues fresh in mind and have a pile of code for handling corner cases.  But turning that into a PR(s) would be _really_ nontrivial, and I expect that if I did so, you'd either say a) it doesn't solve everything so No or b) it is too big so Not Now.

> Each incremental change works toward finishing up the missing pieces, and anything that is fixed now, does not need to be fixed again.

This should apply to `fit_constrained` just as well.  De-duplicating and cleaning up code smells makes it more readable and easier to approach the problem when it does become a priority.

> another round of big refactoring is needed. Why do we spend now time on small refactorings that won't survive the next big round, in maybe a year or so?

1) Because small refactorings add up, make bigger refactorings either easier or unnecessary.
2) Because of specialization of labor: #3974 doesn't require any big decision-making about internals, separates code-smell-alleviation from the Big Picture stuff that requires your Serious Attention.
3) Because I'm a Bayesian.  When I read "maybe a year or so" I look at `statsmodels.interface` which has been an empty `__init__.py` file for 6 years, `discrete_model.Weibull` that has been commented-out for 5, and `sandbox.mle` that starts with the docstring `'''What's the origin of this file? It is not ours.` and hasn't been touched in 4 years.

None of which is to say you're not doing a yeoman's job.  The fact that TODOs are piling up faster than they can be addressed means there's an active community of users and contributors.  While I  am asking you to reconsider some decision-making, the closest thing I have to a complaint is that there isn't two of you.  You've got a Sisyphean task.

greping for "TODO" turns up 924 matches.  "FIXME" turns up another 21.  `flake8 statsmodels | grep undefined` shows 135 `NameError`s waiting to happen*.  Surely some of these can be delegated so as to not require your direct attention.

\* In fairness, 28 of these are complaints about "from .data import *; unable to detect undefined names" and the many of the rest are in `sandbox`.

Removing unused code and addressing small code smells is a way that semi-literates like myself can help fight this losing battle against entropy.

**Comment by josef-pkt** [comment] 2017-10-06 15:04
Ok, some general thought on statsmodels development and me

First I'm not working as much on statsmodels as in the old days. I'm not getting paid, and I need to have some fun in life and when working on statsmodels (e.g. I prefer now a book to statsmodels maintenance in the (late) evenings,.)

Bringing up topic weeks was an attempt to concentrate in time my involvement in topics that are not urgent. It is very difficult for me to look at something without having or getting me to think, which often takes time. Some things can be merged based on general impression and unit tests especially new, still "experimental" features. Other parts are taken care of by Kerby, Chad, Kevin, or Tom.

Overall statsmodels is a huge construction site including still dirt on the floor, many sticky tags (TODOs), parts of the building plan spread over all areas, and some parts are temporary shacks, which give us a roof but not a solid building. Additionally we have leaks all over the place, in some places just tiny ones, in other places still big holes. And it some cases, if we try to plug one hole it just opens up a hole in another part.

My problem is that when I look at decorating a shack or taping over a hole, then I start to think about where we need a new window or more solid walls, or replace the entire shack and the building plan for the full replacement, either the next larger or more solid shack or a permanent building.

There are two types of limitations, one where we have the design or plan but lack the wo/manpower and second where we don't know what design will work for a permanent solution, and we use the "shacks" in the mean time. Whether we should also clean up and decorate the shacks is a secondary issue that depends on the circumstances and time horizon.

Positive examples: 
I have been working on GLM for several years, partially to figure out what the plan is. We had and have several contributors to fix and extend it and it will be close to feature complete and solid. Although there are still many things that can be added.
More count models like zero-inflated and hurdle models has been on the roadmap for a long time. We had a rough plan and some prototypes and finally the GSOC provided the manpower. However, while going through or working on discrete_model, I opened more issues than I closed because all over the place I saw leaks or designs that don't work for future extensions. (As aside I also fixed some of those leaks.)

Recent negative examples, that I just ran into:
gofplots: A sore point for years. An innocent looking bugfix #3547 that most likely causes a problem somewhere else. The problem is that we need a plan #3981.
emplike/AFT: #3629 I don't have much of an idea, except that it will several days just to figure out what it is supposed to do, or maybe there is a quick fix. AFT/parametric survival models is another topic like the new count models. Some pieces are spread out through the code, but there is no systematic plan and development.
margins/predict: High priority in terms of usage, but they are still shacks, even if margin is a pretty solid shack with parts of the full building. (I didn't make smaller changes to margins because I have only a very vague Plan, and we don't have currently another expert on margins.)

BTW: I told you in another issue that fixing MNLogit will get priority treatment.

The only real way out is to get more experienced maintainers for parts of statsmodels. 
(For me this would mean that I don't have to jump around so much, and I could get lost in some of my topic weeks without blocking statsmodels development.)

**Comment by josef-pkt** [comment] 2017-10-06 15:48
`https://www.today.com/home/fixer-upper-season-4-finale-little-shack-prarie-t109807` :)

**Comment by josef-pkt** [comment] 2017-10-07 20:08
(i wrote this yesterday but got distracted before hitting the button)
One thing I wanted to mention before I got distracted by "shacks"

My main criterion for code style and cleanliness is how long it takes me to understand a piece of code or function or method, to get an idea about the underlying structure and being able to spot possible bug. Uniformative names, having to jump around a long time to find the necessary information and lack of basic formatting can make this much longer than needed. The jumping around is often unavoidable, but it has to be justified by it satisfying a specific need in the algorithm or code.

It is one of my basic task to come up with good, quick guesses when somebody has an example with a problem, whether it's a bug or a feature/limitation, and what are the most likely bug candidates or pieces of code that makes something possible or impossible.
(e.g. VAR has overall a good structure, but names are quite confusing/obfuscating.)

**Closed** 2018-03-30 18:55 UTC
Labels: comp-base, comp-discrete, comp-genmod, type-refactor
