### ISSUE TITLE
ModuleNotFoundError: No module named 'statsmodels.regression.rolling'

### ISSUE THREAD

**Issue by hejujoma** [statsmodels/statsmodels#6150] opened 2019-09-05 07:47 UTC
Trying to apply the rolling regression but the following error shows up:

ModuleNotFoundError: No module named 'statsmodels.regression.rolling'

INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0

Statsmodels
===========

Installed: 0.10.0 (C:\Users\jonas\Anaconda3\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.13 (C:\Users\jonas\Anaconda3\lib\site-packages\Cython)
numpy: 1.16.4 (C:\Users\jonas\Anaconda3\lib\site-packages\numpy)
scipy: 1.3.1 (C:\Users\jonas\Anaconda3\lib\site-packages\scipy)
pandas: 0.25.1 (C:\Users\jonas\Anaconda3\lib\site-packages\pandas)
    dateutil: 2.8.0 (C:\Users\jonas\Anaconda3\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\jonas\Anaconda3\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.1.1 (C:\Users\jonas\Anaconda3\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.13.2 (C:\Users\jonas\Anaconda3\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.7.0 (C:\Users\jonas\Anaconda3\lib\site-packages\IPython)
    jinja2: 2.10.1 (C:\Users\jonas\Anaconda3\lib\site-packages\jinja2)
sphinx: 2.1.2 (C:\Users\jonas\Anaconda3\lib\site-packages\sphinx)
    pygments: 2.4.2 (C:\Users\jonas\Anaconda3\lib\site-packages\pygments)
pytest: 5.1.1 (C:\Users\jonas\Anaconda3\lib\site-packages)
virtualenv: Not installed

**Comment by emilmirzayev** [comment] 2019-09-10 08:35
There is `statsmodels.regression.rolling.RollingOLS` in dev version, consider updating the version to dev.
Documentation [here>](https://www.statsmodels.org/dev/generated/statsmodels.regression.rolling.RollingOLS.html#statsmodels.regression.rolling.RollingOLS)

**Comment by hejujoma** [comment] 2019-09-10 10:14
In Conda, how to update to the statsmodel developer version?

**Comment by bashtage** [comment] 2019-09-10 10:28
You cannot.  If you have a C compiler available (or can install one), you can install the latest dev version using

pip install git+https://github.com/statsmodels/statsmodels.git --upgrade

**Comment by bashtage** [comment] 2019-11-27 16:51
Closing since no action needed.

**Closed by bashtage** 2019-11-27 16:51 UTC
