### ISSUE TITLE
Regression t test calculation issue

### ISSUE THREAD

**Issue by wzhtc** [statsmodels/statsmodels#6213] opened 2019-10-26 14:11 UTC
#### Describe the bug

I compared the calculation of statsmodels OLS tvalue versus a straight forward econometric OLS tvalue and found they are different.

#### Code Sample, a copy-pastable example if possible
```python
import numpy as np
import statsmodels.api as sm
np.random.seed(1)
n = 40
x = np.random.normal(1, 1, n)
y = 8 * x + np.random.normal(0, 1, n)

mod = sm.OLS(y, x)
res = mod.fit(method='pinv')
print(res.params, res.tvalues) # [8.12308502] [72.25682714]

xx = np.sum(x*x)
xy = np.sum(x*y)
beta = xy / xx
resi = y - beta * x
resi_var = np.var(resi, ddof=1) / xx
tvalue = beta / np.sqrt(resi_var)
print(beta, tvalue) # 8.123085020673265 72.5022560464012
```

#### Expected Output
The statsmodels tvalue is 72.25682714 and a straight forward formula calculation value is 72.5022560464012. There is a 0.25 difference in the calculation.
Is this some precision issue?

**Comment by josef-pkt** [comment] 2019-10-26 14:18
quick guess

you are regressing without a constant but then use np.var which demeans residuals
`resi_var = np.var(resi, ddof=1) / xx`

**Comment by wzhtc** [comment] 2019-10-26 15:05
@josef-pkt demean should not effect variance right. You could try other degree of freedom, it will still be different.

**Comment by bashtage** [comment] 2019-10-26 15:36
Statsmodels is correct. Your x does not have an exact mean zero so by
demeaning you are reducing the magnitude of the denom in the variance when
the shows up as an increase in the variance.

If you replace your var call with an inner product divided by nobs you will
get the right answer. Your use of ddof=1 is also not correct.

**Comment by bashtage** [comment] 2019-10-26 15:37
Closing since no error.

**Closed** 2019-10-26 15:37 UTC

**Comment by josef-pkt** [comment] 2019-10-26 17:46
aside: If there is a constant in the regression, then the OLS residuals have zero mean. However, that is not true in general when there is no constant in the model.
