### ISSUE TITLE
Getting Fitted values of endogenous variables in a custom state space model

### ISSUE THREAD

**Issue by vikaskumar30** [statsmodels/statsmodels#6101] opened 2019-08-14 20:55 UTC
Hi @ChadFulton 

I am currently trying to fit a state space model (8 variable, 4 state model) with some mixed frequency variables (weekly, monthly and quarterly), represented at a daily frequency. (All of them are stock variables, so there are NaNs for most of them).

Now my question is that when I fit this custom state space model, I was expecting
mod.predict()  
to give me fitted values for these variables at the daily frequency.
But it gives me fitted values for only those days where endogenous variables had values, rest of the days have NaNs like the endogenous variables.

Is there a way to get estimates of these variables for each day as I have daily values for the filtered state and smoothed state. Is there a way to back out the estimated values of endogenous variables at each day.

Thanks

**Comment by ChadFulton** [comment] 2019-08-15 01:14
Thanks for reporting this. What version of Statsmodels are you using? Also, if possible, please provide a small working example that shows the problem.

**Comment by vikaskumar30** [comment] 2019-08-15 23:51
Hi @ChadFulton 

I am using version 0.9.

[input_data.xlsx](https://github.com/statsmodels/statsmodels/files/3507531/input_data.xlsx)


```import pandas as pd
import numpy as np
import statsmodels.api as sm



endog=pd.read_excel("input_data.xlsx",sheet_name="endog",index_col=0,header=0)
exog=pd.read_excel("input_data.xlsx",sheet_name="exog",index_col=0,header=0)
transition_series=pd.read_excel("input_data.xlsx",sheet_name="transition",index_col=0,header=0) 

class SSM(sm.tsa.statespace.MLEModel):
    def __init__(self, endog, exog):
        # Model order
        k_states = 4
        k_posdef = 1
        # k_endog=df_stage1_endog_subset
        nobs=len(transition_series)

        super(SSM, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states, nobs=nobs)
        self.exog = exog.values
        
        self.ssm['transition'] = np.zeros((self.k_states, self.k_states, self.nobs))
        # Initialize the matrices
        for i in range(k_states):
            if i==0:
                self.ssm['transition', :, 0, :] = 0.9
            else:
                self.ssm['transition', i, i, :] = transition_series.iloc[:,i-1].values.ravel()
        self.ssm['selection', :] = 1.
        self.ssm['state_cov', 0, 0] = 0.19
        self.ssm['obs_intercept'] = np.zeros((self.k_endog, self.nobs))
        self._obs_cov_idx = ('obs_cov',) + np.diag_indices(self.k_endog)

    @property
    def param_names(self):
        return [
            'ssm.x10', 'ssm.x20', 'ssm.x30', 'ssm.x40', 'ssm.x50', 'ssm.x60',
            'ssm.p11', 'ssm.p21', 'ssm.p31', 'ssm.p41', 'ssm.p51', 'ssm.p61',
            'ssm.const1', 'ssm.const2', 'ssm.const3', 'ssm.const4', 'ssm.const5', 'ssm.const6',
            'ssm.u1', 'ssm.u2', 'ssm.u3', 'ssm.u4', 'ssm.u5', 'ssm.u6']

    @property
    def start_params(self):
        return  [-0.005643340783663799,
        0.3062255671714733,
        0.5083226660631098,
        0.07425577300908659,
        0.15491004789578577,
        0.05948574287119217,
        2.274766872958943,
        0.199196301071937,
        -0.17729861617184545,
        0.5909576890454198,
        -0.05815267342380495,
        0.2829628868911458,
        0.07440573991913507,
        1.6500548850889984,
        2.8677136684481996,
        0.7579482077087132,
        3.0279568847003064,
        2.0941371291551203,
        0.029455245849725368,
        9.108940907469428,
        12.122414564280144,
        2.242234193176364,
        7.905679222759664,
        3.2134874025160207]

    def transform_params(self, unconstrained):
        constrained = np.zeros(unconstrained.shape, unconstrained.dtype)
        constrained[:unconstrained.shape[0]-self.k_endog] = unconstrained[:unconstrained.shape[0]-self.k_endog]
        constrained[unconstrained.shape[0]-self.k_endog:unconstrained.shape[0]] = unconstrained[unconstrained.shape[0]-self.k_endog:unconstrained.shape[0]]**2
        return constrained

    def untransform_params(self, constrained):
        unconstrained = np.zeros(constrained.shape, constrained.dtype)
        unconstrained[:unconstrained.shape[0]-self.k_endog] = constrained[:unconstrained.shape[0]-self.k_endog]
        unconstrained[unconstrained.shape[0]-self.k_endog:unconstrained.shape[0]] = constrained[unconstrained.shape[0]-self.k_endog:unconstrained.shape[0]]**0.5
        return unconstrained

    def update(self, params, **kwargs):
        params = super(SSM, self).update(params, **kwargs)

        self.ssm['design', 0, 1] = params[0]
        self.ssm['design', 1:5, 2] = params[1:5]
        self.ssm['design', 5, 3] = params[5]
        
        const = params[12:18]
        beta = params[6:12]
        self.ssm['obs_intercept'] = (const + self.exog * beta).T
        self.ssm[self._obs_cov_idx] = params[18:24]
        
mod = SSM(endog=endog, exog=exog)
mod.update(mod.start_params)

""" Fit it using MLE """
res=mod.fit(disp=False)
print(res.summary())
res.predict()
res.filtered_state
```

you will see that it gives me fitted values for only those days where endogenous variables had values, rest of the days have NaNs like the endogenous variables.

**Comment by ChadFulton** [comment] 2019-08-16 01:37
The values of `res.predict()` that are `NaN` correspond to values of `exog` that are `NaN`. Since `endog` depends on `exog`, it cannot compute a predicted value for an observation without knowing what the associated `exog` is.

(Closing as answered, but feel free to follow up if you have other comments / questions).

**Closed by ChadFulton** 2019-08-16 01:37 UTC
Labels: comp-tsa-statespace

**Comment by vikaskumar30** [comment] 2019-08-16 02:02
Hi @ChadFulton,
Thanks for explaining this. 

My question , is that is there a way to get estimates of endog variables at every step. I ask this as I assume these variables would be loading on the common factor(filtered/smoothed) whose values are available at each step.

Thanks

**Comment by ChadFulton** [comment] 2019-08-16 02:25
To do that you would have to make some kind of assumption about `exog`.

Your model is:

`y = x * beta + Z alpha + epsilon`

The prediction is (because `E[epsilon] = 0`):

`E[y] = E[x] * beta + Z E[alpha]`

To form `E[y]` you must have values for each of these:

- `E[x]` is some assumed value for `exog`
- `beta` are the regression coefficients
- `Z` is the "design" matrix
- `E[alpha]` is some estimated value for the unobserved state, and different versions are available depending on the information you want to use in making your predictions. `res.smoothed_state` uses information from the entire dataset (while `res.predicted_state` and `res.filtered_state` use less information).

So the fitted state space model gives you `beta`, `Z`, and `E[alpha]`, but it cannot give you predictions of `y` without some kind of assumption about `E[x]`.

If you want to assume that `E[x] = 0` - which is probably a very poor assumption - then, you could do:

```python
predictions = mod['design'].dot(res.smoothed_state)
```

**Comment by vikaskumar30** [comment] 2019-08-16 02:39
Thanks for explaining this.

**Comment by vikaskumar30** [comment] 2019-08-19 21:59
Hi @ChadFulton 
A small query related to the above model.
If I want to create a similar coincident index to what you had shown here:
https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_dfm_coincident.html

Would my computation of factor similar to your factor in compute_coincident_index function, i.e
``` spec = res.specification
    design = mod.ssm['design']
    transition = mod.ssm['transition']
    ss_kalman_gain = res.filter_results.kalman_gain[:,:,-1]
    k_states = ss_kalman_gain.shape[0]

    W1 = np.linalg.inv(np.eye(k_states) - np.dot(
        np.eye(k_states) - np.dot(ss_kalman_gain, design),
        transition
    )).dot(ss_kalman_gain)[0]

    # Compute the factor mean vector
    factor_mean = np.dot(W1, dta.loc['1972-02-01':, 'dln_indprod':'dln_emp'].mean())

    # Normalize the factors
    factor = res.factors.filtered[0]
    factor *= np.std(usphci.diff()[1:]) / np.std(factor)
```

**Comment by vikaskumar30** [comment] 2019-08-20 21:18
Hi @ChadFulton 
Just following up on this, if you got a chance to see this

**Comment by ChadFulton** [comment] 2019-08-20 22:24
That particular set of steps is based on Stock and Watson's econometric model, which had a particular form that required them to back out a constant term for their common component that was estimated in differenced form. I don't know if you have that requirement or not.

**Comment by vikaskumar30** [comment] 2019-08-20 22:29
Hi @ChadFulton ,
I want just the factor mean part. The common component here is estimated in log differenced form.
if I am just looking to reconstruct the factor mean in this case,
 ```W1 = np.linalg.inv(np.eye(k_states) - np.dot(
        np.eye(k_states) - np.dot(ss_kalman_gain, design),
        transition
    )).dot(ss_kalman_gain)[0] ```
The transition matrix here is 4 * 4 * 16161, so want know to understand how to obtain W1 in this case.

**Comment by ChadFulton** [comment] 2019-08-20 22:33
The existence of W(1) is from the model of Stock and Watson. If you want to make the same assumptions as their model, then based on your state space form, it looks like you could use the same computational steps to get W(1) and similarly estimate `delta = W(1) dy.mean()`, where delta is the mean of the undifferenced common component.

**Comment by vikaskumar30** [comment] 2019-08-20 22:38
Hi @ChadFulton ,
This part in W1 gives me an error:
 ```W1 = np.linalg.inv(np.eye(k_states) - np.dot(
        np.eye(k_states) - np.dot(ss_kalman_gain, design),
        transition
    )).dot(ss_kalman_gain)[0]```

In this case, the design matrix is of size 6 * 4, transition matrix is of size 4 * 4 * 16161 and k_states = 4..
So this part gives an error:
       np.dot(np.eye(k_states) - np.dot(ss_kalman_gain, design),transition)

as np.eye(k_states) - np.dot(ss_kalman_gain, design) is of shape 4 * 4, whereas transition is of shape 4 * 4 * 16161

**Comment by ChadFulton** [comment] 2019-08-20 23:38
Ah, sorry, yes I see you have a time-varying transition matrix.

That will invalidate this approach because the model of Stock and Watson has a time-invariant transition matrix, and that implies that the Kalman gain converges to a steady-state matrix, whereas that is not necessarily the case here.

You may be able to modify their approach to fit your situation, but that depends on your model.

**Comment by vikaskumar30** [comment] 2019-08-21 00:20
Hi @ChadFulton 
Could you guide me how to do this.
The state space model looks like this.

Observation eqn:
Y(t) =  Z*a(t) + e(t)
where Z is a 6 * 4 matrix,
Z=
[[0,0,x10,0],
[0,x20,0,0],
[0,x30,0,0],
[0,x40,0,0],
[0,x50,0,0],
[x60,0,0,0]]
where x's are params to be estimated

and e(t) is error matrix, e~(0,V), where V is
[[var1, 0 ,0 , 0 , 0 , 0],
[0,var2,0,0,0,0],
[0,0,var3,0,0,0],
[0,0,0,var4,0,0],
[0,0,0,0,var5,0],
[0,0,0,0,0,,var6]]

and Y(t)=
[[endog1-const1-p11*exog1],
[endog2-const2-p21*exog2],
[endog3-const3-31*exog3],
[endog4-const4-p41*exog4],
[endog5-const5-p51*exog5],
[endog6-const6-p61*exog6]]
where const and p are params to be estimated.

State eqn:  a(t) = T*a(t-1) + R*n(t)
 where, n(t) ~ (0, S)



T =    [[0.9,  0.0,      0.0,      0.0]
           [0.9,  TS1,   0.0,      0.0]   
           [0.9,  0.0,      TS2,   0.0]   
           [0.9,  0.0,      0.0,      TS3]]
Where TS1, TS2 and TS3 are series

R=np.ones((4,1))

**Comment by ChadFulton** [comment] 2019-08-21 03:32
Yes, this model does not fit into Stock and Watson's model framework. I guess you are running a mixed frequency dynamic factor model, and so that literature would be the place to check to see if anyone has thought about constructing an index in the non-stationary case. I'm not familiar enough with that literature well enough to know.

**Comment by vikaskumar30** [comment] 2019-08-22 20:46
Hi @ChadFulton ,
Reading the Stock and Watson 1991 paper, so he has mentioned on page 11 i.e eqn 17 
![image](https://user-images.githubusercontent.com/53444346/63547079-5399cd00-c4f9-11e9-9539-fcf485cf4b62.png)

![image (1)](https://user-images.githubusercontent.com/53444346/63547510-4f21e400-c4fa-11e9-8b20-af72f2c583d8.png)


I dont understand how the G(t) * Beta vanishes in eqn 18. It is mentioned that Beta is concentrated out of likelihood, does this mean we can assume it to be 0 in steady state.

Also considering the case where transition matrix is time variant. Here if I assume eqn 17 and 18, then it would become
(I - KL)a = G(t)Y(t) - G(t) * Beta, where
K = (I - G(t) * Z(t)) * T(t) and where G(t) = P(t|t-1) * Z' * inv(Ft ).

Now I am planning to do the inverse of (I-KL) at each t, and selecting the first row as weight and basically constructing time variant weight W1. In the above representation, I would be taking the 4 * 4 transition matrix at each time t.  

My query is that, does the filter results have Kalman Gain i.e G(t) computed at each step. if not, is there a way to compute this. Second, Could I assume that G(t) * Beta is zero as the author assumes in eqn 18, or is this a wrong assumption.

Also getting time variant weights and then taking its dot product with the endogenous dataset and then taking its mean, could be considered as the factor mean.

Thanks

**Comment by ChadFulton** [comment] 2019-08-23 01:24
Ultimately, with a time-varying transition matrix, your model does not match that of Stock and Watson, so you can't just use what they did. My guess (but I don't know) would be that you have a cycling Kalman gain matrix, which may mean that there is something analogous that you can do. You might be better off asking this question on cross validated, since it's not really an issue with Statsmodels.
