### ISSUE TITLE
BUG: ExponentialSmoothing returns NaNs from forecast method without any error

### ISSUE THREAD

**Issue by MichalChromcak** [statsmodels/statsmodels#6243] opened 2019-11-12 08:01 UTC
#### Describe the bug

ExponentialSmoothing is returning NaNs from the forecast method. 

##### Expected output
Values being in the result of forecast/predict method or exception raised in case model should return NaNs (ideally already in fit). Hint to the user how to fix it would also be nice.

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing

y = [2342., 2226., 2487., 3082., 2735., 2178., 1717., 2182., 2215., 1663., 1067., 1261.,
     1073.,  986.,  559.,  990., 1561., 1665., 1528., 1807., 1402., 1045.,  981., 1369.,
     1417., 1317., 1256., 1574., 1652., 1479., 1427., 1658., 1738., 1579., 1460., 1863.,
     1749., 1422., 1189.,  972.,  949., 1028.,  660.,  806., 1049.,  974.,  800.]

X = pd.date_range(start='2000-09-30', periods=len(y), freq='Q').astype(str)

endog = pd.DataFrame(X).assign(y=y).set_index(0)

exp_smooth = ExponentialSmoothing(endog=endog, 
                                  damped=True, 
                                  dates=None,
                                  freq=None,                                  
                                  missing='none', 
                                  seasonal='add', 
                                  seasonal_periods=4, 
                                  trend='mul')
```
##### Convergence and RunTime warnings during fit
```python
exp_smooth_fitted = exp_smooth.fit()
# working possibilities found
# exp_smooth_fitted = exp_smooth.fit(**{'smoothing_seasonal':0.1})
# exp_smooth_fitted = exp_smooth.fit(**{'use_boxcox':True})
```
```
/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:163: ValueWarning: No frequency information was provided, so inferred frequency Q-DEC will be used.
  % freq, ValueWarning)
/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/statsmodels/tsa/holtwinters.py:725: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  ConvergenceWarning)
/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/statsmodels/tsa/holtwinters.py:894: RuntimeWarning: invalid value encountered in power
  (alphac * trended(lvls[i - 1], dampen(b[i - 1], phi)))
/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/statsmodels/tsa/holtwinters.py:897: RuntimeWarning: invalid value encountered in power
  (betac * dampen(b[i - 1], phi))
/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/statsmodels/tsa/holtwinters.py:899: RuntimeWarning: invalid value encountered in power
  (gamma * trended(lvls[i - 1], dampen(b[i - 1], phi))) + \
/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/statsmodels/tsa/holtwinters.py:905: RuntimeWarning: invalid value encountered in power
  b[:nobs] = dampen(b[:nobs], phi)
```
##### NaNs in forecast
```python
exp_smooth_fitted.forecast(5)
```
```
2012-06-30   NaN
2012-09-30   NaN
2012-12-31   NaN
2013-03-31   NaN
2013-06-30   NaN
Freq: Q-DEC, dtype: float64
```
##### NaNs in MLE 
```python
exp_smooth_fitted.mle_retvals
```

```python
      fun: nan
 hess_inv: <10x10 LbfgsInvHessProduct with dtype=float64>
      jac: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
  message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 231
      nit: 0
   status: 2
  success: False
        x: array([2.63157895e-01, 1.05263158e-01, 0.00000000e+00, 1.65683333e+03,
       9.65586667e-01, 5.26315789e-01, 6.85166667e+02, 5.69166667e+02,
       8.30166667e+02, 1.42516667e+03])
```
##### Zero in gamma
```python
exp_smooth_fitted.summary()
```
```python
 ExponentialSmoothing Model Results                       
================================================================================
Dep. Variable:                    endog   No. Observations:                   47
Model:             ExponentialSmoothing   SSE                                nan
Optimized:                         True   AIC                                nan
Trend:                   Multiplicative   BIC                                nan
Seasonal:                      Additive   AICC                               nan
Seasonal Periods:                     4   Date:                 Tue, 12 Nov 2019
Box-Cox:                          False   Time:                         08:32:59
Box-Cox Coeff.:                    None                                         
=================================================================================
                          coeff                 code              optimized      
---------------------------------------------------------------------------------
smoothing_level               0.2631579                alpha                 True
smoothing_slope               0.1052632                 beta                 True
smoothing_seasonal             0.000000                gamma                 True
initial_level                 1656.8333                  l.0                 True
initial_slope                 0.9817375                  b.0                 True
damping_slope                 0.5263158                  phi                 True
initial_seasons.0             685.16667                  s.0                 True
initial_seasons.1             569.16667                  s.1                 True
initial_seasons.2             830.16667                  s.2                 True
initial_seasons.3             1425.1667                  s.3                 True
---------------------------------------------------------------------------------
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

Values being in the result of forecast/predict method or exception raised in case model should return NaNs (ideally already in fit). Hint to the user how to fix it would also be nice.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0
OS: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

statsmodels
===========

Installed: 0.11.0dev0+543.gc45cd757b (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.13 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/Cython)
numpy: 1.16.4 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/numpy)
scipy: 1.3.1 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/scipy)
pandas: 0.25.2 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.0 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.1.1 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.13.2 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.9.0 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/IPython)
    jinja2: 2.10.1 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.4.2 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages/pygments)
pytest: 5.0.1 (/Users/michalchromcak/miniconda3/envs/sias_backend/lib/python3.7/site-packages)
virtualenv: Not installed
</details>

**Comment by ChadFulton** [comment] 2019-11-13 02:35
Thanks very much for this report, and especially for all the detail you included.

**Comment by ChadFulton** [comment] 2019-11-13 03:05
Hmm, I see that in ETS, the type of model you've specified (multiplicative trend but additive seasonal) is not allowed:

```R
ets(y, model="AMA", damped=True)
```

gives

```
Error in ets(y, model = "AMA", damped = True) : 
  Forbidden model combination
```

**Comment by MichalChromcak** [comment] 2019-11-13 07:43
Hi @ChadFulton, thank you for the quick analysis. Do you feel like adding such restrictions also to statsmodels is a way to go?
![image](https://user-images.githubusercontent.com/12393430/68742935-99929880-05f1-11ea-8953-de4394f50eba.png)
Image sourced from https://github.com/robjhyndman/forecast/blob/master/R/ets.R

**Comment by atj01** [comment] 2019-11-13 07:52
Hi @ChadFulton, I'm working with @MichalChromcak  and just want to chip in for a moment. I had a quick look at the implementation. I think I the issue is coming indeed from the combination of the multiplicative nature of the trend and the presence of damping. For multiplicative trend the damping factor appears in the exponent of the trend slope, b, which causing the trouble if the trend slope becomes negative.

**Comment by ChadFulton** [comment] 2019-11-13 21:12
Thanks for following up! I want to double check the results with a
different implementation of this model tonight, and I’ll hopefully have
more details then.

**Comment by ChadFulton** [comment] 2019-11-15 05:24
I haven't had time to fully investigate what our code is doing here, but I think the following three comments are safe to make:

- These models are known to have numerical issues in long samples (see Hyndman et al., Chapter 15)

- However, they should be okay for short well-behaved samples like in the example you have given, so I think that our code should be able to handle this case. I think that we could make our code more numerically robust.

- Practically, though, if you don't have a pressing reason to use this model, I would probably suggest using a more numerically stable specification.

I'll update if I learn more about the details here.

**Comment by MichalChromcak** [comment] 2019-11-15 08:56
Thanks Chad. Can you control the behavior of predictions and in case any model should return NaNs, an exception would be raised instead? Or is there a different motivation why forecast/predict method should return NaNs?

**Comment by ChadFulton** [comment] 2019-11-16 01:42
> Thanks Chad. Can you control the behavior of predictions and in case any model should return NaNs, an exception would be raised instead? Or is there a different motivation why forecast/predict method should return NaNs?

I think that this is a good idea here.

We have to be a little careful in general as some results may be valid even if some others are invalid. For example: if you fit a really short state space model, then we can't run the heteroskedasticity tests, so those results show up as NaNs, but that's still okay.

**Comment by bashtage** [comment] 2020-07-28 13:54
Fixed in master.

**Closed by bashtage** 2020-07-28 13:54 UTC
Labels: comp-tsa, type-bug

**Comment by mloning** [comment] 2021-04-09 11:27
Using the original example and changing `seasonal='add'` to `seasonal='mul'` also results in `nan` values. Can someone confirm this? Should I raise a new issue?

```python
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing

y = [2342., 2226., 2487., 3082., 2735., 2178., 1717., 2182., 2215., 1663., 1067., 1261.,
     1073.,  986.,  559.,  990., 1561., 1665., 1528., 1807., 1402., 1045.,  981., 1369.,
     1417., 1317., 1256., 1574., 1652., 1479., 1427., 1658., 1738., 1579., 1460., 1863.,
     1749., 1422., 1189.,  972.,  949., 1028.,  660.,  806., 1049.,  974.,  800.]

X = pd.date_range(start='2000-09-30', periods=len(y), freq='Q').astype(str)

endog = pd.DataFrame(X).assign(y=y).set_index(0)

exp_smooth = ExponentialSmoothing(endog=endog, 
                                  damped=True, 
                                  dates=None,
                                  freq=None,                                  
                                  missing='none', 
                                  seasonal='mul', 
                                  seasonal_periods=4, 
                                  trend='mul')
exp_smooth_fitted = exp_smooth.fit()
exp_smooth_fitted.forecast(5)
```
```
2012-06-30   NaN
2012-09-30   NaN
2012-12-31   NaN
2013-03-31   NaN
2013-06-30   NaN
Freq: Q-DEC, dtype: float64
```
#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
INSTALLED VERSIONS
------------------
Python: 3.7.8.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

statsmodels
===========

Installed: 0.12.1 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.21 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/Cython)
numpy: 1.19.5 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/numpy)
scipy: 1.6.0 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/scipy)
pandas: 1.2.2 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.4 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.16.0 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.20.0 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/IPython)
    jinja2: 2.11.3 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/jinja2)
sphinx: 3.2.1 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/sphinx)
    pygments: 2.7.4 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/pygments)
pytest: 6.0.1 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/pytest)
virtualenv: 20.0.31 (/Users/mloning/.conda/envs/sktime-dev/lib/python3.7/site-packages/virtualenv)

<details>

**Comment by bashtage** [comment] 2021-04-09 11:31
Works for my using master, so probably same fix.

**Comment by mloning** [comment] 2021-04-09 11:41
Thanks @bashtage - so the fix hasn't been released yet?

**Comment by bashtage** [comment] 2021-04-09 11:45
That is correct.  Probably wont be until Summer.  You can either build and install master or possiblly install a nightly from

https://anaconda.org/scipy-wheels-nightly/statsmodels

(these are a bit old and I'm not sure fixed).

**Comment by rpalsaxena** [comment] 2022-11-14 10:28
I am facing same issue.
```
y = [y
10240.6707
12730.06833
10563.95171
10943.7432
9893.5543
9926.21115
10144.79565
7025.33545
9659.93493
11574.38295
11739.101999999999
10090.13145
6526.8405
3479.16
5975.16795
8524.22835
5953.44108
8586.31995
7650.7017
7605.8535
9793.58158
9820.00617
7654.6375499999995
10624.35495
12372.993
9201.82572
8859.95127
16800.83265
15982.8384
12593.2464
14318.515949999999
14085.627
14463.43275
16583.19045
13459.77075
18028.65125
18487.72155
13486.9471
16245.9805
16068.44531
12798.49461
14120.20355
19744.46865
17212.4376
20192.36865
25979.19265
15522.99822
19337.9061
17343.32375
18590.71015
21813.6709
15141.456
18820.36552
16066.7072
9950.53731
8999.7915
5391.848849999999
7849.0965
9793.02195
10717.319
14723.71515
8937.2784
10092.9064
10701.69985
11510.16275
17251.85145
14470.291
16716.83845
14831.16189
15178.6342
16912.44145
18533.6018
16796.67615
16733.24775
13389.14601
15173.22195
12815.43845
12740.75775
10477.6358
12122.4558
15629.6057
17924.1415
14476.5143
143.5
70.0
21.44
45.72
13368.0773
13922.893049999999
21267.94135
17608.9902
15046.4007
14842.9534
13648.23195
16903.49165
19335.25646
13716.635549999999
19996.69333
19025.20127
14616.80409
21141.33942
17414.92985
18448.9051
7215.6384
21070.6302
19053.89255
13668.29375
14445.71505
9083.9974
11859.489300000001
18208.29175
19045.40625
14363.129
1173.7468
141.68
41.379999999999995
110.5
80.38
65.6
297.56
212.86
156.66
109.0
1.8]

model = ExponentialSmoothing(train['y'],   
        seasonal_periods=12,
        trend="add",
        seasonal="add",
        use_boxcox=True,
        initialization_method="estimated")
model = model.fit()
forecast = model.predict(start=len(train), end=len(train) + (1 - 1))
print(forecast)
```

It's giving Nan values as output.
```

**Comment by ChadFulton** [comment] 2022-11-15 19:23
@rpalsaxena the problem here is the boxcox transformation. If I remove the boxcox transformation and plot the output of `model.predict(start=0, end=len(train) + (1 - 1))`, then I get the following figure:

![image](https://user-images.githubusercontent.com/280864/202006900-7cad6394-edad-4e90-ad7c-ee460c901799.png)

Notice that a number of the predictions, including the last one (which is the forecast that you're printing in your code) are negative.  Because the boxcox transformation doesn't support negative values, when it is reversed, it results in the NaN value that you're seeing.
